---
title: "Presentaciones"
toc: false
---

::: {.p-lede}
Por favor, seleccione una de las lecturas marcadas con una "+" de la lista de lecturas y envíe un correo al profesor para que se le asigne una fecha de presentación.
:::

<div class="tbl-wrap">
<table class="pres">
<thead><tr><th>Autores</th><th>Tema</th><th>Presentador(a)</th><th>Fecha de exposición</th></tr></thead>
<tbody>

<tr><td> Seira, Elizondo & Laguna (2017) </td><td><span class="topic-tag">Experimental</span></td><td class="who"> Oren Nava </td><td>Jueves 10 de septiembre</td></tr>

<tr><td> Arceo & Campos (2014) </td><td><span class="topic-tag">Experimental</span></td><td class="who"> Jareth Mejía </td><td>Martes 15 de septiembre</td></tr>

<tr><td> De la O & García (2023) </td><td><span class="topic-tag">Experimental</span></td><td class="who"> Jhonatan Román </td><td>Martes 15 de septiembre</td></tr>

<tr><td> De la O (2013) </td><td><span class="topic-tag">LATE</span></td><td class="who"> Sagrario Fuentes </td><td>Martes 29 de septiembre</td></tr>

<tr><td> Espinosa & Rubin (2015) </td><td><span class="topic-tag">Selección por observables</span></td><td class="who"> Valeria Servín </td><td>Martes 13 de octubre</td></tr>

<tr><td> Cabrera & Padilla-Romo (2023) </td><td><span class="topic-tag">DID</span></td><td class="who"> Edel Araiza </td><td>Martes 20 de octubre</td></tr>

<tr><td> Samaniego & Fernández (2024) </td><td><span class="topic-tag">DID</span></td><td class="who"> Sandra Martínez </td><td>Jueves 22 de octubre</td></tr>

<tr><td> Chort & Öktem (2024) </td><td><span class="topic-tag">DID</span></td><td class="who"> Andrea Blake </td><td>Jueves 22 de octubre</td></tr>

<tr><td> Aguilar & Seira (2021) </td><td><span class="topic-tag">Discontinuidades</span></td><td class="who"> Itzel Lara </td><td>Jueves 5 de noviembre</td></tr>

<tr><td> Alcocer, Skillman & Torres (2025) </td><td><span class="topic-tag">Discontinuidades</span></td><td class="who"> Laura Cordero </td><td>Jueves 5 de noviembre</td></tr>

<tr><td> Campos & Esquivel (2023) </td><td><span class="topic-tag">Control sintético</span></td><td class="who"> Leonardo Ortega </td><td>Jueves 19 de noviembre</td></tr>

<tr><td> Boly & Sanou (2022) </td><td><span class="topic-tag">Control sintético</span></td><td class="who"> Carlos Vargas </td><td>Jueves 19 de noviembre</td></tr>

<tr><td> Cepeda-Francese & Ramírez-Álvarez (2023) </td><td><span class="topic-tag">Control sintético </span></td><td class="who"> Christian Ramírez </td><td> Jueves 19 de noviembre </td></tr>

<tr><td> PD </td><td><span class="topic-tag">Machine learning</span></td><td class="who"> PD </td><td>Jueves 3 de diciembre</td></tr>

</tbody>
</table>
</div>
