{
  "hash": "7901b1d52a2f3c30c91da5aff58c8aa1",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat:\n  revealjs:\n    theme: [\"./theme-ic.scss\"]\n    width: 1600\n    height: 900\n    slide-number: c/t\n    center: false\n    scrollable: false\n    title-slide: false\n    logo: logo-CIDE.jpg\n    footer: \"Inferencia Causal · Emparejamiento\"\n    include-in-header:\n      - _ic-header.html\n      - fontawesome.html\n---\n\n\n\n\n\n\n# Emparejamiento {.portada background-color=\"#163D34\" data-state=\"nochrome\"}\n\n::: {.pa-eyebrow}\nInferencia Causal\n:::\n\n[Irvin Rojas]{.pa-name} <span class=\"pa-icons\"><a href=\"https://github.com/rojasirvin\" target=\"_blank\" aria-label=\"GitHub\"><i class=\"bi bi-github\"></i></a> <a href=\"https://scholar.google.com/citations?hl=es&user=FUwdSTMAAAAJ&view_op=list_works&sortby=pubdate\" target=\"_blank\" aria-label=\"Google Scholar\"><i class=\"bi bi-mortarboard-fill\"></i></a> <a href=\"mailto:irvin.rojas@cide.edu\" aria-label=\"Correo\"><i class=\"bi bi-envelope-fill\"></i></a></span>\n\n::: {.pa-inst}\nCentro de Investigación y Docencia Económicas<br>Maestría en Economía\n:::\n\n::: {.cell}\n<style type=\"text/css\">\n.huge .remark-code { /*Change made here*/\n  font-size: 200% !important;\n}\n.tiny .remark-code { /*Change made here*/\n  font-size: 60% !important;\n}\n</style>\n:::\n\n\n# Emparejamiento {.divider background-color=\"#9B2247\" data-state=\"nochrome\"}\n\n\n# Estas primeras secciones estaban en regresión\n\n\n\n## Supuesto de independencia condicional\n\n- El **supuesto de independencia condicional** significa que, condicional en una serie de características $X_i$, el sesgo de selección desaparece:\n\n$$\\{y_{0i},y_{1i}\\}\\perp D_i | X_i$$\n\n::: {.fragment}\n\n- Supongamos que $D_i$ es ir o  no a la universidad y la variable de interés es el ingreso\n- Sabemos que la comparación observacional nos da:\n\n$$\n\\begin{aligned}\nE(y_i|D_i=1)-E(y_i|D_i=0)=&\\overbrace{ E(y_{1i}-y_{0i}|D_i=1)}^{\\text{Efecto promedio en los tratados}}+\\\\& \\underbrace{E(y_{0i}|D_i=1)-E(y_{oi}|D_i=0)}_{\\text{Sesgo de selección}}\n\\end{aligned}\n$$\n\n- Es posible que aquellos que no fueron a la universidad de todos modos hubieran tenido un mayor salario, por lo que el sesgo de selección es positivo\n\n:::\n\n\n## Supuesto de independencia condicional\n\n- El SIC implica que si hacemos la comparación condicional en $X_i$, el sesgo desaparece\n$$\n\\begin{aligned}\nE(y_i|X_i,D_i=1)-E(y_i|X_i,D_i=0)=E(y_{1i}-y_{0i}|X_i)\n\\end{aligned}\n$$\n- Es decir, que si comparamos a personas con y sin tratamiento, con los $X_i$ *fijos*, el sesgo de selección desaparece\n\n- *Mantener fijas* las $X$ es el análogo a obtener el promedio del salario en cada nivel de escolaridad en la gráfica de la FEC descrita anteriormente\n\n\n## Supuesto de independencia condicional\n\n- Para generalizar el concepto cuando la variable tiene más de dos valores (como con la educación $s_i$), escribamos $Y_{si}\\equiv f_i(s)$\n\n- Esta función nos dice cuál sería el ingreso de $i$ bajo todos los posibles niveles de $s$\n\n- En este caso, asumimos el SIC, que se traduce en: $$Y_{si}\\perp s_i | X_i$$\n\n- En diseños experimentales, el SIC surge porque el tratamiento se asigna de forma aleatoria\n\n- Pero con datos *observacionales*, el SIC significa que $s_i$ es *casi como si fuera asignado de manera aleatoria* cuando condicionamos en $X_i$\n\n## Supuesto de independencia condicional\n\n- En los datos solo observamos $Y_i=f_i(s_i)$\n- Dado el SIC, podemos hacer comparaciones de ingreso promedio para distintos niveles de educación:\n$$E(Y_i|X_i,s_i=s)-E(Y_i|X_i,s_i=s-1)=E(f_i(s)-f_i(s-1)|X_i)$$\n\n::: {.fragment}\n\n- Notemos que lo impráctico de esto es que tendríamos que hacer comparaciones en pares y luego tratar de hacer un promedio ponderado por el número de individuos en cada nivel de educación\n\n:::\n\n\n## Regresión para hacer las comparasiones\n\n- Supongamos una función causal para el ingreso\n$$f_i(s)=\\alpha+\\rho s+\\nu_i$$\n\nque indica lo que un individuo ganaría para todo valor de $s$ (y no solo el valor realizado $s_i$)\n\n- La única parte aleatoria es el error con media cero $\\nu_i$, que captura los factores no observados que afectan los ingresos\n\n- Sustituyendo el valor observado:\n\n$$Y_i=\\alpha+\\rho s_i+\\nu_i$$\n\n- $s_i$ puede estar correlacionado con los resultados potenciales $f_i(s)$, es decir, correlacionado con el error $\\nu_i$\n\n\n## Regresión para hacer las comparasiones\n\n- Supongamos que el SIC se cumple dado un vector $X_i$\n\n- Descompongamos el error en una función lineal de las características $X_i$ y un error $u_i$:\n$$\\nu_i=X_i'\\gamma+u_i$$\n\ndonde se asume que $E(\\nu_i|X_i)=X_i'\\gamma$ y donde $u_i$ y $X_i$ no están correlacionados\n\n- Si se cumple el SIC, entonces:\n\n$$\n\\begin{aligned}\nE(f_i(s)|X_i,s_i)=E(f_i(s)|X_i)&=\\alpha+\\rho s+E(\\nu_i|X_i) \\\\\n&=\\alpha+\\rho s + X_i'\\gamma\n\\end{aligned}\n$$\n\n- Es decir, en el modelo de regresión causal\n$Y_i=\\alpha+\\rho s_i+ X_i'\\gamma+u_i$, $u_i$ no está correlacionado con los regresores $X_i$ y $s_i$\n\n- $\\rho$ es el efecto causal de interés\n\n- El supuesto clave es que la única razón por la cual $\\nu_i$ y $s_i$ están correlacionados es $X_i$\n\n\n# Fin de lo traído desde regresión\n\n\n## Sesgo de selección\n \nLas razones que determinan la asignación del tratamiento pueden también determinar el valor de $Y$. Entonces, una comparación observacional nos da el efecto del tratamiento más el sesgo de selección:\n    \n$$\n\\begin{aligned}\nE(y_i|D_i=1)-E(y_i|D_i=0)=&\\overbrace{ E(y_{1i}|D_i=1)-E(y_{0i}|D_i=1)}^{\\text{Efecto promedio en los tratados}}+\\\\& \\underbrace{E(y_{0i}|D_i=1)-E(y_{oi}|D_i=0)}_{\\text{Sesgo de selección}}\n\\end{aligned}\n$$\n\nUna forma de eliminar el sesgo de selección es mediante la asignación aleatoria del tratamiento; sin embargo, esto no siempre es posible por lo que recurrimos a supuestos para eliminar el sesgo de selección.\n \n\n## Supuesto de independencia\n\nEl *supuesto de independencia* condicional dice que al *controlar* por una serie de características $X_i$, el tratamiento es *como* si fuera aleatorio:\n\n\n$$\nE(Y(1)|D=1,X)=E(Y(1)|D=0,X)\n$$\n\n$$\nE(Y(0)|D=1,X)=E(Y(0)|D=0,X)\n$$\n\nEsto es, los valores esperados de $Y(1)$ y $Y(0)$ son iguales cuando nos fijamos en cada valor de $X$.\n\n# Matching exacto {.divider background-color=\"#9B2247\" data-state=\"nochrome\"}\n\n## Matching exacto\n \nUn estimador de matching exacto consiste en *emparejar* individuos tratados y no tratados para cada valor específico de las $X$ y luego tomar el promedio ponderado de las diferencias.\n  \nTenemos datos observacionales de individuos que recibieron y no recibieron un tratamiento y tenemos una serie de características discretizadas en $X_i$.\n\nAsumimos que controlando por las características $X_i$ podemos obtener diferencias causales y luego hacemos un promedio de dichas diferencias.\n\n\n## Ejemplo: programa hipotético de empleo\n\nUsemos [el ejemplo](https://mixtape.scunning.com/matching-and-subclassification.html?panelset=r-code) de MT (The Mixtape):\n\n\n::: {.cell}\n\n:::\n\n\n## Ejemplo: programa hipotético de empleo\n\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\nLos individuos tratados:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 3\n   unit_treat age_treat earnings_treat\n        <dbl>     <dbl>          <dbl>\n 1          1        18           9500\n 2          2        29          12250\n 3          3        24          11000\n 4          4        27          11750\n 5          5        33          13250\n 6          6        22          10500\n 7          7        19           9750\n 8          8        20          10000\n 9          9        21          10250\n10         10        30          12500\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\nMientras que los no tratados:\n  \n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 3\n   unit_control age_control earnings_control\n          <dbl>       <dbl>            <dbl>\n 1            1          20             8500\n 2            2          27            10075\n 3            3          21             8725\n 4            4          39            12775\n 5            5          38            12550\n 6            6          29            10525\n 7            7          39            12775\n 8            8          33            11425\n 9            9          24             9400\n10           10          30            10750\n11           11          33            11425\n12           12          36            12100\n13           13          22             8950\n14           14          18             8050\n15           15          43            13675\n16           16          39            12775\n17           17          19             8275\n18           18          30             9000\n19           19          51            15475\n20           20          48            14800\n```\n\n\n:::\n:::\n\n:::\n\n::::\n\n\n\n\n\n\n\n## Comparación observacional\n\nSi hiciéramos diferencias simples obtendríamos:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(data.treat$earnings_treat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11075\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(data.control$earnings_control)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11101.25\n```\n\n\n:::\n\n```{.r .cell-code}\n#Diferencia\nmean(data.treat$earnings_treat)- mean(data.control$earnings_control)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -26.25\n```\n\n\n:::\n:::\n\n\nParece que en el grupo de control ganan más (efecto de tratamiento negativo).\n\nEl principal problema con esta diferencia es que sabemos que los ingresos crecen con la edad. Pero notemos que la muestra de no tratados tiene mayor edad promedio:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(data.treat$age_treat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24.3\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(data.control$age_control)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 31.95\n```\n\n\n:::\n\n```{.r .cell-code}\n#Diferencia\nmean(data.treat$age_treat)- mean(data.control$age_control)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -7.65\n```\n\n\n:::\n:::\n\n\nEs decir, estaríamos *confundiendo* el efecto de la edad.\n\n\n## Muestra emparejada\n\n\nConstruyamos la muestra apareada: para cada individuo en el grupo tratado, buscaremos uno en el de control que tenga la misma edad. Cuando le encontramos un individuo no tratado al tratado con la misma edad decimos que esa pareja hizo *match*.\n\nPor ejemplo, la primera unidad tratada, con 18 años y un ingreso de 9500 estaría emparejada con la unidad 14 del grupo de control, que tiene también 18 años y un ingreso de 8050.\n\nPara dicho individuo de 18 años, su ingreso contrafactual sería 8050.\n\nCuando hay varias unidades en el grupo de control que pueden ser empatadas con la de tratamiento, podemos construir el ingreso contrafactual calculando el promedio.\n\nDel grupo de control, los individuos 10 y 18 tienen 30 años, con ingresos 10750 y 9000, por lo que usamos el promedio (9875) para crear el contrafactual del individuo tratado de 30 años de la fila 10.\n\n## Muestra emparejada\n\nLa muestra emparejada o contrafactual será:\n\n\n::: {.cell output-location='column'}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 3\n   unit_matched age_matched earnings_matched\n          <dbl>       <dbl>            <dbl>\n 1            1          18             8050\n 2            2          29            10525\n 3            3          24             9400\n 4            4          27            10075\n 5            5          33            11425\n 6            6          22             8950\n 7            7          19             8275\n 8            8          20             8500\n 9            9          21             8725\n10           10          30             9875\n```\n\n\n:::\n:::\n\n\n## Muestra emparejada\n\nNoten que la edad es la misma entre los tratados y la muestra apareada:\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\nMuestra de tratados:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(data.treat$age_treat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24.3\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\nMuestra emparejada:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(data.matched$age_matched)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24.3\n```\n\n\n:::\n:::\n\n:::\n\n::::\n\n\nEn este caso, decimos que la edad *está balanceada*.\n\nY entonces podemos calcular el efecto de tratamiento como la diferencia de ingresos entre los tratados y los no tratados en la muestra emparejada:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1695\n```\n\n\n:::\n:::\n\n\nEn este caso, encontramos un efecto positivo del programa de 1695 unidades monetarias.\n\n## Estimador de matching exacto\n\nLo anterior nos permite definir el **estimador de matching exacto del TOT** como:\n\n$$\\hat{\\delta}_{TOT}=\\frac{1}{N_T}\\sum_{D_i=1}\\left(Y_i-\\left(\\frac{1}{M}\\sum_{m=1}^{M}Y_{jm(i)}\\right)\\right)$$\n\n## Importancia del soporte común\n\nObservemos lo que ocurre con la distribución de edades en ambos grupos:\n\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\nPara los tratados:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](figures/grafica_tratados-1.png){width=672}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\nMientras que para los no tratados:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](figures/grafica_notratados-1.png){width=672}\n:::\n:::\n\n:::\n\n::::\n\nEl supuesto de traslape débil para identificar el TOT significa que para cada unidad tratada, hay al menos un no tratado. De otra forma, no podemos hacer la comparación.\n\n\n\n\n## Estimador de matching exacto\n\n\n- Hasta aquí, solo hemos imputado el contrafactual para cada unidad en el grupo tratado\n\n- Si podemos imputar también, para cada unidad no tratada, su correspondiente contrafactual tratado, podemos estimar el ATE\n\n- Y un **estimador de matching exacto del ATE** sería:\n\n\n$$\\hat{\\delta}_{ATE}=\\frac{1}{N}\\sum_{i}^N(2D_i-1)\\left(Y_i-\\left(\\frac{1}{M}\\sum_{m=1}^{M}Y_{jm(i)}\\right)\\right)$$\n\n\n## Ejemplo de la vida real\n\n- Tenemos varias características en $X_i$, no solo la edad\n\n- Esto hace que cada valor $X_i=x_i$ este representado por una *celda*\n    \n- $X_i$ incluye, por ejemplo, raza, año de solicitud de ingreso al programa, escolaridad, calificación en examen de aptitud, año de nacimiento (son las características del ejemplo que vermeos más adelante)\n  \n- Estas características definen *celdas* y dentro de cada celda tenemos tratados y no tratados\n \n\n## Efecto del tratamiento con matching exacto\n \n- El TOT asumiendo inconfundibilidad:\n\n$$\n\\begin{aligned}\n\\delta^M=TOT&=E\\left\\{ E(y_{1i}|X_i,D_i=1)-E(y_{0i}|X_i,D_i=0)|D_i=1\\right\\} \\\\\n&=E\\left\\{\\delta_X | D_i=1\\right\\}\n\\end{aligned}\n$$\n\n\n- $\\delta_X$ es la diferencia de ingresos promedio entre estados de tratamiento para cada valor de $X_i$\n    \n- Con $X_i$ discreta y con una muestra disponible:\n\n$$\n\\delta^M=\\sum_{x} \\delta_x P(X_i=x|D_i=1)\n$$\n\n## Ejemplo: veteranos de guerra en Estados Unidos\n\n- [Angrist (1998)](https://www.jstor.org/stable/2998558), Estimating the Labor Market Impact of Voluntary Military Service Using Social Security Data on Military Applicants\n\n- El tratamiento es haber servido en el ejercito, algo que claramente tiene autoselección\n\n- Se trata de estimar el efecto en el ingreso\n\n- Los autores construyen celdas de acuerdo a las características antes mencionadas\n\n  - Raza, año de solicitud de ingreso al programa, escolaridad, calificación en examen de aptitud, año de nacimiento\n\n\n## Ejemplo: veteranos de guerra en Estados Unidos\n\n\n- Efectos estimados usando distintas metodologías\n\n- Los impactos estimados usando el matching exacto se encuentran bajo la columna *Controlled contrast*\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ExactMatching_effects_table_a.jpg)\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ExactMatching_effects_table_b.jpg)\n:::\n:::\n\n:::\n\n::::\n\n\n\n\n## Ejemplo: veteranos de guerra en Estados Unidos\n\n- Noten que la columna (2) muestra lo que se hubiera concluido si solo se comparan diferencias de medias\n    \n- Antes de 1980, las diferencias eran muy pequeñas (cero en términos prácticos)\n  \n- En esta aplicación esta comparación llevaría a conclusiones incorrectas\n  \n- Además, las diferencias para no-blancos y blancos son distintas\n  \n- Hay un pico en los efectos alrededor de 1982\n  \n- En esta aplicación, los resultados por *matching* y regresión son muy parecidos hasta 1984\n  \n- La conclusión es que existe evidencia de efectos negativos en los ingresos por haber servido en el ejército en los blancos y efectos positivos para los individuos de otras razas\n\n\n## Ejemplo: veteranos de guerra en Estados Unidos\n\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\nPara personas identificadas como blancas:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ExactMatching_effects_graph_a.jpg)\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\nPara personas identificadas como no blancas:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ExactMatching_effects_graph_b.jpg)\n:::\n:::\n\n:::\n\n::::\n\n\n\n# Propensity Score Matching {.divider background-color=\"#9B2247\" data-state=\"nochrome\"}\n\n\n## Métodos de apareamiento o *matching*\n\n- Los métodos apareamiento o *matching* recaen en el **supuesto de independencia condicional**\n\n- Al *controlar* por una serie de características $X_i$, el tratamiento es *como* si fuera aleatorio\n\n- Podemos escribir\n\n$$\nE(Y(1)|D=1,X)=E(Y(1)|D=0,X)\n$$\n\n$$\nE(Y(0)|D=1,X)=E(Y(0)|D=0,X)\n$$\n\n- Esto es, los valores esperados de $Y(1)$ y $Y(0)$ son iguales cuando nos fijamos en cada valor de $X$\n\n\n## Supuestos de identificación del TOT\n \n**Supuesto 1. Inconfundibilidad**\n  \n$$\nY(0), Y(1) \\perp  D|X\n$$\n\n- Dado un conjunto de variables $X$, los resultados potenciales son independientes del tratamiento\n  \n- $X$ debe incluir todas las variables que determinan el tratamiento y los resultados potenciales\n  \n**Supuesto 2: Traslape**\n  \n$$\n0< P(D=1|X) < 1\n$$\n\n- $X$ no predice $D$ perfectamente\n  \n- Personas con el mismo $X$ tienen probabilidad positiva de ser tratados y no tratados\n\n\n## Supuestos de identificación del TOT\n \n- Cuando se cumple **Supuesto 1** $+$ **Supuesto 2**  se conoce como **ignorabilidad fuerte**\n  \n- Heckman (1998) muestra que estás condiciones son demasiado estrictas\n  \n- Para identificar el $TOT$ es suficiente:\n    \n- **Supuesto 1a. Inconfundibilidad en el control**\n\n$$\nY(0) \\perp  D | X\n$$\n\n- **Supuesto 2a. Traslape débil**\n\n$$\nP(D=1|X) < 1\n$$\n\n\n## Matching exacto es impráctico\n \n  - En la práctica es difícil manejar problemas en espacios de múltiples dimensiones: **maldición de la dimensionalidad**\n \n- El problema de la maldición de la dimensionalidad se exacerba con el tamaño limitado de las bases de datos\n \n- Si $X$ tuviera solo indicadores binarios, el número de posibles combinaciones sería $2^s$\n   \n- Por ejemplo, si solo tuviéramos $X_1=\\{\\text{menor de 35 años}, \\text{con 35 años o más}\\}$, $X_2=\\{\\text{más que preparatoria}, \\text{menos que preparatoria}\\}$, $X_3=\\{\\text{indígena}, \\text{no indígena}\\}$, tendríamos que hacer ocho comparaciones:\n   \n  - menor de 35 años, más que preparatoria, indígena\n  - menor de 35 años, más que preparatoria, no indígena\n  - ...\n  - con 35 años o más, menos que preparatoria, no indígena\n\n- Pero Si $X$ incluye muchas variables, algunas tomando muchos valores, esto se vuelve imposible de realizar\n  \n\n## Maldición de la dimensionalidad\n\n- El requerimiento de soporte común significa que debemos tener tratados y no tratados para cada valor de $X_i$ para hacer comparaciónes\n\n- Cuando $X_i$ tiene muchas dimensiones, resulta un problema de *escasez* o *sparseness*\n\n- Algunas celdas estarán vacías, o solo tendrán tratados, o solo tendrán no tratados\n\n\n- Si tenemos unidades en todas las celdas de control, **aún podemos estimar el TOT**\n\n  - Noten que cuando completamos la fase pareada en el ejemplo hipotético, siempre encontramos a alguien en el grupo de control para asignárselo a un tratado\n  \n  - Pero al revés, no siempre es posible: por ejemplo, no hay ningún tratado de 48 años\n\n\n\n## Teorema del PS (Rosenbaum y Rubin, 1983)\n \n- **Corolario 1. Inconfundibilidad dado el propensity score**\n \n- El **Supuesto 1** implica:\n \n$$\nY(0), Y(1) \\perp  D|P(X)\n$$\n \ndonde $P(X)=P(D=1|X)$ es la probabilidad de ser tratado dado un conjunto de covariables $X$, el *propensity score* o PS\n  \n\n## Efecto del tratamiento\n \n- El efecto del tratamiento, bajo el supuesto de inconfundibilidad dado el propensity score, es:\n   \n$$\nTOT^{PSM}=E_{P(X)|D=1} \\left(E(Y(1)|D=1, P(X))-E(Y(0)|D=0,P(X)) \\right)\n$$\n \n \n- El $TOT$ es la diferencia en la variable de resultados de los tratados y los no tratados pesada por la distribución del PS en los tratados\n  \n\n\n## Estimación\n \n- Debemos por tanto primero calcular el PS\n \n- Se empatan o se hace match de unidades que fueron tratadas con unidades que no lo fueron usando el PS\n \n- Se mide la diferencia en la variable de resultados entre estos grupos\n \n- Se hace un promedio ponderado de las diferencias\n  \n\n## Implementación\n\n1. Estimación del PS\n \n2. Escoger el algoritmo de matching\n \n3. Comprobar la calidad del matching\n \n4. Estimar el $TOT$\n\n\n## Especificar el modelo del PS\n \n- Se usa un modelo *probit* o *logit*\n \n  - **Prueba y error**.   Maximizar la tasa clasificación de tratamientos y controles usando $\\bar{P}$, la proporción de tratamientos en la muestra\n \n  - **Significancia estadística**.   Usar solo las variables estadísticamente significativas, comenzando con un modelo muy básico\n \n  - **Validación cruzada**.   Comenzar con un modelo simple y agregar grupos de variables comparando las que reduzcan el error cuadrático promedio\n\n- El propósito del PS es sobre todo generar balance de las variables en $X$\n\n\n# Algoritmos de matching {.divider background-color=\"#9B2247\" data-state=\"nochrome\"}\n\n\n## Vecino más cercano\n \n- A cada individuo del grupo tratado se le asigna uno del grupo de comparación en términos del PS\n \n- Puede hacerse con remplazo o sin remplazo\n \n- Puede emplearse también sobremuestreo (*oversampling*), es decir, asignar más de un individuo del grupo de comparación\n\n- Por ejemplo, NN 5 significa que a cada individuo tratado se le asignan los cinco individuos del grupo no tratado con los PS estimados más cercanos\n  \n  \n## Vecino más cercano\n\n\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n| Tratados | $\\hat{p}$ |\n|:---: |:---:|\n| a | 0.031 |\n| b | 0.042 |\n| c | 0.07 |\n| $\\vdots$ | $\\vdots$ |\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n| No tratados | $\\hat{p}$ |\n|:---: |:---:|\n| A | 0.034 |\n| B | 0.068 |\n| C | 0.21 |\n| $\\vdots$ | $\\vdots$ |\n\n:::\n\n::::\n\n\n\n\n\n\n\n\n- Con vecino más cercano, el individuo $a$ tratado estaría emparejado con el $A$ no tratado\n\n- Si el emparejamiento es con reemplazo, $A$ podría ser usado otra vez\ny $b$ también sería emparejado con $A$\n\n- Pero si el emparejamiento es sin reemplazo, $A$ ya no puede ser usado y a $b$ se le emparejaría con $B$\n\n- Cuando hacemos el pareamiento sin reemplazo, debemos tener una muestra lo suficientemente grande\n\n- El pareamiento sin reemplazo depende del orden en que se realice el procedimiento\n\n\n## Caliper y radio\n \n- El método de vecino más cercano puede generar malos emparejamientos si el vecino más cercano está muy lejos en términos del PS\n  \n- Especificar un *caliper* consiste en definir una vecindad aceptable de matching (el caliper) y elegir solo el vecino más cercano dentro del caliper\n \n- Con las funciones de R que usaremos más adelante, el *radio* consiste en definir cuántos individuos deberán ser apareados dado que están dentro del caliper\n  \n\n## Caliper\n\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n| Tratados | $\\hat{p}$ |\n|:---: |:---:|\n| a | 0.031 |\n| b | 0.042 |\n| c | 0.07 |\n| d | 0.11 |\n| $\\vdots$ | $\\vdots$ |\n\n:::\n\n::: {.column width=\"50%\"}\n\n| No tratados | $\\hat{p}$ |\n|:---: |:---:|\n| A | 0.034 |\n| B | 0.068 |\n| C | 0.21 |\n| D | 0.40 |\n| $\\vdots$ | $\\vdots$ |\n:::\n\n::::\n\n\n- El primer paso es fijar el caliper, por ejemplo, de 0.1\n\n- El caliper implica buscar al vecino más cercano dentro de una vecindad de 0.1\n\n- En este ejemplo $c$ podría ser solo emparejado con $B$ si $B$ aún está disponible (porque no ha sido emparejado con nadie o porque, aunque haya sido emparejado, el procedimiento se hace con reemplazo)\n\n\n## Caliper con sobremuestreo\n\n\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n| Tratados | $\\hat{p}$ |\n|:---: |:---:|\n| d | 0.31 |\n| e | 0.39 |\n| f | 0.44 |\n| g | 0.52 |\n| h | 0.55 |\n| i | 0.62 |\n| $\\vdots$ | $\\vdots$ |\n\n:::\n\n::: {.column width=\"50%\"}\n\n| No tratados | $\\hat{p}$ |\n|:---: |:---:|\n| R | 0.27 |\n| S | 0.29 |\n| T | 0.33 |\n| U | 0.49 |\n| V | 0.57 |\n| W | 0.61 |\n| $\\vdots$ | $\\vdots$ |\n\n\n:::\n\n::::\n\n\n\n- Si el caliper se realiza con sobremuestreo, con un caliper de 0.10 y 2 vecinos a $g$ se le asignarían $U$ y $V$ (si estuvieran disponibles)\n\n- Es decir, dentro del caliper, los dos individuos con el PS más cercano\n\n\n## Radio\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n| Tratados | $\\hat{p}$ |\n|:---: |:---:|\n| d | 0.31 |\n| e | 0.39 |\n| f | 0.44 |\n| g | 0.52 |\n| h | 0.55 |\n| i | 0.62 |\n| $\\vdots$ | $\\vdots$ |\n\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n| No tratados | $\\hat{p}$ |\n|:---: |:---:|\n| R | 0.27 |\n| S | 0.29 |\n| T | 0.33 |\n| U | 0.49 |\n| V | 0.57 |\n| W | 0.61 |\n| $\\vdots$ | $\\vdots$ |\n\n\n:::\n\n::::\n\n\n- Pero si ahora implementamos radio con un caliper de 0.10, a $g$ se le asignarían $U$, $V$ y $W$ (si estuvieran disponibles)\n\n- Es decir, todos los individuos dentro del caliper\n\n\n\n\n## Estratificación\n \n- Partir la región de soporte común en bloques de acuerdo al PS\n \n- Estimar el efecto de tratamiento dentro de cada bloque\n \n- No hay una regla sobre cuántos estratos usar. Se aconsajan generalmente cinco\n \n- Dentro de cada estrato debe haber balance de los covariables\n\n  \n\n\n## Kernel y métodos no paramétricos\n \n- Los métodos anteriores escogen solo unas cuantas unidades del grupo de comparación \n \n- Podemos escoger usar muchas o incluso todas las observaciones del grupo de comparación y pesarlas apropiadamente\n \n- Se reduce la varianza pues usamos más información, pero se sacrifica precisión pues se usan observaciones potencialmente muy distantes\n \n- Se le otorga más peso a las observaciones más cercanas y menos a las más distantes\n  \n\n## Kernel\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n| Tratados | $\\hat{p}$ |\n|:---: |:---:|\n| d | 0.31 |\n| e | 0.39 |\n| f | 0.44 |\n| g | 0.52 |\n| h | 0.55 |\n| i | 0.62 |\n\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n| No tratados | $\\hat{p}$ |\n|:---: |:---:|\n| R | 0.27 |\n| S | 0.29 |\n| T | 0.33 |\n| U | 0.49 |\n| V | 0.57 |\n| W | 0.61 |\n\n\n:::\n\n::::\n\n\n- Supongamos que estos son todos nuestros datos\n\n- Con un emparejamiento por kernel, a $d$ lo compararemos con todos los individuos, desde $R$ hasta $W$\n\n- La función kernel le dará más peso a $R$, un poco menos a $S$ y así hasta darle muy poco o casi nada de peso a $W$\n\n\n\n\n## ¿Qué método usar?\n \n- No hay un método claramente superior a todos los demás\n \n- Más aún, el desempeño de cada método depende de cada aplicación\n \n- La ruta más seguida es usar varios algoritmos y mostrar la robustez de los resultados a esta elección\n  \n\n\n\n## Comprobar empíricamente los supuestos\n \n- El parámetro $TOT$ solo se calcula sobre la región de sporte común por lo que se debe verificar el traslape del PS calculado para los tratados y no tratados\n \n- Otro de los teoremas de Rosenbaum y Rubin (1983) implica que\n\n$$\nX \\perp  D|P(X)\n$$\n \n- Esto es, que al controlar por el PS, las variables $X$ no deben proveer información sobre $D$\n   \n- Se recomienda también hacer una prueba de estratificación\n\n  1. Dividir el rango del soporte común en bloques \n \n  1. Hacer una prueba de medias del PS entre grupos dentro de cada bloque\n \n  1. Hacer una prueba de medias de cada variable en $X_i$  entre grupos dentro de cada bloque\n\n\n\n## Ilustración del soporte común\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Gertler_PSOverlap.png){width=218}\n:::\n:::\n\n\n\n\n# Ejemplo en R {.divider background-color=\"#9B2247\" data-state=\"nochrome\"}\n\n## Paquetes\n\nUsaremos dos paquetes nuevos: *MatchIt* y *cobalt*, que pueden descargar como cualquier otro paquete desde CRAN.\n\n## Datos no experimentales de una muestra de mujeres\n \nLos datos en [cattaneo_smoking.csv](cattaneo_smoking.csv) (Cattaneo, 2010) son de una muestra de mujeres que incluye un indicador de si la madre fumó durante el embarazo. El propósito es evaluar el efecto de fumar sobre el peso de los bebés al nacer. Se incluyen una serie de covariables que usaremos para modelar el *propensity score*.\n\n\n## *matchit* para realizar los emparejamientos\n\nLa función que usaremos para hacer los emparejamientos es *matchit* de la librería *MatchIt*. Antes de hacer los emparejamientos, construimos la dummy de tratamiento, **smoke**, una dummy para mujeres casadas, **married**, y una dummy para si el caso en cuestión es el primer bebé, **firstbaby**:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 4642 Columns: 24\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr  (5): mmarried, msmoke, mbsmoke, fbaby, prenatal1\ndbl (19): bweight, mhisp, fhisp, foreign, alcohol, deadkids, mage, medu, fag...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n\n## Comparación observacional\n\nNotemos que, si solo comparamos a las mujeres que fuman con las que no fuman, estamos comparando personas muy diferentes:\n\n\n\n::: {.cell output-location='column'}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_k4cvfx0wguld8hfb9y23 = TinyTable.createTableFunctions(\"tinytable_k4cvfx0wguld8hfb9y23\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '-1', j: 3 }, { i: '-1', j: 5 } ], css_id: 'tinytable_css_4tbnwr5y4kyrk2iwttum',}, \n          { positions: [ { i: '7', j: 2 }, { i: '7', j: 3 }, { i: '7', j: 4 }, { i: '7', j: 5 }, { i: '7', j: 6 }, { i: '7', j: 7 } ], css_id: 'tinytable_css_2m3zho09ey6pv57wfapv',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '4', j: 4 }, { i: '5', j: 4 }, { i: '6', j: 4 }, { i: '1', j: 5 }, { i: '2', j: 5 }, { i: '3', j: 5 }, { i: '4', j: 5 }, { i: '5', j: 5 }, { i: '6', j: 5 }, { i: '1', j: 6 }, { i: '2', j: 6 }, { i: '3', j: 6 }, { i: '4', j: 6 }, { i: '5', j: 6 }, { i: '6', j: 6 }, { i: '1', j: 7 }, { i: '2', j: 7 }, { i: '3', j: 7 }, { i: '4', j: 7 }, { i: '5', j: 7 }, { i: '6', j: 7 } ], css_id: 'tinytable_css_emlwgm1hdw0vjmuei6po',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 }, { i: '0', j: 7 } ], css_id: 'tinytable_css_i112rfu89fnf0bktih9h',}, \n          { positions: [ { i: '-1', j: 2 }, { i: '-1', j: 4 } ], css_id: 'tinytable_css_9u9ryo3s78a83dxqz378',}, \n          { positions: [ { i: '7', j: 1 } ], css_id: 'tinytable_css_fpzy64i0uix32lp7bnfu',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 } ], css_id: 'tinytable_css_n9ovfft0tpbdiwmj7yyz',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_3n1b0zyrf8t0z0rcdgya',}, \n          { positions: [ { i: '-1', j: 1 }, { i: '-1', j: 6 }, { i: '-1', j: 7 } ], css_id: 'tinytable_css_i11sk95z4prjh1d3o3fi',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_k4cvfx0wguld8hfb9y23.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_4tbnwr5y4kyrk2iwttum, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_4tbnwr5y4kyrk2iwttum {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: black; --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.03em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 3%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_2m3zho09ey6pv57wfapv, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_2m3zho09ey6pv57wfapv {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: right }\n    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_emlwgm1hdw0vjmuei6po, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_emlwgm1hdw0vjmuei6po { text-align: right }\n    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_i112rfu89fnf0bktih9h, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_i112rfu89fnf0bktih9h {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: right }\n    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_9u9ryo3s78a83dxqz378, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_9u9ryo3s78a83dxqz378 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: black; --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.03em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 3%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_fpzy64i0uix32lp7bnfu, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_fpzy64i0uix32lp7bnfu {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_n9ovfft0tpbdiwmj7yyz, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_n9ovfft0tpbdiwmj7yyz { text-align: left }\n    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_3n1b0zyrf8t0z0rcdgya, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_3n1b0zyrf8t0z0rcdgya {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_i11sk95z4prjh1d3o3fi, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_i11sk95z4prjh1d3o3fi {  position: relative; --border-bottom: 0; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_k4cvfx0wguld8hfb9y23\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Pruebas de balance</caption>\n        <thead>\n<tr>\n<th scope=\"col\" align=\"center\" colspan=1 data-row=\"-1\" data-col=\"1\"> </th>\n<th scope=\"col\" align=\"center\" colspan=2 data-row=\"-1\" data-col=\"2\">0</th>\n<th scope=\"col\" align=\"center\" colspan=2 data-row=\"-1\" data-col=\"4\">1</th>\n<th scope=\"col\" align=\"center\" colspan=1 data-row=\"-1\" data-col=\"6\"> </th>\n<th scope=\"col\" align=\"center\" colspan=1 data-row=\"-1\" data-col=\"7\"> </th>\n</tr>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Mean</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Std. Dev.</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Mean</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">Std. Dev.</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"6\">Diff. in Means</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"7\">p</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='7'>Fuente: Cattaneo (2009)</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">married</td>\n                  <td data-row=\"1\" data-col=\"2\">0.75</td>\n                  <td data-row=\"1\" data-col=\"3\">0.43</td>\n                  <td data-row=\"1\" data-col=\"4\">0.47</td>\n                  <td data-row=\"1\" data-col=\"5\">0.50</td>\n                  <td data-row=\"1\" data-col=\"6\">-0.28</td>\n                  <td data-row=\"1\" data-col=\"7\">0.00</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">firstbaby</td>\n                  <td data-row=\"2\" data-col=\"2\">0.45</td>\n                  <td data-row=\"2\" data-col=\"3\">0.50</td>\n                  <td data-row=\"2\" data-col=\"4\">0.37</td>\n                  <td data-row=\"2\" data-col=\"5\">0.48</td>\n                  <td data-row=\"2\" data-col=\"6\">-0.08</td>\n                  <td data-row=\"2\" data-col=\"7\">0.00</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">medu</td>\n                  <td data-row=\"3\" data-col=\"2\">12.93</td>\n                  <td data-row=\"3\" data-col=\"3\">2.53</td>\n                  <td data-row=\"3\" data-col=\"4\">11.64</td>\n                  <td data-row=\"3\" data-col=\"5\">2.17</td>\n                  <td data-row=\"3\" data-col=\"6\">-1.29</td>\n                  <td data-row=\"3\" data-col=\"7\">0.00</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\">nprenatal</td>\n                  <td data-row=\"4\" data-col=\"2\">10.96</td>\n                  <td data-row=\"4\" data-col=\"3\">3.52</td>\n                  <td data-row=\"4\" data-col=\"4\">9.86</td>\n                  <td data-row=\"4\" data-col=\"5\">4.21</td>\n                  <td data-row=\"4\" data-col=\"6\">-1.10</td>\n                  <td data-row=\"4\" data-col=\"7\">0.00</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">foreign</td>\n                  <td data-row=\"5\" data-col=\"2\">0.06</td>\n                  <td data-row=\"5\" data-col=\"3\">0.24</td>\n                  <td data-row=\"5\" data-col=\"4\">0.03</td>\n                  <td data-row=\"5\" data-col=\"5\">0.16</td>\n                  <td data-row=\"5\" data-col=\"6\">-0.03</td>\n                  <td data-row=\"5\" data-col=\"7\">0.00</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">mhisp</td>\n                  <td data-row=\"6\" data-col=\"2\">0.04</td>\n                  <td data-row=\"6\" data-col=\"3\">0.19</td>\n                  <td data-row=\"6\" data-col=\"4\">0.02</td>\n                  <td data-row=\"6\" data-col=\"5\">0.15</td>\n                  <td data-row=\"6\" data-col=\"6\">-0.01</td>\n                  <td data-row=\"6\" data-col=\"7\">0.05</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">fage</td>\n                  <td data-row=\"7\" data-col=\"2\">27.84</td>\n                  <td data-row=\"7\" data-col=\"3\">8.79</td>\n                  <td data-row=\"7\" data-col=\"4\">24.74</td>\n                  <td data-row=\"7\" data-col=\"5\">11.15</td>\n                  <td data-row=\"7\" data-col=\"6\">-3.10</td>\n                  <td data-row=\"7\" data-col=\"7\">0.00</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n\n## Estimación del PS\n\nUna manera de hacer más eficiente el uso de las *fórmulas* es usando *as.formula*:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nsmoke ~ married + firstbaby + medu + nprenatal + foreign + mhisp + \n    fage\n```\n\n\n:::\n:::\n\n\nUsamos *matchit* para estimar el PS y realizar los emparejamientos con el algoritmo que indiquemos:\n\n\n::: {.cell}\n\n:::\n\n\n## Estimación del PS\n\nEl resumen del procedimiento da bastante información sobre el pareamiento:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nmatchit(formula = ps, data = data.smoking, method = \"nearest\", \n    distance = \"logit\", replace = FALSE, ratio = 1)\n\nSummary of Balance for All Data:\n          Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean\ndistance         0.2568        0.1700          0.6673     1.4475    0.2002\nmarried          0.4734        0.7515         -0.5569          .    0.2781\nfirstbaby        0.3715        0.4531         -0.1689          .    0.0816\nmedu            11.6389       12.9299         -0.5955     0.7316    0.0717\nnprenatal        9.8623       10.9629         -0.2616     1.4301    0.0376\nforeign          0.0255        0.0598         -0.2181          .    0.0344\nmhisp            0.0243        0.0363         -0.0776          .    0.0120\nfage            24.7431       27.8444         -0.2782     1.6070    0.0468\n          eCDF Max\ndistance    0.3329\nmarried     0.2781\nfirstbaby   0.0816\nmedu        0.2549\nnprenatal   0.1259\nforeign     0.0344\nmhisp       0.0120\nfage        0.1377\n\nSummary of Balance for Matched Data:\n          Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean\ndistance         0.2568        0.2564          0.0033     1.0110    0.0005\nmarried          0.4734        0.4769         -0.0070          .    0.0035\nfirstbaby        0.3715        0.3981         -0.0551          .    0.0266\nmedu            11.6389       11.6019          0.0171     0.7064    0.0161\nnprenatal        9.8623        9.8588          0.0008     1.1543    0.0059\nforeign          0.0255        0.0174          0.0514          .    0.0081\nmhisp            0.0243        0.0231          0.0075          .    0.0012\nfage            24.7431       24.5799          0.0146     1.0787    0.0124\n          eCDF Max Std. Pair Dist.\ndistance    0.0093          0.0046\nmarried     0.0035          0.2202\nfirstbaby   0.0266          0.4575\nmedu        0.0417          0.5168\nnprenatal   0.0185          0.7039\nforeign     0.0081          0.2425\nmhisp       0.0012          0.2781\nfage        0.0556          0.6457\n\nSample Sizes:\n          Control Treated\nAll          3778     864\nMatched       864     864\nUnmatched    2914       0\nDiscarded       0       0\n```\n\n\n:::\n:::\n\n\n\n## Verificación del balance\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\nGráfico de nube:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](figures/unnamed-chunk-21-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTo identify the units, use first mouse button; to stop, use second.\n```\n\n\n:::\n:::\n\n\n\n:::\n\n::: {.column width=\"50%\"}\n\nHistograma:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](figures/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\n::::\n\n\n\n\n## Muestra emparejada\n\nPodemos guardar un objeto con la muestra emparejada usando *match.data* y observar quién hace match con quién:\n\n\n::: {.cell output-location='column'}\n::: {.cell-output .cell-output-stdout}\n\n```\n   [,1]  \n11 \"4130\"\n20 \"2234\"\n25 \"1740\"\n43 \"2857\"\n47 \"305\" \n49 \"1442\"\n```\n\n\n:::\n:::\n\n\n\n## Muestra emparejada\n\nUna propuesta para determinar si el emparejamiento fue exitoso es observar las diferencias promedio estandarizadas (SMD) entre los grupos tratados y no tratados, antes y después del emparejamiento. \n\n$$SMD_X=\\frac{\\bar{X}_T-\\bar{X}_{NT}}{\\sqrt{S^2_T+S^2_{NT}}}$$\n    \nTambién vale la pena no perder de vista la razón de varianzas (VR). Se espera que este ratio no sea muy distinto de 1 después de hacer el emparejamiento:\n    \n$$VR=\\frac{S^2_T}{S^2_{NT}}$$\n\nComo regla de dedo, una diferencia de 0.1 o menos en el SMD se considera un buen balance. Por ejemplo, la escolaridad de la madre tenía un SDM de -0.5955 en la muestra en bruto, pero con el emparejamiento el SDM se vuelve de solo 0.0171.\n\n## *Loveplot*\n\nUsando la librería *cobalt* podemos construir un *love plot* que representa gráficamente las diferencias antes y después del emparejamiento\n\n\n::: {.cell output-location='column'}\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in love.plot(bal.tab(m.out), threshold = 0.1): Standardized mean differences and raw mean differences are present in the same\nplot. Use the `stars` argument to distinguish between them and appropriately\nlabel the x-axis. See `love.plot()` for details.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](figures/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\n## Efecto de tratamiento\n\nExisten muchas maneras de explotar la muestra emparejada. Aquí veremos la más sencilla. Simplemente consideremos a la muestra emparejada como si viniera de un experimento. Sin embargo, debemos poner especial atención a la forma de hacer inferencia pues no debemos ignorar que el PS es estimado.\n\nDependiendo de si el emparejamiento ocurre con o sin reemplazo, y de la naturaleza de la variable dependiente, se recomiendan distintas maneras de estimar el efecto del tratamiento y hacer inferencia. Una buena guía está en la documentación de [MatchIt](https://kosukeimai.github.io/MatchIt/articles/estimating-effects.html).\n\nPor ejemplo, cuando se realiza el emparejamiento sin reemplazo, [Abadie & Spiess (2019)](https://www.tandfonline.com/doi/full/10.1080/01621459.2020.1840383?casa_token=7VdQFPydVtIAAAAA%3A3VRshT4TmqjnyzS2Nz2EBmFi54NlHDIWdtD-mDdAdPHuv51BhbXh1qYOwsRo8yH_WhA1UoUbvP0Kqg) muestran que podemos estimar los errores estándar simplemente agrupando a nivel de pareja (o grupo) emparejado (**subclass** es una columna que enumera a las parejas o grupos emparejados y es construida automáticamente por *matchit*).\n\n\n## Efecto de tratamiento\n\nUsando una regresión con la muestra emparejada\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n            Estimate Std. Error  t value  Pr(>|t|)    \n(Intercept) 3331.983     21.342 156.1200 < 2.2e-16 ***\nsmoke       -194.323     28.111  -6.9128 6.664e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n## Efecto de tratamiento\n\nAlgunos autores incluyen los covariables en su estimación:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n               Estimate  Std. Error t value  Pr(>|t|)    \n(Intercept) 2983.514088   76.563235 38.9680 < 2.2e-16 ***\nsmoke       -195.980548   27.934606 -7.0157 3.279e-12 ***\nmarried      114.170671   30.707023  3.7181 0.0002072 ***\nfirstbaby    -60.979001   30.195581 -2.0195 0.0435935 *  \nmedu           0.076364    5.385295  0.0142 0.9886879    \nnprenatal     32.235062    4.493034  7.1745 1.075e-12 ***\nforeign       25.827549  109.279251  0.2363 0.8131935    \nmhisp        111.852277   85.200388  1.3128 0.1894208    \nfage          -0.139045    1.429538 -0.0973 0.9225265    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nCuando el emparejamiento es con reemplazo, las unidades no tratadas son emparejadas varias veces (aparecen repetidas en la muestra emparejada), lo cual debe ser considerado para estimar los efectos del tratamiento y hacer inferencia. Por ejemplo, se puede usar *bootstrap* para obtener el error estándar del efecto del tratamiento cuando la variable de impacto es continua.\n\n\n\n## Recomendaciones prácticas\n \n- Las características $X$ que determinan la probabilidad de tratamiento deben ser observables\n \n- Las variables usadas para calcular el PS no deben haber sido afectadas por el tratamiento\n \n- Idealmente usamos variables $X$ pre-intervención\n \n- Cuando no hay $X$ pre-intervención, a veces se puede obtener el PS con variables post-intervención siempre y cuando estas no hayan sido afectadas por el tratamiento (pocas veces recomendado)\n\n- Se recomienda ampliamente ver:\n\n  - Caliendo, M., & Kopeinig, S. (2008). Some practical guidance for the implementation of propensity score matching. *Journal of Economic Surveys*, 22(1), 31-72.\n  \n  \n  \n## Conclusión\n\n- Las técnicas de PSM dependen de varios supuestos teoricos fuertes\n\n- La implementación implica que las variables en $X$ son aquellas que permiten hacer los supuestos de inconfundibilidad dado el PS\n\n- En la estimación del PS se toma la decisión sobre la forma funcional\n\n- Los efectos de tratamiento pueden ser distintos entre diferentes algoritmos de emparejamiento y la especificación del PS\n\n- La crítica más importante es que la mayoría de las veces nos preocupa más la autoselección basada en no observables que en observables\n\n- Pero muchas veces es todo lo que tenemos a la mano\n\n- Hay que hacer análisis de sensibilidad a las distintas decisiones\n\n- Presentar resultados transparentes\n\n\n\n\n\n# Emparejamiento {.final background-color=\"#9B2247\" data-state=\"nochrome\"}\n\n::: {.f-eyebrow}\nInferencia Causal\n:::\n\n::: {.f-inst}\n[Irvin Rojas](https://rojasirvin.github.io/)\n:::\n\n::: {.f-inst}\nCIDE · Maestría en Economía\n:::\n\n<span class=\"f-icons\"><a href=\"https://github.com/rojasirvin\" target=\"_blank\" aria-label=\"GitHub\"><i class=\"bi bi-github\"></i></a> <a href=\"https://scholar.google.com/citations?hl=es&user=FUwdSTMAAAAJ&view_op=list_works&sortby=pubdate\" target=\"_blank\" aria-label=\"Google Scholar\"><i class=\"bi bi-mortarboard-fill\"></i></a> <a href=\"mailto:irvin.rojas@cide.edu\" aria-label=\"Correo\"><i class=\"bi bi-envelope-fill\"></i></a></span>\n\n::: {.f-rule}\n:::\n\n::: {.f-copy}\n© 2026 Irvin Rojas. Distribuido bajo licencia Creative Commons **CC BY-NC-SA 4.0**. Los materiales de terceros citados conservan sus propios derechos.\n:::\n",
    "supporting": [
      "emparejamiento_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}