<!DOCTYPE html>
<html lang="en"><head>
<link href="../favicon.png" rel="icon" type="image/png">
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <title>Inferencia Causal 2026 – emparejamiento</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-b653ffaf65bdc9afdd8d06ec44d675b9.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&amp;display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons@1.9.4/css/academicons.min.css">
  <script>
  /* kableExtra footnote: cuando la nota queda en la 1a celda con celdas vacías al lado (sin colspan),
     le damos colspan a la 1a celda y quitamos las vacías para que ocupe todo el ancho de la tabla */
  document.addEventListener('DOMContentLoaded', function () {
    document.querySelectorAll('tfoot tr').forEach(function (tr) {
      var tds = tr.querySelectorAll(':scope > td');
      if (tds.length > 1) {
        tds[0].setAttribute('colspan', tds.length);
        for (var i = tds.length - 1; i >= 1; i--) tds[i].remove();
      }
    });
  });
  </script>
  <style>
  /* Reglas del tema Inferencia Causal, movidas aquí desde la sección scss:rules de
     theme-ic.scss por un bug de Quarto 1.9.38 (su exportador de "css vars" falla ante
     cualquier tema revealjs con scss:rules). Este <style> se inserta después del <link>
     del tema, así que gana el cascade igual que antes. */
  /* ============ tokens ============ */
  :root{
    --main-font:"Inter", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
    --head-font:"Inter", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
    --code-font:"SFMono-Regular", Consolas, "Liberation Mono", monospace;
    --deep:#163D34; --deep-2:#12332A; --green:#2B7258; --green-700:#215546;
    --guinda:#9B2247; --paper:#F5F6F3; --ink:#16211D; --muted:#586761;
    --line:rgba(22,33,29,.12); --line-strong:rgba(22,33,29,.18);
    --rail:#EAF1ED; --code-ink:#E6EFE8;
  }

  .reveal{ font-family:var(--main-font); font-weight:400; color:var(--ink); }
  .reveal .slides{ text-align:left; }
  .reveal .slides section{ text-align:left; height:100%; }

  /* ============ encabezados de contenido (h2 = título de diapositiva) ============ */
  .reveal h1, .reveal h2, .reveal h3, .reveal h4{
    font-family:var(--head-font); font-weight:800; letter-spacing:-.02em; line-height:1.05; color:var(--deep);
    margin:0 0 .55em; text-transform:none; text-align:left;
  }
  /* barra guinda antes del título de diapositiva (h2 en decks con ##; h1 en decks sin ##) */
  .reveal section > h2:first-child,
  .reveal section:not(.portada):not(.divider):not(.final) > h1:first-child{
    position:relative; padding-left:.6em; margin-bottom:.7em;
  }
  .reveal section > h2:first-child::before,
  .reveal section:not(.portada):not(.divider):not(.final) > h1:first-child::before{
    content:""; position:absolute; left:0; top:.1em; bottom:.1em; width:.16em;
    background:var(--guinda); border-radius:3px;
  }
  /* h1 como título de contenido (decks que usan # para cada diapositiva) */
  .reveal section:not(.portada):not(.divider):not(.final) > h1:first-child{
    color:var(--deep); font-size:1.6em; line-height:1.05;
  }

  /* ============ cuerpo, viñetas ============ */
  .reveal p{ line-height:1.45; margin:0 0 .7em; }
  .reveal ul{ list-style:none !important; margin:0 0 .6em; padding:0; }  /* !important: quita el marcador nativo también en sublistas (reveal pone ■) */
  /* '>' (hijo directo): el punto verde SOLO va en los <li> de un <ul>,
     nunca en los de una lista numerada (<ol>) anidada bajo una viñeta */
  .reveal ul > li{ position:relative; padding-left:1.4em; margin:.5em 0; line-height:1.4; }
  .reveal ul > li::before{
    content:""; position:absolute; left:.05em; top:.62em; width:.42em; height:.42em;
    border-radius:50%; background:var(--green);
  }
  .reveal ul ul{ margin:.35em 0 .3em; }
  .reveal ul ul > li::before{ background:var(--muted); width:.34em; height:.34em; }
  /* listas numeradas anidadas bajo una viñeta: número sí, punto no */
  .reveal ul ol{ margin:.35em 0 .3em; }
  .reveal ol > li{ margin:.4em 0; line-height:1.4; }
  .reveal ol{ padding-left:1.2em; }
  .reveal li{ margin:.45em 0; }
  .reveal strong{ color:var(--deep); font-weight:700; }
  .reveal em{ color:var(--muted); }
  .reveal a{ color:var(--green); text-decoration:none; }
  .reveal a:hover{ color:var(--deep); }

  /* ============ columnas ============ */
  .reveal .columns{ display:flex; align-items:center; gap:1.4em; }

  /* ============ código (bloque verde vivo, letras claras) ============ */
  .reveal pre{ box-shadow:none; width:100%; margin:.4em 0 .9em; }
  .reveal div.sourceCode{
    background:var(--deep); border:1px solid rgba(255,255,255,.10);
    border-radius:10px; margin:.4em 0 .9em;
  }
  .reveal pre code{
    background:transparent; color:var(--code-ink); border-radius:10px; padding:.8em 1.1em;
    font-family:var(--code-font); font-size:.7em; line-height:1.55; max-height:none;
  }
  /* Fondos transparentes en pre y code para que se vea el verde del div.sourceCode, y
     texto base claro. Especificidad alta + !important porque quarto inyecta DESPUÉS sus
     defaults .reveal pre code{background-color:#fff;color:#222} y code.sourceCode > span. */
  .reveal div.sourceCode > pre,
  .reveal div.sourceCode pre.sourceCode{ background:transparent !important; }
  .reveal div.sourceCode pre code,
  .reveal div.sourceCode pre code.sourceCode{ background:transparent !important; color:var(--code-ink); }
  .reveal div.sourceCode pre code > span,
  .reveal div.sourceCode pre code.sourceCode > span{ color:var(--code-ink); }
  /* resaltado de sintaxis legible sobre el verde profundo (paleta de la marca) */
  .reveal .sourceCode span.co, .reveal .sourceCode span.do,
  .reveal .sourceCode span.cv, .reveal .sourceCode span.an,
  .reveal .sourceCode span.in{ color:#84A99A; font-style:italic; }              /* comentarios */
  .reveal .sourceCode span.st, .reveal .sourceCode span.ch,
  .reveal .sourceCode span.sc, .reveal .sourceCode span.vs,
  .reveal .sourceCode span.ss{ color:#EFC777; }                                 /* cadenas */
  .reveal .sourceCode span.kw, .reveal .sourceCode span.cf{ color:#F3A6BE; }    /* palabras clave */
  .reveal .sourceCode span.fu, .reveal .sourceCode span.im{ color:#8FE3C6; }    /* funciones */
  .reveal .sourceCode span.dv, .reveal .sourceCode span.fl,
  .reveal .sourceCode span.bn, .reveal .sourceCode span.cn{ color:#EEA9B8; }    /* números */
  .reveal .sourceCode span.dt, .reveal .sourceCode span.at,
  .reveal .sourceCode span.ot, .reveal .sourceCode span.va,
  .reveal .sourceCode span.op{ color:#C2E0D3; }                                 /* tipos / args / operadores */
  .reveal .sourceCode span.al, .reveal .sourceCode span.er,
  .reveal .sourceCode span.wa{ color:#FF9E9E; }                                 /* alertas / errores */

  .reveal code{ font-family:var(--code-font); color:var(--deep); }  /* código en línea sobre papel */
  /* salida / resultados de R: caja clara para contrastar con el bloque de código verde */
  .reveal .cell-output pre code{ background:#fff; color:var(--ink); border:1px solid var(--line); }

  /* ============ tablas ============ */
  .reveal table{ border-collapse:collapse; margin:.4em 0 .8em; font-size:.9em; background:#fff;
    border:1px solid var(--line); border-radius:10px; overflow:hidden; }
  .reveal table th{
    background:var(--guinda); color:#fff !important; text-align:center; font-weight:700;
    text-transform:uppercase; letter-spacing:.06em; font-size:.78em; padding:.5em .8em; border:none;
  }
  /* el contenido de las celdas de encabezado oscuras (incluido MathJax, que trae su propio color)
     también en blanco */
  .reveal table th *{ color:#fff !important; }
  .reveal table th svg, .reveal table th svg *{ fill:#fff !important; }
  /* título de tabla (add_header_above con background="white") → fondo blanco, texto negro.
     Se empata por la presencia del estilo inline background-color (solo lo trae ese título;
     las celdas guinda reciben su color por CSS, no inline). Sin ':' dentro de la cadena para
     no romper el analizador de css-vars de Quarto. */
  .reveal table th[style*="background-color"],
  .reveal table th[style*="background-color"] *{
    color:#141414 !important;
  }
  .reveal table td{ padding:.5em .8em; border-top:1px solid var(--line); text-align:center;
    font-variant-numeric:tabular-nums; }
  .reveal table tr:nth-child(even) td{ background:#FBFCFB; }
  /* kableExtra scroll_box: una altura en % no resuelve dentro de una diapositiva reveal (no hay
     padre con altura fija) → forzamos una altura máx. fija para que la tabla haga scroll y quepa */
  .reveal div[style*="overflow-y"]{
    height:auto !important; max-height:560px !important;
  }
  /* Encabezado fijo al hacer scroll dentro de un scroll_box. kableExtra ya marca cada th como
     sticky, pero dos cosas lo anulaban: el border-collapse:collapse de arriba (Chrome ignora
     sticky en celdas de tablas colapsadas) y el overflow:hidden de la tabla (la convertía en el
     ancestro de scroll, en vez del recuadro). Aquí se revierten ambos solo para estas tablas y
     el sticky se aplica al thead completo, para que las dos filas de encabezado —el título de
     add_header_above y los nombres de columna— se queden juntas y sin encimarse. */
  .reveal div[style*="overflow-y"] table{
    border-collapse:separate !important; border-spacing:0 !important; overflow:visible !important;
  }
  .reveal div[style*="overflow-y"] thead{ position:sticky; top:0; z-index:3; }
  .reveal div[style*="overflow-y"] thead th{ position:static !important; }
  /* kableExtra footnote: a veces no aplica colspan y la nota queda en la 1a columna con celdas
     vacías al lado → la hacemos ocupar todo el ancho de la tabla */
  /* kableExtra a veces no le pone colspan a la nota → un script en _ic-header.html se lo pone
     y quita las celdas vacías; aquí solo la alineamos a la izquierda */
  .reveal tfoot td{ text-align:left !important; }

  /* ============ ecuaciones ============ */
  .reveal .MathJax, .reveal mjx-container{ color:var(--deep); }

  /* ============ callout / idea clave (Quarto callouts o .idea) ============ */
  .reveal .idea{
    background:rgba(155,34,71,.07); border:1px solid rgba(155,34,71,.18);
    border-left:.28em solid var(--guinda); border-radius:0 14px 14px 0; padding:.9em 1.1em;
  }
  .reveal .idea .idea-l{ font-size:.6em; font-weight:800; letter-spacing:.12em; text-transform:uppercase;
    color:var(--guinda); display:block; margin-bottom:.4em; }
  .reveal .idea .idea-big{ font-size:1.2em; font-weight:800; letter-spacing:-.02em; color:var(--deep);
    line-height:1.15; margin:0; }

  /* ============ frase / cita (.phrase): quote centrada en cursiva + fuente abajo-derecha ============ */
  .reveal .phrase{
    position:relative;
    background:rgba(155,34,71,.06); border:1px solid rgba(155,34,71,.18);
    border-left:.28em solid var(--guinda); border-radius:0 14px 14px 0;
    padding:1.1em 1.7em 1em;
  }
  .reveal .phrase::before{                 /* comilla decorativa sutil, esquina superior izq. */
    content:"\201C"; position:absolute; top:.06em; left:.32em; pointer-events:none;
    font-family:Georgia,"Times New Roman",serif; font-size:2.4em; line-height:1; color:var(--guinda); opacity:.25;
  }
  .reveal .phrase p{
    text-align:center; font-style:italic; font-size:1.18em; color:var(--deep); line-height:1.45; margin:0 0 .45em;
  }
  .reveal .phrase p:last-child{ margin-bottom:0; }
  .reveal .phrase .cite{                   /* la fuente/cita: abajo a la derecha, sin cursiva */
    display:block; text-align:right; font-style:normal; font-weight:600;
    font-size:.72em; color:var(--muted); letter-spacing:.02em; margin-top:.8em;
  }

  /* ============ cromo: footer, número de diapositiva, logo ============ */
  .reveal .footer{
    text-align:left !important; left:3.2% !important; right:auto !important; bottom:2.6%; width:auto !important;
    color:var(--muted); font-size:.5em; font-weight:600; letter-spacing:.03em;
  }
  .reveal .footer p, .reveal .footer > *{ margin:0; text-align:left !important; }
  .reveal .slide-number{
    background:transparent; color:var(--muted); font-family:var(--main-font); font-weight:700;
    font-size:.5em; top:auto !important; bottom:2.6% !important; right:3.2% !important; left:auto;
    font-variant-numeric:tabular-nums; letter-spacing:.04em;
  }
  /* logo CIDE — teja blanca arriba a la derecha en todas las diapositivas */
  .reveal .slide-logo{
    position:fixed; top:3.4%; right:3%; bottom:auto; max-height:none;
    height:5.6%; width:auto; aspect-ratio:1; background:#fff; border-radius:8px; padding:.35%;
    box-shadow:0 1px 4px rgba(0,0,0,.18); object-fit:contain; z-index:40;
  }
  /* ocultar footer y número en portada / divisores / final (data-state="nochrome" → clase en <body>) */
  body.nochrome .footer, body.nochrome .slide-number{ display:none !important; }

  /* ============ PORTADA (verde profundo) ============ */
  .reveal section.portada{
    display:flex !important; flex-direction:column; justify-content:center; align-items:flex-start;
    height:100%; padding:0 8%; text-align:left;
  }
  .reveal section.portada h1{
    color:#fff; font-size:4em; line-height:1.02; margin:0; padding:0; letter-spacing:-.03em;
  }
  .reveal section.portada h1::after{
    content:""; display:block; width:1.9em; height:.16em; background:var(--guinda);
    border-radius:3px; margin:.7em 0 1em;
  }
  .reveal section.portada .pa-eyebrow{
    order:-1; font-size:1.15em; font-weight:600; color:#9FD3BB; letter-spacing:.01em; margin-bottom:.85em;
  }
  .reveal section.portada .pa-name{ font-weight:600; color:#fff; font-size:1.35em; }
  .reveal section.portada .pa-icons{ margin-left:.5em; }
  .reveal section.portada .pa-icons a{ color:#E78AA1; margin:0 .2em; font-size:1.35em; }
  .reveal section.portada .pa-icons a:hover{ color:#fff; }
  .reveal section.portada .pa-inst{
    margin-top:1.3em; color:#9FD3BB; font-size:.92em; font-weight:600; letter-spacing:.14em; text-transform:uppercase; line-height:1.75;
  }

  /* ============ DIVISOR DE SECCIÓN (fondo guinda) — marcar el # con {.divider} ============ */
  .reveal section.divider{
    display:flex !important; flex-direction:column; justify-content:center; align-items:flex-start;
    height:100%; padding:0 8%;
  }
  .reveal section.divider > h1{ color:#fff; font-size:3.2em; line-height:1.02; margin:0; }

  /* ============ SLIDE FINAL (créditos, fondo guinda) ============ */
  .reveal section.final{
    display:flex !important; flex-direction:column; justify-content:center; align-items:flex-start;
    height:100%; padding:0 8%; color:#fff;
  }
  .reveal section.final .f-eyebrow{ order:-1; font-size:.86em; font-weight:600; color:#F4C6D2; margin:0 0 .9em; }
  .reveal section.final h1, .reveal section.final h2{ color:#fff; font-size:2.4em; margin:0; padding:0; }
  .reveal section.final h1::before, .reveal section.final h2::before{ display:none; }
  .reveal section.final h1{ font-weight:800; letter-spacing:-.02em; }
  .reveal section.final .f-inst{ font-size:.82em; font-weight:600; letter-spacing:.05em; color:#F1D6DE; margin:.5em 0 0; }
  .reveal section.final .f-inst a{ color:inherit; border-bottom:1px solid rgba(255,255,255,.4); text-decoration:none; }
  .reveal section.final .f-inst a:hover{ border-bottom-color:#fff; }
  .reveal section.final .f-icons{ margin-top:1em; font-size:1.4em; }
  .reveal section.final .f-icons a{ color:#fff; margin:0 .22em; }
  .reveal section.final .f-rule{ width:2.4em; height:.12em; background:rgba(255,255,255,.7); border-radius:2px; margin:1.1em 0; }
  .reveal section.final .f-copy{ font-size:.56em; color:#EAC5CF; margin:0; max-width:40em; line-height:1.5; }
  .reveal section.final .f-copy strong{ color:#fff; }

  /* ============ fragmentos ============ */
  .reveal .fragment{ text-align:left; }
  </style>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">


<section id="emparejamiento" class="title-slide slide level1 portada center" data-background-color="#163D34" data-state="nochrome">
<h1>Emparejamiento</h1>
<div class="pa-eyebrow">
<p>Inferencia Causal</p>
</div>
<p><span class="pa-name">Irvin Rojas</span> <span class="pa-icons"><a href="https://github.com/rojasirvin" target="_blank" aria-label="GitHub"><i class="bi bi-github"></i></a> <a href="https://scholar.google.com/citations?hl=es&amp;user=FUwdSTMAAAAJ&amp;view_op=list_works&amp;sortby=pubdate" target="_blank" aria-label="Google Scholar"><i class="bi bi-mortarboard-fill"></i></a> <a href="mailto:irvin.rojas@cide.edu" aria-label="Correo"><i class="bi bi-envelope-fill"></i></a></span></p>
<div class="pa-inst">
<p>Centro de Investigación y Docencia Económicas<br>Maestría en Economía</p>
</div>
<div class="cell">
<style type="text/css">
.huge .remark-code { /*Change made here*/
  font-size: 200% !important;
}
.tiny .remark-code { /*Change made here*/
  font-size: 60% !important;
}
</style>
</div>
</section>

<section id="emparejamiento-1" class="title-slide slide level1 divider center" data-background-color="#9B2247" data-state="nochrome">
<h1>Emparejamiento</h1>

</section>

<section>
<section id="estas-primeras-secciones-estaban-en-regresión" class="title-slide slide level1 center">
<h1>Estas primeras secciones estaban en regresión</h1>

</section>
<section id="supuesto-de-independencia-condicional" class="slide level2">
<h2>Supuesto de independencia condicional</h2>
<ul>
<li>El <strong>supuesto de independencia condicional</strong> significa que, condicional en una serie de características <span class="math inline">\(X_i\)</span>, el sesgo de selección desaparece:</li>
</ul>
<p><span class="math display">\[\{y_{0i},y_{1i}\}\perp D_i | X_i\]</span></p>
<div class="fragment">
<ul>
<li>Supongamos que <span class="math inline">\(D_i\)</span> es ir o no a la universidad y la variable de interés es el ingreso</li>
<li>Sabemos que la comparación observacional nos da:</li>
</ul>
<p><span class="math display">\[
\begin{aligned}
E(y_i|D_i=1)-E(y_i|D_i=0)=&amp;\overbrace{ E(y_{1i}-y_{0i}|D_i=1)}^{\text{Efecto promedio en los tratados}}+\\&amp; \underbrace{E(y_{0i}|D_i=1)-E(y_{oi}|D_i=0)}_{\text{Sesgo de selección}}
\end{aligned}
\]</span></p>
<ul>
<li>Es posible que aquellos que no fueron a la universidad de todos modos hubieran tenido un mayor salario, por lo que el sesgo de selección es positivo</li>
</ul>
</div>
</section>
<section id="supuesto-de-independencia-condicional-1" class="slide level2">
<h2>Supuesto de independencia condicional</h2>
<ul>
<li><p>El SIC implica que si hacemos la comparación condicional en <span class="math inline">\(X_i\)</span>, el sesgo desaparece <span class="math display">\[
\begin{aligned}
E(y_i|X_i,D_i=1)-E(y_i|X_i,D_i=0)=E(y_{1i}-y_{0i}|X_i)
\end{aligned}
\]</span></p></li>
<li><p>Es decir, que si comparamos a personas con y sin tratamiento, con los <span class="math inline">\(X_i\)</span> <em>fijos</em>, el sesgo de selección desaparece</p></li>
<li><p><em>Mantener fijas</em> las <span class="math inline">\(X\)</span> es el análogo a obtener el promedio del salario en cada nivel de escolaridad en la gráfica de la FEC descrita anteriormente</p></li>
</ul>
</section>
<section id="supuesto-de-independencia-condicional-2" class="slide level2">
<h2>Supuesto de independencia condicional</h2>
<ul>
<li><p>Para generalizar el concepto cuando la variable tiene más de dos valores (como con la educación <span class="math inline">\(s_i\)</span>), escribamos <span class="math inline">\(Y_{si}\equiv f_i(s)\)</span></p></li>
<li><p>Esta función nos dice cuál sería el ingreso de <span class="math inline">\(i\)</span> bajo todos los posibles niveles de <span class="math inline">\(s\)</span></p></li>
<li><p>En este caso, asumimos el SIC, que se traduce en: <span class="math display">\[Y_{si}\perp s_i | X_i\]</span></p></li>
<li><p>En diseños experimentales, el SIC surge porque el tratamiento se asigna de forma aleatoria</p></li>
<li><p>Pero con datos <em>observacionales</em>, el SIC significa que <span class="math inline">\(s_i\)</span> es <em>casi como si fuera asignado de manera aleatoria</em> cuando condicionamos en <span class="math inline">\(X_i\)</span></p></li>
</ul>
</section>
<section id="supuesto-de-independencia-condicional-3" class="slide level2">
<h2>Supuesto de independencia condicional</h2>
<ul>
<li>En los datos solo observamos <span class="math inline">\(Y_i=f_i(s_i)\)</span></li>
<li>Dado el SIC, podemos hacer comparaciones de ingreso promedio para distintos niveles de educación: <span class="math display">\[E(Y_i|X_i,s_i=s)-E(Y_i|X_i,s_i=s-1)=E(f_i(s)-f_i(s-1)|X_i)\]</span></li>
</ul>
<div class="fragment">
<ul>
<li>Notemos que lo impráctico de esto es que tendríamos que hacer comparaciones en pares y luego tratar de hacer un promedio ponderado por el número de individuos en cada nivel de educación</li>
</ul>
</div>
</section>
<section id="regresión-para-hacer-las-comparasiones" class="slide level2">
<h2>Regresión para hacer las comparasiones</h2>
<ul>
<li>Supongamos una función causal para el ingreso <span class="math display">\[f_i(s)=\alpha+\rho s+\nu_i\]</span></li>
</ul>
<p>que indica lo que un individuo ganaría para todo valor de <span class="math inline">\(s\)</span> (y no solo el valor realizado <span class="math inline">\(s_i\)</span>)</p>
<ul>
<li><p>La única parte aleatoria es el error con media cero <span class="math inline">\(\nu_i\)</span>, que captura los factores no observados que afectan los ingresos</p></li>
<li><p>Sustituyendo el valor observado:</p></li>
</ul>
<p><span class="math display">\[Y_i=\alpha+\rho s_i+\nu_i\]</span></p>
<ul>
<li><span class="math inline">\(s_i\)</span> puede estar correlacionado con los resultados potenciales <span class="math inline">\(f_i(s)\)</span>, es decir, correlacionado con el error <span class="math inline">\(\nu_i\)</span></li>
</ul>
</section>
<section id="regresión-para-hacer-las-comparasiones-1" class="slide level2">
<h2>Regresión para hacer las comparasiones</h2>
<ul>
<li><p>Supongamos que el SIC se cumple dado un vector <span class="math inline">\(X_i\)</span></p></li>
<li><p>Descompongamos el error en una función lineal de las características <span class="math inline">\(X_i\)</span> y un error <span class="math inline">\(u_i\)</span>: <span class="math display">\[\nu_i=X_i'\gamma+u_i\]</span></p></li>
</ul>
<p>donde se asume que <span class="math inline">\(E(\nu_i|X_i)=X_i'\gamma\)</span> y donde <span class="math inline">\(u_i\)</span> y <span class="math inline">\(X_i\)</span> no están correlacionados</p>
<ul>
<li>Si se cumple el SIC, entonces:</li>
</ul>
<p><span class="math display">\[
\begin{aligned}
E(f_i(s)|X_i,s_i)=E(f_i(s)|X_i)&amp;=\alpha+\rho s+E(\nu_i|X_i) \\
&amp;=\alpha+\rho s + X_i'\gamma
\end{aligned}
\]</span></p>
<ul>
<li><p>Es decir, en el modelo de regresión causal <span class="math inline">\(Y_i=\alpha+\rho s_i+ X_i'\gamma+u_i\)</span>, <span class="math inline">\(u_i\)</span> no está correlacionado con los regresores <span class="math inline">\(X_i\)</span> y <span class="math inline">\(s_i\)</span></p></li>
<li><p><span class="math inline">\(\rho\)</span> es el efecto causal de interés</p></li>
<li><p>El supuesto clave es que la única razón por la cual <span class="math inline">\(\nu_i\)</span> y <span class="math inline">\(s_i\)</span> están correlacionados es <span class="math inline">\(X_i\)</span></p></li>
</ul>
</section></section>
<section>
<section id="fin-de-lo-traído-desde-regresión" class="title-slide slide level1 center">
<h1>Fin de lo traído desde regresión</h1>

</section>
<section id="sesgo-de-selección" class="slide level2">
<h2>Sesgo de selección</h2>
<p>Las razones que determinan la asignación del tratamiento pueden también determinar el valor de <span class="math inline">\(Y\)</span>. Entonces, una comparación observacional nos da el efecto del tratamiento más el sesgo de selección:</p>
<p><span class="math display">\[
\begin{aligned}
E(y_i|D_i=1)-E(y_i|D_i=0)=&amp;\overbrace{ E(y_{1i}|D_i=1)-E(y_{0i}|D_i=1)}^{\text{Efecto promedio en los tratados}}+\\&amp; \underbrace{E(y_{0i}|D_i=1)-E(y_{oi}|D_i=0)}_{\text{Sesgo de selección}}
\end{aligned}
\]</span></p>
<p>Una forma de eliminar el sesgo de selección es mediante la asignación aleatoria del tratamiento; sin embargo, esto no siempre es posible por lo que recurrimos a supuestos para eliminar el sesgo de selección.</p>
</section>
<section id="supuesto-de-independencia" class="slide level2">
<h2>Supuesto de independencia</h2>
<p>El <em>supuesto de independencia</em> condicional dice que al <em>controlar</em> por una serie de características <span class="math inline">\(X_i\)</span>, el tratamiento es <em>como</em> si fuera aleatorio:</p>
<p><span class="math display">\[
E(Y(1)|D=1,X)=E(Y(1)|D=0,X)
\]</span></p>
<p><span class="math display">\[
E(Y(0)|D=1,X)=E(Y(0)|D=0,X)
\]</span></p>
<p>Esto es, los valores esperados de <span class="math inline">\(Y(1)\)</span> y <span class="math inline">\(Y(0)\)</span> son iguales cuando nos fijamos en cada valor de <span class="math inline">\(X\)</span>.</p>
</section></section>
<section>
<section id="matching-exacto" class="title-slide slide level1 divider center" data-background-color="#9B2247" data-state="nochrome">
<h1>Matching exacto</h1>

</section>
<section id="matching-exacto-1" class="slide level2">
<h2>Matching exacto</h2>
<p>Un estimador de matching exacto consiste en <em>emparejar</em> individuos tratados y no tratados para cada valor específico de las <span class="math inline">\(X\)</span> y luego tomar el promedio ponderado de las diferencias.</p>
<p>Tenemos datos observacionales de individuos que recibieron y no recibieron un tratamiento y tenemos una serie de características discretizadas en <span class="math inline">\(X_i\)</span>.</p>
<p>Asumimos que controlando por las características <span class="math inline">\(X_i\)</span> podemos obtener diferencias causales y luego hacemos un promedio de dichas diferencias.</p>
</section>
<section id="ejemplo-programa-hipotético-de-empleo" class="slide level2">
<h2>Ejemplo: programa hipotético de empleo</h2>
<p>Usemos <a href="https://mixtape.scunning.com/matching-and-subclassification.html?panelset=r-code">el ejemplo</a> de MT (The Mixtape):</p>
</section>
<section id="ejemplo-programa-hipotético-de-empleo-1" class="slide level2">
<h2>Ejemplo: programa hipotético de empleo</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>Los individuos tratados:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   unit_treat age_treat earnings_treat
        &lt;dbl&gt;     &lt;dbl&gt;          &lt;dbl&gt;
 1          1        18           9500
 2          2        29          12250
 3          3        24          11000
 4          4        27          11750
 5          5        33          13250
 6          6        22          10500
 7          7        19           9750
 8          8        20          10000
 9          9        21          10250
10         10        30          12500</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>Mientras que los no tratados:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 3
   unit_control age_control earnings_control
          &lt;dbl&gt;       &lt;dbl&gt;            &lt;dbl&gt;
 1            1          20             8500
 2            2          27            10075
 3            3          21             8725
 4            4          39            12775
 5            5          38            12550
 6            6          29            10525
 7            7          39            12775
 8            8          33            11425
 9            9          24             9400
10           10          30            10750
11           11          33            11425
12           12          36            12100
13           13          22             8950
14           14          18             8050
15           15          43            13675
16           16          39            12775
17           17          19             8275
18           18          30             9000
19           19          51            15475
20           20          48            14800</code></pre>
</div>
</div>
</div></div>
</section>
<section id="comparación-observacional" class="slide level2">
<h2>Comparación observacional</h2>
<p>Si hiciéramos diferencias simples obtendríamos:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-label="1"></a><span class="fu">mean</span>(data.treat<span class="sc">$</span>earnings_treat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11075</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-label="1"></a><span class="fu">mean</span>(data.control<span class="sc">$</span>earnings_control)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11101.25</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a aria-label="1"></a><span class="co">#Diferencia</span></span>
<span id="cb7-2"><a aria-label="2"></a><span class="fu">mean</span>(data.treat<span class="sc">$</span>earnings_treat)<span class="sc">-</span> <span class="fu">mean</span>(data.control<span class="sc">$</span>earnings_control)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -26.25</code></pre>
</div>
</div>
<p>Parece que en el grupo de control ganan más (efecto de tratamiento negativo).</p>
<p>El principal problema con esta diferencia es que sabemos que los ingresos crecen con la edad. Pero notemos que la muestra de no tratados tiene mayor edad promedio:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a aria-label="1"></a><span class="fu">mean</span>(data.treat<span class="sc">$</span>age_treat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a aria-label="1"></a><span class="fu">mean</span>(data.control<span class="sc">$</span>age_control)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 31.95</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a aria-label="1"></a><span class="co">#Diferencia</span></span>
<span id="cb13-2"><a aria-label="2"></a><span class="fu">mean</span>(data.treat<span class="sc">$</span>age_treat)<span class="sc">-</span> <span class="fu">mean</span>(data.control<span class="sc">$</span>age_control)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -7.65</code></pre>
</div>
</div>
<p>Es decir, estaríamos <em>confundiendo</em> el efecto de la edad.</p>
</section>
<section id="muestra-emparejada" class="slide level2">
<h2>Muestra emparejada</h2>
<p>Construyamos la muestra apareada: para cada individuo en el grupo tratado, buscaremos uno en el de control que tenga la misma edad. Cuando le encontramos un individuo no tratado al tratado con la misma edad decimos que esa pareja hizo <em>match</em>.</p>
<p>Por ejemplo, la primera unidad tratada, con 18 años y un ingreso de 9500 estaría emparejada con la unidad 14 del grupo de control, que tiene también 18 años y un ingreso de 8050.</p>
<p>Para dicho individuo de 18 años, su ingreso contrafactual sería 8050.</p>
<p>Cuando hay varias unidades en el grupo de control que pueden ser empatadas con la de tratamiento, podemos construir el ingreso contrafactual calculando el promedio.</p>
<p>Del grupo de control, los individuos 10 y 18 tienen 30 años, con ingresos 10750 y 9000, por lo que usamos el promedio (9875) para crear el contrafactual del individuo tratado de 30 años de la fila 10.</p>
</section>
<section id="muestra-emparejada-1" class="slide level2">
<h2>Muestra emparejada</h2>
<p>La muestra emparejada o contrafactual será:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   unit_matched age_matched earnings_matched
          &lt;dbl&gt;       &lt;dbl&gt;            &lt;dbl&gt;
 1            1          18             8050
 2            2          29            10525
 3            3          24             9400
 4            4          27            10075
 5            5          33            11425
 6            6          22             8950
 7            7          19             8275
 8            8          20             8500
 9            9          21             8725
10           10          30             9875</code></pre>
</div>
</div>
</section>
<section id="muestra-emparejada-2" class="slide level2">
<h2>Muestra emparejada</h2>
<p>Noten que la edad es la misma entre los tratados y la muestra apareada:</p>
<div class="columns">
<div class="column" style="width:50%;">
<p>Muestra de tratados:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a aria-label="1"></a><span class="fu">mean</span>(data.treat<span class="sc">$</span>age_treat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24.3</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>Muestra emparejada:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a aria-label="1"></a><span class="fu">mean</span>(data.matched<span class="sc">$</span>age_matched)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24.3</code></pre>
</div>
</div>
</div></div>
<p>En este caso, decimos que la edad <em>está balanceada</em>.</p>
<p>Y entonces podemos calcular el efecto de tratamiento como la diferencia de ingresos entre los tratados y los no tratados en la muestra emparejada:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1695</code></pre>
</div>
</div>
<p>En este caso, encontramos un efecto positivo del programa de 1695 unidades monetarias.</p>
</section>
<section id="estimador-de-matching-exacto" class="slide level2">
<h2>Estimador de matching exacto</h2>
<p>Lo anterior nos permite definir el <strong>estimador de matching exacto del TOT</strong> como:</p>
<p><span class="math display">\[\hat{\delta}_{TOT}=\frac{1}{N_T}\sum_{D_i=1}\left(Y_i-\left(\frac{1}{M}\sum_{m=1}^{M}Y_{jm(i)}\right)\right)\]</span></p>
</section>
<section id="importancia-del-soporte-común" class="slide level2">
<h2>Importancia del soporte común</h2>
<p>Observemos lo que ocurre con la distribución de edades en ambos grupos:</p>
<div class="columns">
<div class="column" style="width:50%;">
<p>Para los tratados:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="figures/grafica_tratados-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>Mientras que para los no tratados:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="figures/grafica_notratados-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</div></div>
<p>El supuesto de traslape débil para identificar el TOT significa que para cada unidad tratada, hay al menos un no tratado. De otra forma, no podemos hacer la comparación.</p>
</section>
<section id="estimador-de-matching-exacto-1" class="slide level2">
<h2>Estimador de matching exacto</h2>
<ul>
<li><p>Hasta aquí, solo hemos imputado el contrafactual para cada unidad en el grupo tratado</p></li>
<li><p>Si podemos imputar también, para cada unidad no tratada, su correspondiente contrafactual tratado, podemos estimar el ATE</p></li>
<li><p>Y un <strong>estimador de matching exacto del ATE</strong> sería:</p></li>
</ul>
<p><span class="math display">\[\hat{\delta}_{ATE}=\frac{1}{N}\sum_{i}^N(2D_i-1)\left(Y_i-\left(\frac{1}{M}\sum_{m=1}^{M}Y_{jm(i)}\right)\right)\]</span></p>
</section>
<section id="ejemplo-de-la-vida-real" class="slide level2">
<h2>Ejemplo de la vida real</h2>
<ul>
<li><p>Tenemos varias características en <span class="math inline">\(X_i\)</span>, no solo la edad</p></li>
<li><p>Esto hace que cada valor <span class="math inline">\(X_i=x_i\)</span> este representado por una <em>celda</em></p></li>
<li><p><span class="math inline">\(X_i\)</span> incluye, por ejemplo, raza, año de solicitud de ingreso al programa, escolaridad, calificación en examen de aptitud, año de nacimiento (son las características del ejemplo que vermeos más adelante)</p></li>
<li><p>Estas características definen <em>celdas</em> y dentro de cada celda tenemos tratados y no tratados</p></li>
</ul>
</section>
<section id="efecto-del-tratamiento-con-matching-exacto" class="slide level2">
<h2>Efecto del tratamiento con matching exacto</h2>
<ul>
<li>El TOT asumiendo inconfundibilidad:</li>
</ul>
<p><span class="math display">\[
\begin{aligned}
\delta^M=TOT&amp;=E\left\{ E(y_{1i}|X_i,D_i=1)-E(y_{0i}|X_i,D_i=0)|D_i=1\right\} \\
&amp;=E\left\{\delta_X | D_i=1\right\}
\end{aligned}
\]</span></p>
<ul>
<li><p><span class="math inline">\(\delta_X\)</span> es la diferencia de ingresos promedio entre estados de tratamiento para cada valor de <span class="math inline">\(X_i\)</span></p></li>
<li><p>Con <span class="math inline">\(X_i\)</span> discreta y con una muestra disponible:</p></li>
</ul>
<p><span class="math display">\[
\delta^M=\sum_{x} \delta_x P(X_i=x|D_i=1)
\]</span></p>
</section>
<section id="ejemplo-veteranos-de-guerra-en-estados-unidos" class="slide level2">
<h2>Ejemplo: veteranos de guerra en Estados Unidos</h2>
<ul>
<li><p><a href="https://www.jstor.org/stable/2998558">Angrist (1998)</a>, Estimating the Labor Market Impact of Voluntary Military Service Using Social Security Data on Military Applicants</p></li>
<li><p>El tratamiento es haber servido en el ejercito, algo que claramente tiene autoselección</p></li>
<li><p>Se trata de estimar el efecto en el ingreso</p></li>
<li><p>Los autores construyen celdas de acuerdo a las características antes mencionadas</p>
<ul>
<li>Raza, año de solicitud de ingreso al programa, escolaridad, calificación en examen de aptitud, año de nacimiento</li>
</ul></li>
</ul>
</section>
<section id="ejemplo-veteranos-de-guerra-en-estados-unidos-1" class="slide level2">
<h2>Ejemplo: veteranos de guerra en Estados Unidos</h2>
<ul>
<li><p>Efectos estimados usando distintas metodologías</p></li>
<li><p>Los impactos estimados usando el matching exacto se encuentran bajo la columna <em>Controlled contrast</em></p></li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="ExactMatching_effects_table_a.jpg"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="ExactMatching_effects_table_b.jpg"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="ejemplo-veteranos-de-guerra-en-estados-unidos-2" class="slide level2">
<h2>Ejemplo: veteranos de guerra en Estados Unidos</h2>
<ul>
<li><p>Noten que la columna (2) muestra lo que se hubiera concluido si solo se comparan diferencias de medias</p></li>
<li><p>Antes de 1980, las diferencias eran muy pequeñas (cero en términos prácticos)</p></li>
<li><p>En esta aplicación esta comparación llevaría a conclusiones incorrectas</p></li>
<li><p>Además, las diferencias para no-blancos y blancos son distintas</p></li>
<li><p>Hay un pico en los efectos alrededor de 1982</p></li>
<li><p>En esta aplicación, los resultados por <em>matching</em> y regresión son muy parecidos hasta 1984</p></li>
<li><p>La conclusión es que existe evidencia de efectos negativos en los ingresos por haber servido en el ejército en los blancos y efectos positivos para los individuos de otras razas</p></li>
</ul>
</section>
<section id="ejemplo-veteranos-de-guerra-en-estados-unidos-3" class="slide level2">
<h2>Ejemplo: veteranos de guerra en Estados Unidos</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>Para personas identificadas como blancas:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="ExactMatching_effects_graph_a.jpg"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>Para personas identificadas como no blancas:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="ExactMatching_effects_graph_b.jpg"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section></section>
<section>
<section id="propensity-score-matching" class="title-slide slide level1 divider center" data-background-color="#9B2247" data-state="nochrome">
<h1>Propensity Score Matching</h1>

</section>
<section id="métodos-de-apareamiento-o-matching" class="slide level2">
<h2>Métodos de apareamiento o <em>matching</em></h2>
<ul>
<li><p>Los métodos apareamiento o <em>matching</em> recaen en el <strong>supuesto de independencia condicional</strong></p></li>
<li><p>Al <em>controlar</em> por una serie de características <span class="math inline">\(X_i\)</span>, el tratamiento es <em>como</em> si fuera aleatorio</p></li>
<li><p>Podemos escribir</p></li>
</ul>
<p><span class="math display">\[
E(Y(1)|D=1,X)=E(Y(1)|D=0,X)
\]</span></p>
<p><span class="math display">\[
E(Y(0)|D=1,X)=E(Y(0)|D=0,X)
\]</span></p>
<ul>
<li>Esto es, los valores esperados de <span class="math inline">\(Y(1)\)</span> y <span class="math inline">\(Y(0)\)</span> son iguales cuando nos fijamos en cada valor de <span class="math inline">\(X\)</span></li>
</ul>
</section>
<section id="supuestos-de-identificación-del-tot" class="slide level2">
<h2>Supuestos de identificación del TOT</h2>
<p><strong>Supuesto 1. Inconfundibilidad</strong></p>
<p><span class="math display">\[
Y(0), Y(1) \perp  D|X
\]</span></p>
<ul>
<li><p>Dado un conjunto de variables <span class="math inline">\(X\)</span>, los resultados potenciales son independientes del tratamiento</p></li>
<li><p><span class="math inline">\(X\)</span> debe incluir todas las variables que determinan el tratamiento y los resultados potenciales</p></li>
</ul>
<p><strong>Supuesto 2: Traslape</strong></p>
<p><span class="math display">\[
0&lt; P(D=1|X) &lt; 1
\]</span></p>
<ul>
<li><p><span class="math inline">\(X\)</span> no predice <span class="math inline">\(D\)</span> perfectamente</p></li>
<li><p>Personas con el mismo <span class="math inline">\(X\)</span> tienen probabilidad positiva de ser tratados y no tratados</p></li>
</ul>
</section>
<section id="supuestos-de-identificación-del-tot-1" class="slide level2">
<h2>Supuestos de identificación del TOT</h2>
<ul>
<li><p>Cuando se cumple <strong>Supuesto 1</strong> <span class="math inline">\(+\)</span> <strong>Supuesto 2</strong> se conoce como <strong>ignorabilidad fuerte</strong></p></li>
<li><p>Heckman (1998) muestra que estás condiciones son demasiado estrictas</p></li>
<li><p>Para identificar el <span class="math inline">\(TOT\)</span> es suficiente:</p></li>
<li><p><strong>Supuesto 1a. Inconfundibilidad en el control</strong></p></li>
</ul>
<p><span class="math display">\[
Y(0) \perp  D | X
\]</span></p>
<ul>
<li><strong>Supuesto 2a. Traslape débil</strong></li>
</ul>
<p><span class="math display">\[
P(D=1|X) &lt; 1
\]</span></p>
</section>
<section id="matching-exacto-es-impráctico" class="slide level2">
<h2>Matching exacto es impráctico</h2>
<ul>
<li><p>En la práctica es difícil manejar problemas en espacios de múltiples dimensiones: <strong>maldición de la dimensionalidad</strong></p></li>
<li><p>El problema de la maldición de la dimensionalidad se exacerba con el tamaño limitado de las bases de datos</p></li>
<li><p>Si <span class="math inline">\(X\)</span> tuviera solo indicadores binarios, el número de posibles combinaciones sería <span class="math inline">\(2^s\)</span></p></li>
<li><p>Por ejemplo, si solo tuviéramos <span class="math inline">\(X_1=\{\text{menor de 35 años}, \text{con 35 años o más}\}\)</span>, <span class="math inline">\(X_2=\{\text{más que preparatoria}, \text{menos que preparatoria}\}\)</span>, <span class="math inline">\(X_3=\{\text{indígena}, \text{no indígena}\}\)</span>, tendríamos que hacer ocho comparaciones:</p>
<ul>
<li>menor de 35 años, más que preparatoria, indígena</li>
<li>menor de 35 años, más que preparatoria, no indígena</li>
<li>…</li>
<li>con 35 años o más, menos que preparatoria, no indígena</li>
</ul></li>
<li><p>Pero Si <span class="math inline">\(X\)</span> incluye muchas variables, algunas tomando muchos valores, esto se vuelve imposible de realizar</p></li>
</ul>
</section>
<section id="maldición-de-la-dimensionalidad" class="slide level2">
<h2>Maldición de la dimensionalidad</h2>
<ul>
<li><p>El requerimiento de soporte común significa que debemos tener tratados y no tratados para cada valor de <span class="math inline">\(X_i\)</span> para hacer comparaciónes</p></li>
<li><p>Cuando <span class="math inline">\(X_i\)</span> tiene muchas dimensiones, resulta un problema de <em>escasez</em> o <em>sparseness</em></p></li>
<li><p>Algunas celdas estarán vacías, o solo tendrán tratados, o solo tendrán no tratados</p></li>
<li><p>Si tenemos unidades en todas las celdas de control, <strong>aún podemos estimar el TOT</strong></p>
<ul>
<li><p>Noten que cuando completamos la fase pareada en el ejemplo hipotético, siempre encontramos a alguien en el grupo de control para asignárselo a un tratado</p></li>
<li><p>Pero al revés, no siempre es posible: por ejemplo, no hay ningún tratado de 48 años</p></li>
</ul></li>
</ul>
</section>
<section id="teorema-del-ps-rosenbaum-y-rubin-1983" class="slide level2">
<h2>Teorema del PS (Rosenbaum y Rubin, 1983)</h2>
<ul>
<li><p><strong>Corolario 1. Inconfundibilidad dado el propensity score</strong></p></li>
<li><p>El <strong>Supuesto 1</strong> implica:</p></li>
</ul>
<p><span class="math display">\[
Y(0), Y(1) \perp  D|P(X)
\]</span></p>
<p>donde <span class="math inline">\(P(X)=P(D=1|X)\)</span> es la probabilidad de ser tratado dado un conjunto de covariables <span class="math inline">\(X\)</span>, el <em>propensity score</em> o PS</p>
</section>
<section id="efecto-del-tratamiento" class="slide level2">
<h2>Efecto del tratamiento</h2>
<ul>
<li>El efecto del tratamiento, bajo el supuesto de inconfundibilidad dado el propensity score, es:</li>
</ul>
<p><span class="math display">\[
TOT^{PSM}=E_{P(X)|D=1} \left(E(Y(1)|D=1, P(X))-E(Y(0)|D=0,P(X)) \right)
\]</span></p>
<ul>
<li>El <span class="math inline">\(TOT\)</span> es la diferencia en la variable de resultados de los tratados y los no tratados pesada por la distribución del PS en los tratados</li>
</ul>
</section>
<section id="estimación" class="slide level2">
<h2>Estimación</h2>
<ul>
<li><p>Debemos por tanto primero calcular el PS</p></li>
<li><p>Se empatan o se hace match de unidades que fueron tratadas con unidades que no lo fueron usando el PS</p></li>
<li><p>Se mide la diferencia en la variable de resultados entre estos grupos</p></li>
<li><p>Se hace un promedio ponderado de las diferencias</p></li>
</ul>
</section>
<section id="implementación" class="slide level2">
<h2>Implementación</h2>
<ol type="1">
<li><p>Estimación del PS</p></li>
<li><p>Escoger el algoritmo de matching</p></li>
<li><p>Comprobar la calidad del matching</p></li>
<li><p>Estimar el <span class="math inline">\(TOT\)</span></p></li>
</ol>
</section>
<section id="especificar-el-modelo-del-ps" class="slide level2">
<h2>Especificar el modelo del PS</h2>
<ul>
<li><p>Se usa un modelo <em>probit</em> o <em>logit</em></p>
<ul>
<li><p><strong>Prueba y error</strong>. Maximizar la tasa clasificación de tratamientos y controles usando <span class="math inline">\(\bar{P}\)</span>, la proporción de tratamientos en la muestra</p></li>
<li><p><strong>Significancia estadística</strong>. Usar solo las variables estadísticamente significativas, comenzando con un modelo muy básico</p></li>
<li><p><strong>Validación cruzada</strong>. Comenzar con un modelo simple y agregar grupos de variables comparando las que reduzcan el error cuadrático promedio</p></li>
</ul></li>
<li><p>El propósito del PS es sobre todo generar balance de las variables en <span class="math inline">\(X\)</span></p></li>
</ul>
</section></section>
<section>
<section id="algoritmos-de-matching" class="title-slide slide level1 divider center" data-background-color="#9B2247" data-state="nochrome">
<h1>Algoritmos de matching</h1>

</section>
<section id="vecino-más-cercano" class="slide level2">
<h2>Vecino más cercano</h2>
<ul>
<li><p>A cada individuo del grupo tratado se le asigna uno del grupo de comparación en términos del PS</p></li>
<li><p>Puede hacerse con remplazo o sin remplazo</p></li>
<li><p>Puede emplearse también sobremuestreo (<em>oversampling</em>), es decir, asignar más de un individuo del grupo de comparación</p></li>
<li><p>Por ejemplo, NN 5 significa que a cada individuo tratado se le asignan los cinco individuos del grupo no tratado con los PS estimados más cercanos</p></li>
</ul>
</section>
<section id="vecino-más-cercano-1" class="slide level2">
<h2>Vecino más cercano</h2>
<div class="columns">
<div class="column" style="width:50%;">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Tratados</th>
<th style="text-align: center;"><span class="math inline">\(\hat{p}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">a</td>
<td style="text-align: center;">0.031</td>
</tr>
<tr class="even">
<td style="text-align: center;">b</td>
<td style="text-align: center;">0.042</td>
</tr>
<tr class="odd">
<td style="text-align: center;">c</td>
<td style="text-align: center;">0.07</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:50%;">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">No tratados</th>
<th style="text-align: center;"><span class="math inline">\(\hat{p}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">0.034</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">0.068</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">0.21</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
</tr>
</tbody>
</table>
</div></div>
<ul>
<li><p>Con vecino más cercano, el individuo <span class="math inline">\(a\)</span> tratado estaría emparejado con el <span class="math inline">\(A\)</span> no tratado</p></li>
<li><p>Si el emparejamiento es con reemplazo, <span class="math inline">\(A\)</span> podría ser usado otra vez y <span class="math inline">\(b\)</span> también sería emparejado con <span class="math inline">\(A\)</span></p></li>
<li><p>Pero si el emparejamiento es sin reemplazo, <span class="math inline">\(A\)</span> ya no puede ser usado y a <span class="math inline">\(b\)</span> se le emparejaría con <span class="math inline">\(B\)</span></p></li>
<li><p>Cuando hacemos el pareamiento sin reemplazo, debemos tener una muestra lo suficientemente grande</p></li>
<li><p>El pareamiento sin reemplazo depende del orden en que se realice el procedimiento</p></li>
</ul>
</section>
<section id="caliper-y-radio" class="slide level2">
<h2>Caliper y radio</h2>
<ul>
<li><p>El método de vecino más cercano puede generar malos emparejamientos si el vecino más cercano está muy lejos en términos del PS</p></li>
<li><p>Especificar un <em>caliper</em> consiste en definir una vecindad aceptable de matching (el caliper) y elegir solo el vecino más cercano dentro del caliper</p></li>
<li><p>Con las funciones de R que usaremos más adelante, el <em>radio</em> consiste en definir cuántos individuos deberán ser apareados dado que están dentro del caliper</p></li>
</ul>
</section>
<section id="caliper" class="slide level2">
<h2>Caliper</h2>
<div class="columns">
<div class="column" style="width:50%;">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Tratados</th>
<th style="text-align: center;"><span class="math inline">\(\hat{p}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">a</td>
<td style="text-align: center;">0.031</td>
</tr>
<tr class="even">
<td style="text-align: center;">b</td>
<td style="text-align: center;">0.042</td>
</tr>
<tr class="odd">
<td style="text-align: center;">c</td>
<td style="text-align: center;">0.07</td>
</tr>
<tr class="even">
<td style="text-align: center;">d</td>
<td style="text-align: center;">0.11</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:50%;">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">No tratados</th>
<th style="text-align: center;"><span class="math inline">\(\hat{p}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">0.034</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">0.068</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">0.21</td>
</tr>
<tr class="even">
<td style="text-align: center;">D</td>
<td style="text-align: center;">0.40</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
</tr>
</tbody>
</table>
</div></div>
<ul>
<li><p>El primer paso es fijar el caliper, por ejemplo, de 0.1</p></li>
<li><p>El caliper implica buscar al vecino más cercano dentro de una vecindad de 0.1</p></li>
<li><p>En este ejemplo <span class="math inline">\(c\)</span> podría ser solo emparejado con <span class="math inline">\(B\)</span> si <span class="math inline">\(B\)</span> aún está disponible (porque no ha sido emparejado con nadie o porque, aunque haya sido emparejado, el procedimiento se hace con reemplazo)</p></li>
</ul>
</section>
<section id="caliper-con-sobremuestreo" class="slide level2">
<h2>Caliper con sobremuestreo</h2>
<div class="columns">
<div class="column" style="width:50%;">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Tratados</th>
<th style="text-align: center;"><span class="math inline">\(\hat{p}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">d</td>
<td style="text-align: center;">0.31</td>
</tr>
<tr class="even">
<td style="text-align: center;">e</td>
<td style="text-align: center;">0.39</td>
</tr>
<tr class="odd">
<td style="text-align: center;">f</td>
<td style="text-align: center;">0.44</td>
</tr>
<tr class="even">
<td style="text-align: center;">g</td>
<td style="text-align: center;">0.52</td>
</tr>
<tr class="odd">
<td style="text-align: center;">h</td>
<td style="text-align: center;">0.55</td>
</tr>
<tr class="even">
<td style="text-align: center;">i</td>
<td style="text-align: center;">0.62</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:50%;">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">No tratados</th>
<th style="text-align: center;"><span class="math inline">\(\hat{p}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">R</td>
<td style="text-align: center;">0.27</td>
</tr>
<tr class="even">
<td style="text-align: center;">S</td>
<td style="text-align: center;">0.29</td>
</tr>
<tr class="odd">
<td style="text-align: center;">T</td>
<td style="text-align: center;">0.33</td>
</tr>
<tr class="even">
<td style="text-align: center;">U</td>
<td style="text-align: center;">0.49</td>
</tr>
<tr class="odd">
<td style="text-align: center;">V</td>
<td style="text-align: center;">0.57</td>
</tr>
<tr class="even">
<td style="text-align: center;">W</td>
<td style="text-align: center;">0.61</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
</tr>
</tbody>
</table>
</div></div>
<ul>
<li><p>Si el caliper se realiza con sobremuestreo, con un caliper de 0.10 y 2 vecinos a <span class="math inline">\(g\)</span> se le asignarían <span class="math inline">\(U\)</span> y <span class="math inline">\(V\)</span> (si estuvieran disponibles)</p></li>
<li><p>Es decir, dentro del caliper, los dos individuos con el PS más cercano</p></li>
</ul>
</section>
<section id="radio" class="slide level2">
<h2>Radio</h2>
<div class="columns">
<div class="column" style="width:50%;">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Tratados</th>
<th style="text-align: center;"><span class="math inline">\(\hat{p}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">d</td>
<td style="text-align: center;">0.31</td>
</tr>
<tr class="even">
<td style="text-align: center;">e</td>
<td style="text-align: center;">0.39</td>
</tr>
<tr class="odd">
<td style="text-align: center;">f</td>
<td style="text-align: center;">0.44</td>
</tr>
<tr class="even">
<td style="text-align: center;">g</td>
<td style="text-align: center;">0.52</td>
</tr>
<tr class="odd">
<td style="text-align: center;">h</td>
<td style="text-align: center;">0.55</td>
</tr>
<tr class="even">
<td style="text-align: center;">i</td>
<td style="text-align: center;">0.62</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:50%;">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">No tratados</th>
<th style="text-align: center;"><span class="math inline">\(\hat{p}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">R</td>
<td style="text-align: center;">0.27</td>
</tr>
<tr class="even">
<td style="text-align: center;">S</td>
<td style="text-align: center;">0.29</td>
</tr>
<tr class="odd">
<td style="text-align: center;">T</td>
<td style="text-align: center;">0.33</td>
</tr>
<tr class="even">
<td style="text-align: center;">U</td>
<td style="text-align: center;">0.49</td>
</tr>
<tr class="odd">
<td style="text-align: center;">V</td>
<td style="text-align: center;">0.57</td>
</tr>
<tr class="even">
<td style="text-align: center;">W</td>
<td style="text-align: center;">0.61</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
</tr>
</tbody>
</table>
</div></div>
<ul>
<li><p>Pero si ahora implementamos radio con un caliper de 0.10, a <span class="math inline">\(g\)</span> se le asignarían <span class="math inline">\(U\)</span>, <span class="math inline">\(V\)</span> y <span class="math inline">\(W\)</span> (si estuvieran disponibles)</p></li>
<li><p>Es decir, todos los individuos dentro del caliper</p></li>
</ul>
</section>
<section id="estratificación" class="slide level2">
<h2>Estratificación</h2>
<ul>
<li><p>Partir la región de soporte común en bloques de acuerdo al PS</p></li>
<li><p>Estimar el efecto de tratamiento dentro de cada bloque</p></li>
<li><p>No hay una regla sobre cuántos estratos usar. Se aconsajan generalmente cinco</p></li>
<li><p>Dentro de cada estrato debe haber balance de los covariables</p></li>
</ul>
</section>
<section id="kernel-y-métodos-no-paramétricos" class="slide level2">
<h2>Kernel y métodos no paramétricos</h2>
<ul>
<li><p>Los métodos anteriores escogen solo unas cuantas unidades del grupo de comparación</p></li>
<li><p>Podemos escoger usar muchas o incluso todas las observaciones del grupo de comparación y pesarlas apropiadamente</p></li>
<li><p>Se reduce la varianza pues usamos más información, pero se sacrifica precisión pues se usan observaciones potencialmente muy distantes</p></li>
<li><p>Se le otorga más peso a las observaciones más cercanas y menos a las más distantes</p></li>
</ul>
</section>
<section id="kernel" class="slide level2">
<h2>Kernel</h2>
<div class="columns">
<div class="column" style="width:50%;">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Tratados</th>
<th style="text-align: center;"><span class="math inline">\(\hat{p}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">d</td>
<td style="text-align: center;">0.31</td>
</tr>
<tr class="even">
<td style="text-align: center;">e</td>
<td style="text-align: center;">0.39</td>
</tr>
<tr class="odd">
<td style="text-align: center;">f</td>
<td style="text-align: center;">0.44</td>
</tr>
<tr class="even">
<td style="text-align: center;">g</td>
<td style="text-align: center;">0.52</td>
</tr>
<tr class="odd">
<td style="text-align: center;">h</td>
<td style="text-align: center;">0.55</td>
</tr>
<tr class="even">
<td style="text-align: center;">i</td>
<td style="text-align: center;">0.62</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:50%;">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">No tratados</th>
<th style="text-align: center;"><span class="math inline">\(\hat{p}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">R</td>
<td style="text-align: center;">0.27</td>
</tr>
<tr class="even">
<td style="text-align: center;">S</td>
<td style="text-align: center;">0.29</td>
</tr>
<tr class="odd">
<td style="text-align: center;">T</td>
<td style="text-align: center;">0.33</td>
</tr>
<tr class="even">
<td style="text-align: center;">U</td>
<td style="text-align: center;">0.49</td>
</tr>
<tr class="odd">
<td style="text-align: center;">V</td>
<td style="text-align: center;">0.57</td>
</tr>
<tr class="even">
<td style="text-align: center;">W</td>
<td style="text-align: center;">0.61</td>
</tr>
</tbody>
</table>
</div></div>
<ul>
<li><p>Supongamos que estos son todos nuestros datos</p></li>
<li><p>Con un emparejamiento por kernel, a <span class="math inline">\(d\)</span> lo compararemos con todos los individuos, desde <span class="math inline">\(R\)</span> hasta <span class="math inline">\(W\)</span></p></li>
<li><p>La función kernel le dará más peso a <span class="math inline">\(R\)</span>, un poco menos a <span class="math inline">\(S\)</span> y así hasta darle muy poco o casi nada de peso a <span class="math inline">\(W\)</span></p></li>
</ul>
</section>
<section id="qué-método-usar" class="slide level2">
<h2>¿Qué método usar?</h2>
<ul>
<li><p>No hay un método claramente superior a todos los demás</p></li>
<li><p>Más aún, el desempeño de cada método depende de cada aplicación</p></li>
<li><p>La ruta más seguida es usar varios algoritmos y mostrar la robustez de los resultados a esta elección</p></li>
</ul>
</section>
<section id="comprobar-empíricamente-los-supuestos" class="slide level2">
<h2>Comprobar empíricamente los supuestos</h2>
<ul>
<li><p>El parámetro <span class="math inline">\(TOT\)</span> solo se calcula sobre la región de sporte común por lo que se debe verificar el traslape del PS calculado para los tratados y no tratados</p></li>
<li><p>Otro de los teoremas de Rosenbaum y Rubin (1983) implica que</p></li>
</ul>
<p><span class="math display">\[
X \perp  D|P(X)
\]</span></p>
<ul>
<li><p>Esto es, que al controlar por el PS, las variables <span class="math inline">\(X\)</span> no deben proveer información sobre <span class="math inline">\(D\)</span></p></li>
<li><p>Se recomienda también hacer una prueba de estratificación</p>
<ol type="1">
<li><p>Dividir el rango del soporte común en bloques</p></li>
<li><p>Hacer una prueba de medias del PS entre grupos dentro de cada bloque</p></li>
<li><p>Hacer una prueba de medias de cada variable en <span class="math inline">\(X_i\)</span> entre grupos dentro de cada bloque</p></li>
</ol></li>
</ul>
</section>
<section id="ilustración-del-soporte-común" class="slide level2">
<h2>Ilustración del soporte común</h2>

<img data-src="Gertler_PSOverlap.png" width="218" class="r-stretch"></section></section>
<section>
<section id="ejemplo-en-r" class="title-slide slide level1 divider center" data-background-color="#9B2247" data-state="nochrome">
<h1>Ejemplo en R</h1>

</section>
<section id="paquetes" class="slide level2">
<h2>Paquetes</h2>
<p>Usaremos dos paquetes nuevos: <em>MatchIt</em> y <em>cobalt</em>, que pueden descargar como cualquier otro paquete desde CRAN.</p>
</section>
<section id="datos-no-experimentales-de-una-muestra-de-mujeres" class="slide level2">
<h2>Datos no experimentales de una muestra de mujeres</h2>
<p>Los datos en <a href="cattaneo_smoking.csv">cattaneo_smoking.csv</a> (Cattaneo, 2010) son de una muestra de mujeres que incluye un indicador de si la madre fumó durante el embarazo. El propósito es evaluar el efecto de fumar sobre el peso de los bebés al nacer. Se incluyen una serie de covariables que usaremos para modelar el <em>propensity score</em>.</p>
</section>
<section id="matchit-para-realizar-los-emparejamientos" class="slide level2">
<h2><em>matchit</em> para realizar los emparejamientos</h2>
<p>La función que usaremos para hacer los emparejamientos es <em>matchit</em> de la librería <em>MatchIt</em>. Antes de hacer los emparejamientos, construimos la dummy de tratamiento, <strong>smoke</strong>, una dummy para mujeres casadas, <strong>married</strong>, y una dummy para si el caso en cuestión es el primer bebé, <strong>firstbaby</strong>:</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 4642 Columns: 24
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): mmarried, msmoke, mbsmoke, fbaby, prenatal1
dbl (19): bweight, mhisp, fhisp, foreign, alcohol, deadkids, mage, medu, fag...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</section>
<section id="comparación-observacional-1" class="slide level2">
<h2>Comparación observacional</h2>
<p>Notemos que, si solo comparamos a las mujeres que fuman con las que no fuman, estamos comparando personas muy diferentes:</p>
<div class="cell">
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_k4cvfx0wguld8hfb9y23 = TinyTable.createTableFunctions("tinytable_k4cvfx0wguld8hfb9y23");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '-1', j: 3 }, { i: '-1', j: 5 } ], css_id: 'tinytable_css_4tbnwr5y4kyrk2iwttum',}, 
          { positions: [ { i: '7', j: 2 }, { i: '7', j: 3 }, { i: '7', j: 4 }, { i: '7', j: 5 }, { i: '7', j: 6 }, { i: '7', j: 7 } ], css_id: 'tinytable_css_2m3zho09ey6pv57wfapv',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '4', j: 4 }, { i: '5', j: 4 }, { i: '6', j: 4 }, { i: '1', j: 5 }, { i: '2', j: 5 }, { i: '3', j: 5 }, { i: '4', j: 5 }, { i: '5', j: 5 }, { i: '6', j: 5 }, { i: '1', j: 6 }, { i: '2', j: 6 }, { i: '3', j: 6 }, { i: '4', j: 6 }, { i: '5', j: 6 }, { i: '6', j: 6 }, { i: '1', j: 7 }, { i: '2', j: 7 }, { i: '3', j: 7 }, { i: '4', j: 7 }, { i: '5', j: 7 }, { i: '6', j: 7 } ], css_id: 'tinytable_css_emlwgm1hdw0vjmuei6po',}, 
          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 }, { i: '0', j: 7 } ], css_id: 'tinytable_css_i112rfu89fnf0bktih9h',}, 
          { positions: [ { i: '-1', j: 2 }, { i: '-1', j: 4 } ], css_id: 'tinytable_css_9u9ryo3s78a83dxqz378',}, 
          { positions: [ { i: '7', j: 1 } ], css_id: 'tinytable_css_fpzy64i0uix32lp7bnfu',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 } ], css_id: 'tinytable_css_n9ovfft0tpbdiwmj7yyz',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_3n1b0zyrf8t0z0rcdgya',}, 
          { positions: [ { i: '-1', j: 1 }, { i: '-1', j: 6 }, { i: '-1', j: 7 } ], css_id: 'tinytable_css_i11sk95z4prjh1d3o3fi',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_k4cvfx0wguld8hfb9y23.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_4tbnwr5y4kyrk2iwttum, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_4tbnwr5y4kyrk2iwttum {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: black; --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.03em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 3%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_2m3zho09ey6pv57wfapv, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_2m3zho09ey6pv57wfapv {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: right }
    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_emlwgm1hdw0vjmuei6po, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_emlwgm1hdw0vjmuei6po { text-align: right }
    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_i112rfu89fnf0bktih9h, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_i112rfu89fnf0bktih9h {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: right }
    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_9u9ryo3s78a83dxqz378, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_9u9ryo3s78a83dxqz378 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: black; --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.03em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 3%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_fpzy64i0uix32lp7bnfu, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_fpzy64i0uix32lp7bnfu {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_n9ovfft0tpbdiwmj7yyz, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_n9ovfft0tpbdiwmj7yyz { text-align: left }
    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_3n1b0zyrf8t0z0rcdgya, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_3n1b0zyrf8t0z0rcdgya {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_i11sk95z4prjh1d3o3fi, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_i11sk95z4prjh1d3o3fi {  position: relative; --border-bottom: 0; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_k4cvfx0wguld8hfb9y23" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        <caption>Pruebas de balance</caption>
        <thead>
<tr>
<th scope="col" align="center" colspan="1" data-row="-1" data-col="1"> </th>
<th scope="col" align="center" colspan="2" data-row="-1" data-col="2">0</th>
<th scope="col" align="center" colspan="2" data-row="-1" data-col="4">1</th>
<th scope="col" align="center" colspan="1" data-row="-1" data-col="6"> </th>
<th scope="col" align="center" colspan="1" data-row="-1" data-col="7"> </th>
</tr>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">Mean</th>
                <th scope="col" data-row="0" data-col="3">Std. Dev.</th>
                <th scope="col" data-row="0" data-col="4">Mean</th>
                <th scope="col" data-row="0" data-col="5">Std. Dev.</th>
                <th scope="col" data-row="0" data-col="6">Diff. in Means</th>
                <th scope="col" data-row="0" data-col="7">p</th>
              </tr>
        </thead>
        <tfoot><tr><td colspan="7">Fuente: Cattaneo (2009)</td></tr></tfoot>
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">married</td>
                  <td data-row="1" data-col="2">0.75</td>
                  <td data-row="1" data-col="3">0.43</td>
                  <td data-row="1" data-col="4">0.47</td>
                  <td data-row="1" data-col="5">0.50</td>
                  <td data-row="1" data-col="6">-0.28</td>
                  <td data-row="1" data-col="7">0.00</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1">firstbaby</td>
                  <td data-row="2" data-col="2">0.45</td>
                  <td data-row="2" data-col="3">0.50</td>
                  <td data-row="2" data-col="4">0.37</td>
                  <td data-row="2" data-col="5">0.48</td>
                  <td data-row="2" data-col="6">-0.08</td>
                  <td data-row="2" data-col="7">0.00</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">medu</td>
                  <td data-row="3" data-col="2">12.93</td>
                  <td data-row="3" data-col="3">2.53</td>
                  <td data-row="3" data-col="4">11.64</td>
                  <td data-row="3" data-col="5">2.17</td>
                  <td data-row="3" data-col="6">-1.29</td>
                  <td data-row="3" data-col="7">0.00</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1">nprenatal</td>
                  <td data-row="4" data-col="2">10.96</td>
                  <td data-row="4" data-col="3">3.52</td>
                  <td data-row="4" data-col="4">9.86</td>
                  <td data-row="4" data-col="5">4.21</td>
                  <td data-row="4" data-col="6">-1.10</td>
                  <td data-row="4" data-col="7">0.00</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">foreign</td>
                  <td data-row="5" data-col="2">0.06</td>
                  <td data-row="5" data-col="3">0.24</td>
                  <td data-row="5" data-col="4">0.03</td>
                  <td data-row="5" data-col="5">0.16</td>
                  <td data-row="5" data-col="6">-0.03</td>
                  <td data-row="5" data-col="7">0.00</td>
                </tr>
                <tr>
                  <td data-row="6" data-col="1">mhisp</td>
                  <td data-row="6" data-col="2">0.04</td>
                  <td data-row="6" data-col="3">0.19</td>
                  <td data-row="6" data-col="4">0.02</td>
                  <td data-row="6" data-col="5">0.15</td>
                  <td data-row="6" data-col="6">-0.01</td>
                  <td data-row="6" data-col="7">0.05</td>
                </tr>
                <tr>
                  <td data-row="7" data-col="1">fage</td>
                  <td data-row="7" data-col="2">27.84</td>
                  <td data-row="7" data-col="3">8.79</td>
                  <td data-row="7" data-col="4">24.74</td>
                  <td data-row="7" data-col="5">11.15</td>
                  <td data-row="7" data-col="6">-3.10</td>
                  <td data-row="7" data-col="7">0.00</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
</section>
<section id="estimación-del-ps" class="slide level2">
<h2>Estimación del PS</h2>
<p>Una manera de hacer más eficiente el uso de las <em>fórmulas</em> es usando <em>as.formula</em>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>smoke ~ married + firstbaby + medu + nprenatal + foreign + mhisp + 
    fage</code></pre>
</div>
</div>
<p>Usamos <em>matchit</em> para estimar el PS y realizar los emparejamientos con el algoritmo que indiquemos:</p>
</section>
<section id="estimación-del-ps-1" class="slide level2">
<h2>Estimación del PS</h2>
<p>El resumen del procedimiento da bastante información sobre el pareamiento:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
matchit(formula = ps, data = data.smoking, method = "nearest", 
    distance = "logit", replace = FALSE, ratio = 1)

Summary of Balance for All Data:
          Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean
distance         0.2568        0.1700          0.6673     1.4475    0.2002
married          0.4734        0.7515         -0.5569          .    0.2781
firstbaby        0.3715        0.4531         -0.1689          .    0.0816
medu            11.6389       12.9299         -0.5955     0.7316    0.0717
nprenatal        9.8623       10.9629         -0.2616     1.4301    0.0376
foreign          0.0255        0.0598         -0.2181          .    0.0344
mhisp            0.0243        0.0363         -0.0776          .    0.0120
fage            24.7431       27.8444         -0.2782     1.6070    0.0468
          eCDF Max
distance    0.3329
married     0.2781
firstbaby   0.0816
medu        0.2549
nprenatal   0.1259
foreign     0.0344
mhisp       0.0120
fage        0.1377

Summary of Balance for Matched Data:
          Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean
distance         0.2568        0.2564          0.0033     1.0110    0.0005
married          0.4734        0.4769         -0.0070          .    0.0035
firstbaby        0.3715        0.3981         -0.0551          .    0.0266
medu            11.6389       11.6019          0.0171     0.7064    0.0161
nprenatal        9.8623        9.8588          0.0008     1.1543    0.0059
foreign          0.0255        0.0174          0.0514          .    0.0081
mhisp            0.0243        0.0231          0.0075          .    0.0012
fage            24.7431       24.5799          0.0146     1.0787    0.0124
          eCDF Max Std. Pair Dist.
distance    0.0093          0.0046
married     0.0035          0.2202
firstbaby   0.0266          0.4575
medu        0.0417          0.5168
nprenatal   0.0185          0.7039
foreign     0.0081          0.2425
mhisp       0.0012          0.2781
fage        0.0556          0.6457

Sample Sizes:
          Control Treated
All          3778     864
Matched       864     864
Unmatched    2914       0
Discarded       0       0</code></pre>
</div>
</div>
</section>
<section id="verificación-del-balance" class="slide level2">
<h2>Verificación del balance</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>Gráfico de nube:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="figures/unnamed-chunk-21-1.png" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>To identify the units, use first mouse button; to stop, use second.</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>Histograma:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="figures/unnamed-chunk-22-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="muestra-emparejada-3" class="slide level2">
<h2>Muestra emparejada</h2>
<p>Podemos guardar un objeto con la muestra emparejada usando <em>match.data</em> y observar quién hace match con quién:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   [,1]  
11 "4130"
20 "2234"
25 "1740"
43 "2857"
47 "305" 
49 "1442"</code></pre>
</div>
</div>
</section>
<section id="muestra-emparejada-4" class="slide level2">
<h2>Muestra emparejada</h2>
<p>Una propuesta para determinar si el emparejamiento fue exitoso es observar las diferencias promedio estandarizadas (SMD) entre los grupos tratados y no tratados, antes y después del emparejamiento.</p>
<p><span class="math display">\[SMD_X=\frac{\bar{X}_T-\bar{X}_{NT}}{\sqrt{S^2_T+S^2_{NT}}}\]</span></p>
<p>También vale la pena no perder de vista la razón de varianzas (VR). Se espera que este ratio no sea muy distinto de 1 después de hacer el emparejamiento:</p>
<p><span class="math display">\[VR=\frac{S^2_T}{S^2_{NT}}\]</span></p>
<p>Como regla de dedo, una diferencia de 0.1 o menos en el SMD se considera un buen balance. Por ejemplo, la escolaridad de la madre tenía un SDM de -0.5955 en la muestra en bruto, pero con el emparejamiento el SDM se vuelve de solo 0.0171.</p>
</section>
<section id="loveplot" class="slide level2">
<h2><em>Loveplot</em></h2>
<p>Usando la librería <em>cobalt</em> podemos construir un <em>love plot</em> que representa gráficamente las diferencias antes y después del emparejamiento</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning in love.plot(bal.tab(m.out), threshold = 0.1): Standardized mean differences and raw mean differences are present in the same
plot. Use the `stars` argument to distinguish between them and appropriately
label the x-axis. See `love.plot()` for details.</code></pre>
</div>

</div>
<img data-src="figures/unnamed-chunk-24-1.png" width="672" class="r-stretch"></section>
<section id="efecto-de-tratamiento" class="slide level2">
<h2>Efecto de tratamiento</h2>
<p>Existen muchas maneras de explotar la muestra emparejada. Aquí veremos la más sencilla. Simplemente consideremos a la muestra emparejada como si viniera de un experimento. Sin embargo, debemos poner especial atención a la forma de hacer inferencia pues no debemos ignorar que el PS es estimado.</p>
<p>Dependiendo de si el emparejamiento ocurre con o sin reemplazo, y de la naturaleza de la variable dependiente, se recomiendan distintas maneras de estimar el efecto del tratamiento y hacer inferencia. Una buena guía está en la documentación de <a href="https://kosukeimai.github.io/MatchIt/articles/estimating-effects.html">MatchIt</a>.</p>
<p>Por ejemplo, cuando se realiza el emparejamiento sin reemplazo, <a href="https://www.tandfonline.com/doi/full/10.1080/01621459.2020.1840383?casa_token=7VdQFPydVtIAAAAA%3A3VRshT4TmqjnyzS2Nz2EBmFi54NlHDIWdtD-mDdAdPHuv51BhbXh1qYOwsRo8yH_WhA1UoUbvP0Kqg">Abadie &amp; Spiess (2019)</a> muestran que podemos estimar los errores estándar simplemente agrupando a nivel de pareja (o grupo) emparejado (<strong>subclass</strong> es una columna que enumera a las parejas o grupos emparejados y es construida automáticamente por <em>matchit</em>).</p>
</section>
<section id="efecto-de-tratamiento-1" class="slide level2">
<h2>Efecto de tratamiento</h2>
<p>Usando una regresión con la muestra emparejada</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

            Estimate Std. Error  t value  Pr(&gt;|t|)    
(Intercept) 3331.983     21.342 156.1200 &lt; 2.2e-16 ***
smoke       -194.323     28.111  -6.9128 6.664e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="efecto-de-tratamiento-2" class="slide level2">
<h2>Efecto de tratamiento</h2>
<p>Algunos autores incluyen los covariables en su estimación:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

               Estimate  Std. Error t value  Pr(&gt;|t|)    
(Intercept) 2983.514088   76.563235 38.9680 &lt; 2.2e-16 ***
smoke       -195.980548   27.934606 -7.0157 3.279e-12 ***
married      114.170671   30.707023  3.7181 0.0002072 ***
firstbaby    -60.979001   30.195581 -2.0195 0.0435935 *  
medu           0.076364    5.385295  0.0142 0.9886879    
nprenatal     32.235062    4.493034  7.1745 1.075e-12 ***
foreign       25.827549  109.279251  0.2363 0.8131935    
mhisp        111.852277   85.200388  1.3128 0.1894208    
fage          -0.139045    1.429538 -0.0973 0.9225265    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Cuando el emparejamiento es con reemplazo, las unidades no tratadas son emparejadas varias veces (aparecen repetidas en la muestra emparejada), lo cual debe ser considerado para estimar los efectos del tratamiento y hacer inferencia. Por ejemplo, se puede usar <em>bootstrap</em> para obtener el error estándar del efecto del tratamiento cuando la variable de impacto es continua.</p>
</section>
<section id="recomendaciones-prácticas" class="slide level2">
<h2>Recomendaciones prácticas</h2>
<ul>
<li><p>Las características <span class="math inline">\(X\)</span> que determinan la probabilidad de tratamiento deben ser observables</p></li>
<li><p>Las variables usadas para calcular el PS no deben haber sido afectadas por el tratamiento</p></li>
<li><p>Idealmente usamos variables <span class="math inline">\(X\)</span> pre-intervención</p></li>
<li><p>Cuando no hay <span class="math inline">\(X\)</span> pre-intervención, a veces se puede obtener el PS con variables post-intervención siempre y cuando estas no hayan sido afectadas por el tratamiento (pocas veces recomendado)</p></li>
<li><p>Se recomienda ampliamente ver:</p>
<ul>
<li>Caliendo, M., &amp; Kopeinig, S. (2008). Some practical guidance for the implementation of propensity score matching. <em>Journal of Economic Surveys</em>, 22(1), 31-72.</li>
</ul></li>
</ul>
</section>
<section id="conclusión" class="slide level2">
<h2>Conclusión</h2>
<ul>
<li><p>Las técnicas de PSM dependen de varios supuestos teoricos fuertes</p></li>
<li><p>La implementación implica que las variables en <span class="math inline">\(X\)</span> son aquellas que permiten hacer los supuestos de inconfundibilidad dado el PS</p></li>
<li><p>En la estimación del PS se toma la decisión sobre la forma funcional</p></li>
<li><p>Los efectos de tratamiento pueden ser distintos entre diferentes algoritmos de emparejamiento y la especificación del PS</p></li>
<li><p>La crítica más importante es que la mayoría de las veces nos preocupa más la autoselección basada en no observables que en observables</p></li>
<li><p>Pero muchas veces es todo lo que tenemos a la mano</p></li>
<li><p>Hay que hacer análisis de sensibilidad a las distintas decisiones</p></li>
<li><p>Presentar resultados transparentes</p></li>
</ul>
</section></section>
<section id="emparejamiento-2" class="title-slide slide level1 final center" data-background-color="#9B2247" data-state="nochrome">
<h1>Emparejamiento</h1>
<div class="f-eyebrow">
<p>Inferencia Causal</p>
</div>
<div class="f-inst">
<p><a href="https://rojasirvin.github.io/">Irvin Rojas</a></p>
</div>
<div class="f-inst">
<p>CIDE · Maestría en Economía</p>
</div>
<p><span class="f-icons"><a href="https://github.com/rojasirvin" target="_blank" aria-label="GitHub"><i class="bi bi-github"></i></a> <a href="https://scholar.google.com/citations?hl=es&amp;user=FUwdSTMAAAAJ&amp;view_op=list_works&amp;sortby=pubdate" target="_blank" aria-label="Google Scholar"><i class="bi bi-mortarboard-fill"></i></a> <a href="mailto:irvin.rojas@cide.edu" aria-label="Correo"><i class="bi bi-envelope-fill"></i></a></span></p>
<div class="f-rule">

</div>
<div class="f-copy">
<p>© 2026 Irvin Rojas. Distribuido bajo licencia Creative Commons <strong>CC BY-NC-SA 4.0</strong>. Los materiales de terceros citados conservan sus propios derechos.</p>
</div>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="logo-CIDE.jpg" class="slide-logo"></p>
<div class="footer footer-default">
<p>Inferencia Causal · Emparejamiento</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/rojasirvin\.github\.io\/inferencia-causal\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>