<!DOCTYPE html>
<html lang="en"><head>
<link href="../favicon.png" rel="icon" type="image/png">
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.19">

  <title>Inferencia Causal 2026 – seleccion-observables</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-b653ffaf65bdc9afdd8d06ec44d675b9.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&amp;display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons@1.9.4/css/academicons.min.css">
  <script>
  /* kableExtra footnote: cuando la nota queda en la 1a celda con celdas vacías al lado (sin colspan),
     le damos colspan a la 1a celda y quitamos las vacías para que ocupe todo el ancho de la tabla */
  document.addEventListener('DOMContentLoaded', function () {
    document.querySelectorAll('tfoot tr').forEach(function (tr) {
      var tds = tr.querySelectorAll(':scope > td');
      if (tds.length > 1) {
        tds[0].setAttribute('colspan', tds.length);
        for (var i = tds.length - 1; i >= 1; i--) tds[i].remove();
      }
    });
  });
  /* Notas al pie: Quarto las pasa al pie de cada lámina y reinicia la numeración en 1, aunque
     conserva el consecutivo en el id (fn1, fn2, ...). Reponemos ese consecutivo en la lista y en
     las llamadas de la lámina; solo si coinciden en número, para no tocar superíndices que no
     son notas (p. ej. un exponente escrito con ^2^) */
  document.addEventListener('DOMContentLoaded', function () {
    document.querySelectorAll('ol.aside-footnotes').forEach(function (ol) {
      var notas = ol.querySelectorAll(':scope > li[id^="fn"]');
      var lamina = ol.closest('section');
      if (!notas.length || !lamina) return;
      var llamadas = Array.prototype.filter.call(lamina.querySelectorAll('sup'), function (sup) {
        return /^\d+$/.test(sup.textContent) && !sup.closest('table') && !sup.closest('aside');
      });
      if (llamadas.length !== notas.length) return;
      ol.setAttribute('start', notas[0].id.replace('fn', ''));
      llamadas.forEach(function (sup, i) { sup.textContent = notas[i].id.replace('fn', ''); });
    });
  });
  </script>
  <style>
  /* Reglas del tema Inferencia Causal, movidas aquí desde la sección scss:rules de
     theme-ic.scss por un bug de Quarto 1.9.38 (su exportador de "css vars" falla ante
     cualquier tema revealjs con scss:rules). Este <style> se inserta después del <link>
     del tema, así que gana el cascade igual que antes. */
  /* ============ tokens ============ */
  :root{
    --main-font:"Inter", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
    --head-font:"Inter", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
    --code-font:"SFMono-Regular", Consolas, "Liberation Mono", monospace;
    --deep:#163D34; --deep-2:#12332A; --green:#2B7258; --green-700:#215546;
    --guinda:#9B2247; --paper:#F5F6F3; --ink:#16211D; --muted:#586761;
    --line:rgba(22,33,29,.12); --line-strong:rgba(22,33,29,.18);
    --rail:#EAF1ED; --code-ink:#E6EFE8;
  }

  .reveal{ font-family:var(--main-font); font-weight:400; color:var(--ink); }
  .reveal .slides{ text-align:left; }
  .reveal .slides section{ text-align:left; height:100%; }

  /* ============ encabezados de contenido (h2 = título de diapositiva) ============ */
  .reveal h1, .reveal h2, .reveal h3, .reveal h4{
    font-family:var(--head-font); font-weight:800; letter-spacing:-.02em; line-height:1.05; color:var(--deep);
    margin:0 0 .55em; text-transform:none; text-align:left;
  }
  /* barra guinda antes del título de diapositiva (h2 en decks con ##; h1 en decks sin ##) */
  .reveal section > h2:first-child,
  .reveal section:not(.portada):not(.divider):not(.final) > h1:first-child{
    position:relative; padding-left:.6em; margin-bottom:.7em;
  }
  .reveal section > h2:first-child::before,
  .reveal section:not(.portada):not(.divider):not(.final) > h1:first-child::before{
    content:""; position:absolute; left:0; top:.1em; bottom:.1em; width:.16em;
    background:var(--guinda); border-radius:3px;
  }
  /* h1 como título de contenido (decks que usan # para cada diapositiva) */
  .reveal section:not(.portada):not(.divider):not(.final) > h1:first-child{
    color:var(--deep); font-size:1.6em; line-height:1.05;
  }

  /* ============ cuerpo, viñetas ============ */
  .reveal p{ line-height:1.45; margin:0 0 .7em; }
  .reveal ul{ list-style:none !important; margin:0 0 .6em; padding:0; }  /* !important: quita el marcador nativo también en sublistas (reveal pone ■) */
  /* '>' (hijo directo): el punto verde SOLO va en los <li> de un <ul>,
     nunca en los de una lista numerada (<ol>) anidada bajo una viñeta */
  .reveal ul > li{ position:relative; padding-left:1.4em; margin:.5em 0; line-height:1.4; }
  .reveal ul > li::before{
    content:""; position:absolute; left:.05em; top:.62em; width:.42em; height:.42em;
    border-radius:50%; background:var(--green);
  }
  .reveal ul ul{ margin:.35em 0 .3em; }
  .reveal ul ul > li::before{ background:var(--muted); width:.34em; height:.34em; }
  /* listas numeradas anidadas bajo una viñeta: número sí, punto no */
  .reveal ul ol{ margin:.35em 0 .3em; }
  .reveal ol > li{ margin:.4em 0; line-height:1.4; }
  .reveal ol{ padding-left:1.2em; }
  .reveal li{ margin:.45em 0; }
  .reveal strong{ color:var(--deep); font-weight:700; }
  .reveal em{ color:var(--muted); }
  .reveal a{ color:var(--green); text-decoration:none; }
  .reveal a:hover{ color:var(--deep); }

  /* ============ columnas ============ */
  .reveal .columns{ display:flex; align-items:center; gap:1.4em; }

  /* ============ código (bloque verde vivo, letras claras) ============ */
  .reveal pre{ box-shadow:none; width:100%; margin:.4em 0 .9em; }
  .reveal div.sourceCode{
    background:var(--deep); border:1px solid rgba(255,255,255,.10);
    border-radius:10px; margin:.4em 0 .9em;
  }
  .reveal pre code{
    background:transparent; color:var(--code-ink); border-radius:10px; padding:.8em 1.1em;
    font-family:var(--code-font); font-size:.7em; line-height:1.55; max-height:none;
  }
  /* Fondos transparentes en pre y code para que se vea el verde del div.sourceCode, y
     texto base claro. Especificidad alta + !important porque quarto inyecta DESPUÉS sus
     defaults .reveal pre code{background-color:#fff;color:#222} y code.sourceCode > span. */
  .reveal div.sourceCode > pre,
  .reveal div.sourceCode pre.sourceCode{ background:transparent !important; }
  .reveal div.sourceCode pre code,
  .reveal div.sourceCode pre code.sourceCode{ background:transparent !important; color:var(--code-ink); }
  .reveal div.sourceCode pre code > span,
  .reveal div.sourceCode pre code.sourceCode > span{ color:var(--code-ink); }
  /* Con output-location: column el bloque de código vive dentro de .column-output-location y
     quarto le repone el fondo blanco; lo regresamos al verde del resto de los bloques */
  .reveal .column-output-location div.sourceCode,
  .reveal .column-output-location div.sourceCode.cell-code{ background:var(--deep) !important; }
  /* resaltado de sintaxis legible sobre el verde profundo (paleta de la marca) */
  .reveal .sourceCode span.co, .reveal .sourceCode span.do,
  .reveal .sourceCode span.cv, .reveal .sourceCode span.an,
  .reveal .sourceCode span.in{ color:#84A99A; font-style:italic; }              /* comentarios */
  .reveal .sourceCode span.st, .reveal .sourceCode span.ch,
  .reveal .sourceCode span.sc, .reveal .sourceCode span.vs,
  .reveal .sourceCode span.ss{ color:#EFC777; }                                 /* cadenas */
  .reveal .sourceCode span.kw, .reveal .sourceCode span.cf{ color:#F3A6BE; }    /* palabras clave */
  .reveal .sourceCode span.fu, .reveal .sourceCode span.im{ color:#8FE3C6; }    /* funciones */
  .reveal .sourceCode span.dv, .reveal .sourceCode span.fl,
  .reveal .sourceCode span.bn, .reveal .sourceCode span.cn{ color:#EEA9B8; }    /* números */
  .reveal .sourceCode span.dt, .reveal .sourceCode span.at,
  .reveal .sourceCode span.ot, .reveal .sourceCode span.va,
  .reveal .sourceCode span.op{ color:#C2E0D3; }                                 /* tipos / args / operadores */
  .reveal .sourceCode span.al, .reveal .sourceCode span.er,
  .reveal .sourceCode span.wa{ color:#FF9E9E; }                                 /* alertas / errores */

  .reveal code{ font-family:var(--code-font); color:var(--deep); }  /* código en línea sobre papel */
  /* salida / resultados de R: caja clara para contrastar con el bloque de código verde */
  .reveal .cell-output pre code{ background:#fff; color:var(--ink); border:1px solid var(--line); }

  /* ============ tablas ============ */
  .reveal table{ border-collapse:collapse; margin:.4em 0 .8em; font-size:.9em; background:#fff;
    border:1px solid var(--line); border-radius:10px; overflow:hidden; }
  .reveal table th{
    background:var(--guinda); color:#fff !important; text-align:center; font-weight:700;
    text-transform:uppercase; letter-spacing:.06em; font-size:.78em; padding:.5em .8em; border:none;
  }
  /* el contenido de las celdas de encabezado oscuras (incluido MathJax, que trae su propio color)
     también en blanco */
  .reveal table th *{ color:#fff !important; }
  .reveal table th svg, .reveal table th svg *{ fill:#fff !important; }
  /* título de tabla (add_header_above con background="white") → fondo blanco, texto negro.
     Se empata por la presencia del estilo inline background-color (solo lo trae ese título;
     las celdas guinda reciben su color por CSS, no inline). Sin ':' dentro de la cadena para
     no romper el analizador de css-vars de Quarto. */
  .reveal table th[style*="background-color"],
  .reveal table th[style*="background-color"] *{
    color:#141414 !important;
  }
  .reveal table td{ padding:.5em .8em; border-top:1px solid var(--line); text-align:center;
    font-variant-numeric:tabular-nums; }
  .reveal table tr:nth-child(even) td{ background:#FBFCFB; }
  /* kableExtra scroll_box: una altura en % no resuelve dentro de una diapositiva reveal (no hay
     padre con altura fija) → forzamos una altura máx. fija para que la tabla haga scroll y quepa */
  .reveal div[style*="overflow-y"]{
    height:auto !important; max-height:560px !important;
  }
  /* Encabezado fijo al hacer scroll dentro de un scroll_box. kableExtra ya marca cada th como
     sticky, pero dos cosas lo anulaban: el border-collapse:collapse de arriba (Chrome ignora
     sticky en celdas de tablas colapsadas) y el overflow:hidden de la tabla (la convertía en el
     ancestro de scroll, en vez del recuadro). Aquí se revierten ambos solo para estas tablas y
     el sticky se aplica al thead completo, para que las dos filas de encabezado —el título de
     add_header_above y los nombres de columna— se queden juntas y sin encimarse. */
  .reveal div[style*="overflow-y"] table{
    border-collapse:separate !important; border-spacing:0 !important; overflow:visible !important;
  }
  .reveal div[style*="overflow-y"] thead{ position:sticky; top:0; z-index:3; }
  .reveal div[style*="overflow-y"] thead th{ position:static !important; }
  /* kableExtra footnote: a veces no aplica colspan y la nota queda en la 1a columna con celdas
     vacías al lado → la hacemos ocupar todo el ancho de la tabla */
  /* kableExtra a veces no le pone colspan a la nota → un script en _ic-header.html se lo pone
     y quita las celdas vacías; aquí solo la alineamos a la izquierda */
  .reveal tfoot td{ text-align:left !important; }

  /* ============ ecuaciones ============ */
  .reveal .MathJax, .reveal mjx-container{ color:var(--deep); }

  /* ============ callout / idea clave (Quarto callouts o .idea) ============ */
  .reveal .idea{
    background:rgba(155,34,71,.07); border:1px solid rgba(155,34,71,.18);
    border-left:.28em solid var(--guinda); border-radius:0 14px 14px 0; padding:.9em 1.1em;
  }
  .reveal .idea .idea-l{ font-size:.6em; font-weight:800; letter-spacing:.12em; text-transform:uppercase;
    color:var(--guinda); display:block; margin-bottom:.4em; }
  .reveal .idea .idea-big{ font-size:1.2em; font-weight:800; letter-spacing:-.02em; color:var(--deep);
    line-height:1.15; margin:0; }

  /* ============ frase / cita (.phrase): quote centrada en cursiva + fuente abajo-derecha ============ */
  .reveal .phrase{
    position:relative;
    background:rgba(155,34,71,.06); border:1px solid rgba(155,34,71,.18);
    border-left:.28em solid var(--guinda); border-radius:0 14px 14px 0;
    padding:1.1em 1.7em 1em;
  }
  .reveal .phrase::before{                 /* comilla decorativa sutil, esquina superior izq. */
    content:"\201C"; position:absolute; top:.06em; left:.32em; pointer-events:none;
    font-family:Georgia,"Times New Roman",serif; font-size:2.4em; line-height:1; color:var(--guinda); opacity:.25;
  }
  .reveal .phrase p{
    text-align:center; font-style:italic; font-size:1.18em; color:var(--deep); line-height:1.45; margin:0 0 .45em;
  }
  .reveal .phrase p:last-child{ margin-bottom:0; }
  .reveal .phrase .cite{                   /* la fuente/cita: abajo a la derecha, sin cursiva */
    display:block; text-align:right; font-style:normal; font-weight:600;
    font-size:.72em; color:var(--muted); letter-spacing:.02em; margin-top:.8em;
  }

  /* ============ cromo: footer, número de diapositiva, logo ============ */
  .reveal .footer{
    text-align:left !important; left:3.2% !important; right:auto !important; bottom:2.6%; width:auto !important;
    color:var(--muted); font-size:.5em; font-weight:600; letter-spacing:.03em;
  }
  .reveal .footer p, .reveal .footer > *{ margin:0; text-align:left !important; }
  .reveal .slide-number{
    background:transparent; color:var(--muted); font-family:var(--main-font); font-weight:700;
    font-size:.5em; top:auto !important; bottom:2.6% !important; right:3.2% !important; left:auto;
    font-variant-numeric:tabular-nums; letter-spacing:.04em;
  }
  /* logo CIDE — teja blanca arriba a la derecha en todas las diapositivas */
  .reveal .slide-logo{
    position:fixed; top:3.4%; right:3%; bottom:auto; max-height:none;
    height:5.6%; width:auto; aspect-ratio:1; background:#fff; border-radius:8px; padding:.35%;
    box-shadow:0 1px 4px rgba(0,0,0,.18); object-fit:contain; z-index:40;
  }
  /* ocultar footer y número en portada / divisores / final (data-state="nochrome" → clase en <body>) */
  body.nochrome .footer, body.nochrome .slide-number{ display:none !important; }

  /* ============ PORTADA (verde profundo) ============ */
  .reveal section.portada{
    display:flex !important; flex-direction:column; justify-content:center; align-items:flex-start;
    height:100%; padding:0 8%; text-align:left;
  }
  .reveal section.portada h1{
    color:#fff; font-size:4em; line-height:1.02; margin:0; padding:0; letter-spacing:-.03em;
  }
  .reveal section.portada h1::after{
    content:""; display:block; width:1.9em; height:.16em; background:var(--guinda);
    border-radius:3px; margin:.7em 0 1em;
  }
  .reveal section.portada .pa-eyebrow{
    order:-1; font-size:1.15em; font-weight:600; color:#9FD3BB; letter-spacing:.01em; margin-bottom:.85em;
  }
  .reveal section.portada .pa-name{ font-weight:600; color:#fff; font-size:1.35em; }
  .reveal section.portada .pa-icons{ margin-left:.5em; }
  .reveal section.portada .pa-icons a{ color:#E78AA1; margin:0 .2em; font-size:1.35em; }
  .reveal section.portada .pa-icons a:hover{ color:#fff; }
  .reveal section.portada .pa-inst{
    margin-top:1.3em; color:#9FD3BB; font-size:.92em; font-weight:600; letter-spacing:.14em; text-transform:uppercase; line-height:1.75;
  }

  /* ============ DIVISOR DE SECCIÓN (fondo guinda) — marcar el # con {.divider} ============ */
  .reveal section.divider{
    display:flex !important; flex-direction:column; justify-content:center; align-items:flex-start;
    height:100%; padding:0 8%;
  }
  .reveal section.divider > h1{ color:#fff; font-size:3.2em; line-height:1.02; margin:0; }

  /* ============ SLIDE FINAL (créditos, fondo guinda) ============ */
  .reveal section.final{
    display:flex !important; flex-direction:column; justify-content:center; align-items:flex-start;
    height:100%; padding:0 8%; color:#fff;
  }
  .reveal section.final .f-eyebrow{ order:-1; font-size:.86em; font-weight:600; color:#F4C6D2; margin:0 0 .9em; }
  .reveal section.final h1, .reveal section.final h2{ color:#fff; font-size:2.4em; margin:0; padding:0; }
  .reveal section.final h1::before, .reveal section.final h2::before{ display:none; }
  .reveal section.final h1{ font-weight:800; letter-spacing:-.02em; }
  .reveal section.final .f-inst{ font-size:.82em; font-weight:600; letter-spacing:.05em; color:#F1D6DE; margin:.5em 0 0; }
  .reveal section.final .f-inst a{ color:inherit; border-bottom:1px solid rgba(255,255,255,.4); text-decoration:none; }
  .reveal section.final .f-inst a:hover{ border-bottom-color:#fff; }
  .reveal section.final .f-icons{ margin-top:1em; font-size:1.4em; }
  .reveal section.final .f-icons a{ color:#fff; margin:0 .22em; }
  .reveal section.final .f-rule{ width:2.4em; height:.12em; background:rgba(255,255,255,.7); border-radius:2px; margin:1.1em 0; }
  .reveal section.final .f-copy{ font-size:.56em; color:#EAC5CF; margin:0; max-width:40em; line-height:1.5; }
  .reveal section.final .f-copy strong{ color:#fff; }

  /* ============ fragmentos ============ */
  .reveal .fragment{ text-align:left; }
  </style>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
  <script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
  <link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">


<section id="selección-por-observables" class="title-slide slide level1 portada center" data-background-color="#163D34" data-state="nochrome">
<h1>Selección por Observables</h1>
<div class="pa-eyebrow">
<p>Inferencia Causal</p>
</div>
<p><span class="pa-name">Irvin Rojas</span> <span class="pa-icons"><a href="https://github.com/rojasirvin" target="_blank" aria-label="GitHub"><i class="bi bi-github"></i></a> <a href="https://scholar.google.com/citations?hl=es&amp;user=FUwdSTMAAAAJ&amp;view_op=list_works&amp;sortby=pubdate" target="_blank" aria-label="Google Scholar"><i class="bi bi-mortarboard-fill"></i></a> <a href="mailto:irvin.rojas@cide.edu" aria-label="Correo"><i class="bi bi-envelope-fill"></i></a></span></p>
<div class="pa-inst">
<p>Centro de Investigación y Docencia Económicas<br>Maestría en Economía</p>
</div>
<div class="cell">
<style type="text/css">
.huge .remark-code { /*Change made here*/
  font-size: 200% !important;
}
.tiny .remark-code { /*Change made here*/
  font-size: 60% !important;
}
/* Láminas con código y salida de R más grandes que el .7em del tema; mismo
   tamaño en todas, con interlineado y márgenes más compactos para que quepan */
.reveal .codigo-grande div.sourceCode pre code.sourceCode { font-size: 1.3em !important; line-height: 1.4; }
.reveal .codigo-grande .cell-output pre code { font-size: 1.3em; line-height: 1.25; padding: .45em 1.1em; }
.reveal .codigo-grande pre, .reveal .codigo-grande div.sourceCode { margin: .25em 0 .45em; }
/* Salida larga de R (22 coeficientes): más grande que el .7em del tema, pero
   sin llegar al tamaño de .codigo-grande para que quepa en una lámina */
.reveal .salida-mediana .cell-output pre code { font-size: .95em; line-height: 1.2; }
/* Salida muy larga (summary de matchit): letra más grande dentro de un recuadro
   con scroll vertical, en lugar de encogerla para que quepa */
.reveal .salida-scroll .cell-output pre { max-height: 560px; overflow-y: auto; border: 1px solid var(--line); border-radius: 10px; }
.reveal .salida-scroll .cell-output pre code { font-size: 1.3em; line-height: 1.3; max-height: none !important; overflow: visible !important; border: 0; }
/* Tabla de balance junto a su código: más chica para que quepa en media lámina */
.reveal .tabla-compacta table { font-size: .62em; }
/* El tema centra verticalmente las columnas; aquí arrancan al mismo nivel */
.reveal .columnas-arriba .columns { align-items: flex-start; }
/* El tema limita los scroll_box a 560px; esta lámina solo tiene la tabla */
.reveal .tabla-alta div[style*="overflow-y"] { max-height: 770px !important; }
</style>
</div>
</section>

<section>
<section id="selección-por-observables-1" class="title-slide slide level1 divider center" data-background-color="#9B2247" data-state="nochrome">
<h1>Selección por Observables</h1>

</section>
<section id="motivación" class="slide level2">
<h2>Motivación</h2>
<ul>
<li><p>Hemos estudiado la conveniencia de los experimentos para revelar relaciones causales</p></li>
<li><p>También hemos destacado las limitaciones de los diseños experimentales</p></li>
<li><p>Algunos métodos nos permiten usar datos observacionales y supuestos estadísticos para estimar relaciones causales en ausencia de variación experimental</p></li>
<li><p>Los métodos basados en selección en observables dieron origen a una literatura extensa en economía en la década de los 2000, sin embargo, su aplicación actual como método de inferencia principal es muy limitada</p></li>
<li><p>En cambio, los fundamentos de los métodos basados en observables son piezas clave en métodos modernos de inferencia causal que usan <em>machine learning</em> o los conocidos como <em>estimadores doblemente robustos</em></p></li>
</ul>
</section>
<section id="organización-de-lo-que-cubriremos-en-el-curso" class="slide level2">
<h2>Organización de lo que cubriremos en el curso</h2>
<ol type="1">
<li>Supuesto de independencia condicional</li>
<li>Métodos de <em>matching</em>
<ul>
<li><em>Matching</em> basado en covariables</li>
<li><em>Propensity score matching</em></li>
</ul></li>
<li>Otros métodos basados en el SIC
<ul>
<li>Regresión</li>
<li>Métodos locales</li>
<li><em>Inverse probability weighting</em></li>
<li>Métodos doblemente robustos</li>
</ul></li>
</ol>
</section>
<section id="recordatorio-del-sesgo-de-selección" class="slide level2">
<h2>Recordatorio del sesgo de selección</h2>
<ul>
<li><p>Las razones que determinan la asignación del tratamiento determinan también el valor de <span class="math inline">\(Y\)</span></p></li>
<li><p>Una comparación observacional nos da el efecto del tratamiento más el sesgo de selección:</p></li>
</ul>
<p><span class="math display">\[
\begin{aligned}
E(Y|D=1)-E(Y|D=0)=&amp;\overbrace{ E(Y(1)|D=1)-E(Y(0)|D=1)}^{\Delta_{TOT}\text{: efecto promedio en los tratados}}+\\&amp; \underbrace{E(Y(0)|D=1)-E(Y(0)|D=0)}_{\text{Sesgo de selección}}
\end{aligned}
\]</span></p>
<ul>
<li><p>Una forma de eliminar el sesgo de selección es mediante la asignación aleatoria del tratamiento</p></li>
<li><p>Esto no siempre es posible, por lo que recurrimos a supuestos estadísticos</p></li>
</ul>
</section>
<section id="supuesto-de-independencia-condicional" class="slide level2">
<h2>Supuesto de independencia condicional</h2>
<ul>
<li><strong>Supuesto 1. Independencia condicional (SIC)</strong>: condicional en una serie de características <span class="math inline">\(X\)</span>, los resultados potenciales son independientes del tratamiento</li>
</ul>
<p><span class="math display">\[\{Y(0),Y(1)\}\perp D | X\]</span></p>
<ul>
<li>El SIC también se conoce como inconfundibilidad, ignorabilidad del tratamiento o <em>unconfoundedness</em></li>
</ul>
</section>
<section id="supuesto-de-independencia-condicional-1" class="slide level2">
<h2>Supuesto de independencia condicional</h2>
<ul>
<li>El SIC dice que al <em>controlar</em> por una serie de características <span class="math inline">\(X\)</span>, el tratamiento es <em>como</em> si fuera aleatorio:</li>
</ul>
<p><span class="math display">\[
E(Y(1)|D=1,X)=E(Y(1)|D=0,X)
\]</span></p>
<p><span class="math display">\[
E(Y(0)|D=1,X)=E(Y(0)|D=0,X)
\]</span></p>
<ul>
<li>Los valores esperados de <span class="math inline">\(Y(1)\)</span> y <span class="math inline">\(Y(0)\)</span> son iguales cuando nos fijamos en cada valor de <span class="math inline">\(X\)</span></li>
</ul>
</section>
<section id="ejemplo-ir-a-la-universidad" class="slide level2">
<h2>Ejemplo: ir a la universidad</h2>
<ul>
<li><p>Supongamos que <span class="math inline">\(D\)</span> es ir o no a la universidad y la variable de interés es el ingreso</p></li>
<li><p>Sabemos que la comparación estará contaminada por el sesgo de selección</p></li>
<li><p>Es posible que aquellos que fueron a la universidad de todos modos hubieran tenido un mayor salario, incluso sin haber ido a la universidad, por lo que el sesgo de selección es positivo</p></li>
<li><p>El SIC implica que si hacemos la comparación condicional en <span class="math inline">\(X\)</span>, el sesgo de selección desaparece</p></li>
</ul>
<p><span class="math display">\[
E(Y|D=1,X)-E(Y|D=0,X)=E(Y(1)-Y(0)|X)
\]</span></p>
<ul>
<li><p>Es decir, que si comparamos a personas con y sin tratamiento, con los <span class="math inline">\(X\)</span> <em>fijos</em>, el sesgo de selección desaparece</p></li>
<li><p><em>Mantener fijas</em> las <span class="math inline">\(X\)</span> es el análogo a obtener el promedio del salario en cada nivel de escolaridad en la gráfica de la FEC</p></li>
</ul>
</section>
<section id="ejemplo-ir-a-la-universidad-1" class="slide level2">
<h2>Ejemplo: ir a la universidad</h2>
<ul>
<li><p>Para generalizar el concepto cuando la variable tiene más de dos valores (como con la educación <span class="math inline">\(S\)</span>), escribamos <span class="math inline">\(Y(s)\)</span> para el ingreso potencial con <span class="math inline">\(s\)</span> años de educación</p></li>
<li><p>Esta función nos dice cuál sería el ingreso de un individuo bajo todos los posibles niveles de <span class="math inline">\(s\)</span></p></li>
<li><p>En este caso, asumimos el SIC, que se traduce en: <span class="math display">\[Y(s)\perp S | X\quad \forall\quad s\]</span></p></li>
<li><p>En diseños experimentales, descansamos en el supuesto de independencia de los resultados potenciales con respecto al estatus de tratamiento</p></li>
<li><p>Pero con datos <em>observacionales</em>, el SIC significa que <span class="math inline">\(S\)</span> es <em>casi como si fuera asignado de manera aleatoria</em> cuando condicionamos en <span class="math inline">\(X\)</span></p></li>
</ul>
</section>
<section id="ejemplo-ir-a-la-universidad-2" class="slide level2">
<h2>Ejemplo: ir a la universidad</h2>
<ul>
<li><p>En los datos solo observamos <span class="math inline">\(Y=Y(S)\)</span></p></li>
<li><p>Dado el SIC, podemos hacer comparaciones de ingreso promedio para distintos niveles de educación:</p></li>
</ul>
<p><span class="math display">\[E(Y|S=s,X)-E(Y|S=s-1,X)=E(Y(s)-Y(s-1)|X)\]</span></p>
<ul>
<li>Notemos que lo impráctico de esto es que tendríamos que hacer comparaciones en pares y luego tratar de hacer un promedio ponderado por el número de individuos en cada nivel de educación</li>
</ul>
</section>
<section id="regresión-para-hacer-las-comparaciones" class="slide level2">
<h2>Regresión para hacer las comparaciones</h2>
<ul>
<li>Supongamos una función causal para el ingreso</li>
</ul>
<p><span class="math display">\[Y(s)=\alpha+\rho s+\nu\]</span></p>
<p>que indica lo que un individuo ganaría para todo valor de <span class="math inline">\(s\)</span> (y no solo el valor realizado <span class="math inline">\(S\)</span>)</p>
<ul>
<li><p>La única parte aleatoria es el error con media cero <span class="math inline">\(\nu\)</span>, que captura los factores no observados que afectan los ingresos</p></li>
<li><p>Sustituyendo el valor observado:</p></li>
</ul>
<p><span class="math display">\[Y=\alpha+\rho S+\nu\]</span></p>
<ul>
<li><span class="math inline">\(S\)</span> puede estar correlacionado con los resultados potenciales <span class="math inline">\(Y(s)\)</span>, es decir, correlacionado con el error <span class="math inline">\(\nu\)</span></li>
</ul>
</section>
<section id="regresión-para-hacer-las-comparaciones-1" class="slide level2">
<h2>Regresión para hacer las comparaciones</h2>
<ul>
<li><p>Supongamos que el SIC se cumple dado un vector <span class="math inline">\(X\)</span></p></li>
<li><p>Descompongamos el error en una función lineal de las características <span class="math inline">\(X\)</span> y un error <span class="math inline">\(u\)</span>:</p></li>
</ul>
<p><span class="math display">\[\nu=X'\gamma+u\]</span></p>
<p>donde se asume que <span class="math inline">\(E(\nu|X)=X'\gamma\)</span> y donde <span class="math inline">\(u\)</span> y <span class="math inline">\(X\)</span> no están correlacionados</p>
<ul>
<li>Si se cumple el SIC, entonces:</li>
</ul>
<p><span class="math display">\[
\begin{aligned}
E(Y(s)|X,S)=E(Y(s)|X)&amp;=\alpha+\rho s+E(\nu|X) \\
&amp;=\alpha+\rho s + X'\gamma
\end{aligned}
\]</span></p>
<ul>
<li><p>Es decir, en el modelo de regresión causal <span class="math inline">\(Y=\alpha+\rho S+ X'\gamma+u\)</span>, <span class="math inline">\(u\)</span> no está correlacionado con los regresores <span class="math inline">\(X\)</span> y <span class="math inline">\(S\)</span></p></li>
<li><p><span class="math inline">\(\rho\)</span> es el efecto causal de interés</p></li>
<li><p>El supuesto clave es que la única razón por la cual <span class="math inline">\(\nu\)</span> y <span class="math inline">\(S\)</span> están correlacionados es <span class="math inline">\(X\)</span></p></li>
</ul>
</section>
<section id="supuesto-de-soporte-común" class="slide level2">
<h2>Supuesto de soporte común</h2>
<ul>
<li><strong>Supuesto 2. Soporte común</strong>: para cualquier combinación de covariables en la población, existen individuos tratados y no tratados</li>
</ul>
<p><span class="math display">\[0&lt;p(X)&lt;1\]</span></p>
<p>donde <span class="math inline">\(p(X)=\Pr(D=1|X)\)</span> es la probabilidad condicional de recibir el tratamiento o <em>propensity score (PS)</em></p>
<ul>
<li>El soporte común descarta que haya covariables que predigan determinísticamente la asignación de tratamiento</li>
</ul>
</section>
<section id="supuestos-de-identificación-del-tot" class="slide level2">
<h2>Supuestos de identificación del TOT</h2>
<ul>
<li><p>Cuando se cumple <strong>Supuesto 1</strong> <span class="math inline">\(+\)</span> <strong>Supuesto 2</strong> se conoce como <strong>ignorabilidad fuerte</strong></p></li>
<li><p>Heckman, Ichimura y Todd (1998) muestran que estas condiciones son demasiado estrictas si nos interesa estimar solo el TOT</p></li>
<li><p>Para identificar el TOT es suficiente:</p></li>
<li><p><strong>Supuesto 1a. Inconfundibilidad en el control</strong></p></li>
</ul>
<p><span class="math display">\[
Y(0) \perp  D | X
\]</span></p>
<ul>
<li><strong>Supuesto 2a. Traslape débil</strong></li>
</ul>
<p><span class="math display">\[
p(X) &lt; 1
\]</span></p>
</section></section>
<section>
<section id="matching-exacto" class="title-slide slide level1 divider center" data-background-color="#9B2247" data-state="nochrome">
<h1>Matching exacto</h1>

</section>
<section id="matching-exacto-1" class="slide level2">
<h2>Matching exacto</h2>
<ul>
<li><p>Un estimador de matching exacto consiste en <em>emparejar</em> individuos tratados y no tratados para cada valor específico de las <span class="math inline">\(X\)</span> y estimar un promedio ponderado de las diferencias</p></li>
<li><p>Tenemos datos observacionales de individuos que recibieron y no recibieron un tratamiento y tenemos una serie de características <span class="math inline">\(X\)</span></p></li>
<li><p>Bajo el SIC, podemos eliminar el sesgo de selección al estimar las diferencias de <span class="math inline">\(Y\)</span> dentro de grupos con las mismas <span class="math inline">\(X\)</span></p></li>
<li><p>Requerimos que existan observaciones tratadas y no tratadas para todas las características <span class="math inline">\(X\)</span></p></li>
</ul>
</section>
<section id="ejemplo-programa-hipotético-de-empleo" class="slide level2">
<h2>Ejemplo: programa hipotético de empleo</h2>
<ul>
<li>Usemos <a href="https://mixtape.scunning.com/matching-and-subclassification.html?panelset=r-code">el ejemplo</a> en The Mixtape (MT):</li>
</ul>
</section>
<section id="ejemplo-programa-hipotético-de-empleo-1" class="slide level2 codigo-grande columnas-arriba">
<h2>Ejemplo: programa hipotético de empleo</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>Los individuos tratados:</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   unit_treat age_treat earnings_treat
        &lt;dbl&gt;     &lt;dbl&gt;          &lt;dbl&gt;
 1          1        18           9500
 2          2        29          12250
 3          3        24          11000
 4          4        27          11750
 5          5        33          13250
 6          6        22          10500
 7          7        19           9750
 8          8        20          10000
 9          9        21          10250
10         10        30          12500</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>Mientras que los no tratados:</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 3
   unit_control age_control earnings_control
          &lt;dbl&gt;       &lt;dbl&gt;            &lt;dbl&gt;
 1            1          20             8500
 2            2          27            10075
 3            3          21             8725
 4            4          39            12775
 5            5          38            12550
 6            6          29            10525
 7            7          39            12775
 8            8          33            11425
 9            9          24             9400
10           10          30            10750
11           11          33            11425
12           12          36            12100
13           13          22             8950
14           14          18             8050
15           15          43            13675
16           16          39            12775
17           17          19             8275
18           18          30             9000
19           19          51            15475
20           20          48            14800</code></pre>
</div>
</div>
</div></div>
</section>
<section id="comparación-observacional" class="slide level2 codigo-grande">
<h2>Comparación observacional</h2>
<ul>
<li>Si hiciéramos diferencias simples obtendríamos:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-label="1"></a><span class="fu">mean</span>(data.treat<span class="sc">$</span>earnings_treat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11075</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-label="1"></a><span class="fu">mean</span>(data.control<span class="sc">$</span>earnings_control)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11101.25</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a aria-label="1"></a><span class="co">#Diferencia</span></span>
<span id="cb7-2"><a aria-label="2"></a><span class="fu">mean</span>(data.treat<span class="sc">$</span>earnings_treat) <span class="sc">-</span> <span class="fu">mean</span>(data.control<span class="sc">$</span>earnings_control)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -26.25</code></pre>
</div>
</div>
<ul>
<li>Parece que en el grupo de control ganan más (efecto de tratamiento negativo)</li>
</ul>
</section>
<section id="comparación-observacional-1" class="slide level2 codigo-grande">
<h2>Comparación observacional</h2>
<ul>
<li><p>El principal problema con esta diferencia es que sabemos que los ingresos crecen con la edad</p></li>
<li><p>La muestra de no tratados tiene mayor edad promedio:</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a aria-label="1"></a><span class="fu">mean</span>(data.treat<span class="sc">$</span>age_treat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a aria-label="1"></a><span class="fu">mean</span>(data.control<span class="sc">$</span>age_control)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 31.95</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a aria-label="1"></a><span class="co">#Diferencia</span></span>
<span id="cb13-2"><a aria-label="2"></a><span class="fu">mean</span>(data.treat<span class="sc">$</span>age_treat) <span class="sc">-</span> <span class="fu">mean</span>(data.control<span class="sc">$</span>age_control)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -7.65</code></pre>
</div>
</div>
<ul>
<li>Estamos <em>confundiendo</em> el efecto de la edad</li>
</ul>
</section>
<section id="muestra-emparejada" class="slide level2">
<h2>Muestra emparejada</h2>
<ul>
<li><p>Construyamos la muestra emparejada buscando, para cada individuo en el grupo tratado, uno en el de control que tenga la misma edad. Cuando le encontramos un individuo no tratado al tratado con la misma edad decimos que esa pareja hizo <em>match</em></p></li>
<li><p>Por ejemplo, la primera unidad tratada, con 18 años y un ingreso de 9,500 estaría emparejada con la unidad 14 del grupo de control, que tiene también 18 años y un ingreso de 8,050</p></li>
<li><p>Para dicho individuo de 18 años, su ingreso contrafactual sería 8,050</p></li>
<li><p>Cuando hay varias unidades en el grupo de control que pueden ser empatadas con la de tratamiento, podemos construir el ingreso contrafactual calculando el promedio</p></li>
<li><p>Del grupo de control, los individuos 10 y 18 tienen 30 años, con ingresos 10,750 y 9,000, por lo que usamos el promedio (9,875) para crear el contrafactual del individuo tratado de 30 años de la fila 10</p></li>
</ul>
</section>
<section id="muestra-emparejada-1" class="slide level2 codigo-grande">
<h2>Muestra emparejada</h2>
<ul>
<li>La muestra emparejada o contrafactual será:</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   unit_matched age_matched earnings_matched
          &lt;dbl&gt;       &lt;dbl&gt;            &lt;dbl&gt;
 1            1          18             8050
 2            2          29            10525
 3            3          24             9400
 4            4          27            10075
 5            5          33            11425
 6            6          22             8950
 7            7          19             8275
 8            8          20             8500
 9            9          21             8725
10           10          30             9875</code></pre>
</div>
</div>
</section>
<section id="muestra-emparejada-2" class="slide level2 codigo-grande">
<h2>Muestra emparejada</h2>
<ul>
<li>Noten que la edad es la misma entre los tratados y la muestra emparejada:</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>Muestra de tratados:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a aria-label="1"></a><span class="fu">mean</span>(data.treat<span class="sc">$</span>age_treat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24.3</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>Muestra emparejada:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a aria-label="1"></a><span class="fu">mean</span>(data.matched<span class="sc">$</span>age_matched)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24.3</code></pre>
</div>
</div>
</div></div>
<ul>
<li><p>En este caso, decimos que la edad <em>está balanceada</em></p></li>
<li><p>Y entonces podemos calcular el efecto de tratamiento como la diferencia de ingresos entre los tratados y los no tratados en la muestra emparejada:</p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1695</code></pre>
</div>
</div>
<ul>
<li>En este caso, encontramos un efecto positivo del programa de 1,695 unidades monetarias.</li>
</ul>
</section>
<section id="estimador-de-matching-exacto" class="slide level2">
<h2>Estimador de matching exacto</h2>
<ul>
<li>Podemos definir un <strong>estimador de matching exacto</strong> del TOT basado en una sola característica como:</li>
</ul>
<p><span class="math display">\[\hat{\Delta}_{TOT}=\frac{1}{n_1}\sum_{i:D_i=1}\left(Y_i-\frac{1}{M_i}\sum_{m=1}^{M_i}Y_{j_m(i)}\right)\]</span></p>
<p>donde <span class="math inline">\(n_1\)</span> es el número de tratados, <span class="math inline">\(M_i\)</span> es el número de no tratados con <span class="math inline">\(X_j=X_i\)</span> y <span class="math inline">\(j_m(i)\)</span> es el <span class="math inline">\(m\)</span>-ésimo de ellos</p>
</section>
<section id="importancia-del-soporte-común" class="slide level2">
<h2>Importancia del soporte común</h2>
<ul>
<li>Observemos lo que ocurre con la distribución de edades en ambos grupos:</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<p>Para los tratados:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="figures/grafica_tratados-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>Mientras que para los no tratados:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="figures/grafica_notratados-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
<ul>
<li>El supuesto de traslape débil para identificar el TOT significa que para cada unidad tratada, hay al menos un no tratado</li>
</ul>
</section>
<section id="estimador-de-matching-exacto-del-ate" class="slide level2">
<h2>Estimador de matching exacto del ATE</h2>
<ul>
<li><p>Hasta aquí, solo hemos imputado el contrafactual para cada unidad en el grupo tratado</p></li>
<li><p>Si podemos imputar también, para cada unidad no tratada, su correspondiente contrafactual tratado, podemos estimar el ATE</p></li>
<li><p>Y un <strong>estimador de matching exacto</strong> del ATE sería:</p></li>
</ul>
<p><span class="math display">\[\hat{\Delta}_{ATE}=\frac{1}{n}\sum_{i=1}^{n}(2D_i-1)\left(Y_i-\frac{1}{M_i}\sum_{m=1}^{M_i}Y_{j_m(i)}\right)\]</span></p>
<p>donde ahora <span class="math inline">\(j_m(i)\)</span> recorre las <span class="math inline">\(M_i\)</span> unidades del grupo <em>opuesto</em> al de <span class="math inline">\(i\)</span> con <span class="math inline">\(X_j=X_i\)</span></p>
<ul>
<li>Casi todas las aplicaciones de <em>matching</em> se enfocan en el TOT</li>
</ul>
</section>
<section id="matching-con-más-de-una-característica" class="slide level2">
<h2><em>Matching</em> con más de una característica</h2>
<ul>
<li><p>En general, tenemos varias características en <span class="math inline">\(X\)</span></p></li>
<li><p>Pensamos en <span class="math inline">\(X\)</span> más como una <em>celda</em> de individuos que comparten las mismas características</p></li>
<li><p>Tenemos que tener una regla para definir la distancia mínima entre dos vectores de covariables <span class="math inline">\(X_i\)</span> y <span class="math inline">\(X_j\)</span></p></li>
<li><p>Un <strong>estimador de vecino más cercano</strong> es:</p></li>
</ul>
<p><span class="math display">\[\hat{\Delta}_{TOT}=\frac{1}{n_1}\sum_{i:D_i=1}\left(Y_i-\sum_{j:D_j=0}\mathbb{I}\left\{||X_j-X_i||=\min_{l:D_l=0}||X_l-X_i||\right\} Y_j\right)\]</span></p>
</section>
<section id="decisiones-en-el-matching" class="slide level2">
<h2>Decisiones en el <em>matching</em></h2>
<ul>
<li>¿Realizar el <em>matching</em> con o sin reemplazo?<sup>1</sup></li>
</ul>
<ul>
<li>Sin reemplazo:
<ul>
<li>Reduce la varianza en la estimación al usar un grupo no tratado más grande en lugar de reusar observaciones</li>
<li>Incrementa el sesgo pues algunos <em>matches</em> no podrán hacerse dado que algunas observaciones no tratadas ya han sido descartadas</li>
</ul></li>
<li>¿Cómo medir la distancia entre las covariables?
<ul>
<li>Euclidiana: <span class="math inline">\(||X_j-X_i||_{Euclidiana}=\sqrt{\sum_{k=1}^{K}(X_{jk}-X_{ik})^2}\)</span></li>
<li>Varianza: <span class="math inline">\(||X_j-X_i||_{Varianza}=\sqrt{\sum_{k=1}^{K}\frac{(X_{jk}-X_{ik})^2}{\hat{Var}(X_k)}}\)</span></li>
<li>Mahalanobis: <span class="math inline">\(||X_j-X_i||_{Mahalanobis}=\sqrt{(X_j-X_i)'\hat{\Sigma}_X^{-1}(X_j-X_i)}\)</span>, con <span class="math inline">\(\hat{\Sigma}_X\)</span> la matriz de varianzas y covarianzas de <span class="math inline">\(X\)</span></li>
</ul></li>
</ul>
<aside><ol class="aside-footnotes"><li id="fn1"><p>La discusión en <em>Causal Analysis (CA)</em> asume <em>matching con reemplazo</em>.</p></li></ol></aside></section>
<section id="decisiones-en-el-matching-1" class="slide level2">
<h2>Decisiones en el <em>matching</em></h2>
<ul>
<li>¿Cómo estimar la varianza?
<ul>
<li>Abadie e Imbens (2008) mostraron analíticamente que el bootstrap no es apropiado en el contexto de <em>matching</em></li>
<li>Sin embargo, otros estudios de simulación han mostrado que funciona en muchas aplicaciones de <em>matching</em> y se llega a usar en casos particulares (por ejemplo, cuando el <em>matching</em> se realiza con reemplazo)</li>
<li>El consejo práctico es usar resultados analíticos cuando estos estén disponibles</li>
</ul></li>
</ul>
</section>
<section id="ejemplo-veteranos-del-ejército-de-estados-unidos" class="slide level2">
<h2>Ejemplo: veteranos del ejército de Estados Unidos</h2>
<ul>
<li>Angrist (1998)<sup>1</sup> estudia el efecto del servicio militar sobre los ingresos (inscribirse en el ejército tiene un claro componente de autoselección)</li>
</ul>
<ul>
<li><p>El autor tiene datos <span class="math inline">\(X\)</span>: raza, año de solicitud de ingreso al ejército, escolaridad, calificación en examen de aptitud, año de nacimiento</p></li>
<li><p>Estas características definen <em>celdas</em> y dentro de cada celda tenemos tratados y no tratados</p></li>
<li><p>Se estiman los efectos usando distintas metodologías</p></li>
<li><p>Los impactos estimados usando el matching exacto se encuentran bajo la columna <em>Contraste controlado</em></p></li>
</ul>
<aside><ol class="aside-footnotes"><li id="fn2"><p><a href="https://www.jstor.org/stable/2998558">Estimating the Labor Market Impact of Voluntary Military Service Using Social Security Data on Military Applicants</a>.</p></li></ol></aside></section>
<section id="ejemplo-veteranos-del-ejército-de-estados-unidos-1" class="slide level2 tabla-alta">
<h2>Ejemplo: veteranos del ejército de Estados Unidos</h2>
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:700px; ">
<table class="lightable-paper lightable-hover caption-top" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;border-bottom: 0;">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th colspan="9" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
Estimaciones alternativas del efecto del servicio militar en los ingresos
</div></th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; position: sticky; top: 0; background-color: #FFFFFF;"></th>
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
Blancos
</div></th>
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important; position: sticky; top: 0; background-color: #FFFFFF;"><div style="TRUE">
No blancos
</div></th>
</tr>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; color: white !important; background-color: rgba(155, 34, 71, 255) !important; position: sticky; top: 0; background-color: #FFFFFF;">Año</th>
<th data-quarto-table-cell-role="th" style="text-align: center; color: white !important; background-color: rgba(155, 34, 71, 255) !important; position: sticky; top: 0; background-color: #FFFFFF;">Media<br>
(1)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; color: white !important; background-color: rgba(155, 34, 71, 255) !important; position: sticky; top: 0; background-color: #FFFFFF;">Diferencia de medias<br>
(2)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; color: white !important; background-color: rgba(155, 34, 71, 255) !important; position: sticky; top: 0; background-color: #FFFFFF;">Contraste controlado<br>
(3)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; color: white !important; background-color: rgba(155, 34, 71, 255) !important; position: sticky; top: 0; background-color: #FFFFFF;">Regresión<br>
(4)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; color: white !important; background-color: rgba(155, 34, 71, 255) !important; position: sticky; top: 0; background-color: #FFFFFF;">Media<br>
(5)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; color: white !important; background-color: rgba(155, 34, 71, 255) !important; position: sticky; top: 0; background-color: #FFFFFF;">Diferencia de medias<br>
(6)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; color: white !important; background-color: rgba(155, 34, 71, 255) !important; position: sticky; top: 0; background-color: #FFFFFF;">Contraste controlado<br>
(7)</th>
<th data-quarto-table-cell-role="th" style="text-align: center; color: white !important; background-color: rgba(155, 34, 71, 255) !important; position: sticky; top: 0; background-color: #FFFFFF;">Regresión<br>
(8)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">74</td>
<td style="text-align: center;">182.7</td>
<td style="text-align: center;">-26.1</td>
<td style="text-align: center;">-14.0</td>
<td style="text-align: center;">-13.0</td>
<td style="text-align: center;">157.2</td>
<td style="text-align: center;">-4.9</td>
<td style="text-align: center;">-2.0</td>
<td style="text-align: center;">-3.9</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(7.0)</td>
<td style="text-align: center;">(9.2)</td>
<td style="text-align: center;">(9.4)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(4.4)</td>
<td style="text-align: center;">(6.0)</td>
<td style="text-align: center;">(5.8)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">75</td>
<td style="text-align: center;">237.9</td>
<td style="text-align: center;">-41.4</td>
<td style="text-align: center;">-14.2</td>
<td style="text-align: center;">-12.0</td>
<td style="text-align: center;">216.9</td>
<td style="text-align: center;">-0.6</td>
<td style="text-align: center;">-17.1</td>
<td style="text-align: center;">-15.2</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(6.3)</td>
<td style="text-align: center;">(7.6)</td>
<td style="text-align: center;">(7.8)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(4.5)</td>
<td style="text-align: center;">(6.0)</td>
<td style="text-align: center;">(5.5)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">76</td>
<td style="text-align: center;">473.4</td>
<td style="text-align: center;">-47.9</td>
<td style="text-align: center;">-14.8</td>
<td style="text-align: center;">-12.7</td>
<td style="text-align: center;">413.6</td>
<td style="text-align: center;">-14.5</td>
<td style="text-align: center;">-33.3</td>
<td style="text-align: center;">-30.2</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(8.1)</td>
<td style="text-align: center;">(9.0)</td>
<td style="text-align: center;">(9.3)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(6.4)</td>
<td style="text-align: center;">(8.0)</td>
<td style="text-align: center;">(7.4)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">77</td>
<td style="text-align: center;">1012.9</td>
<td style="text-align: center;">-7.1</td>
<td style="text-align: center;">-8.6</td>
<td style="text-align: center;">-9.4</td>
<td style="text-align: center;">820.9</td>
<td style="text-align: center;">-13.0</td>
<td style="text-align: center;">-56.0</td>
<td style="text-align: center;">-51.3</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(11.3)</td>
<td style="text-align: center;">(12.3)</td>
<td style="text-align: center;">(12.2)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(9.1)</td>
<td style="text-align: center;">(11.1)</td>
<td style="text-align: center;">(10.0)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">78</td>
<td style="text-align: center;">2147.1</td>
<td style="text-align: center;">40.3</td>
<td style="text-align: center;">-23.5</td>
<td style="text-align: center;">-22.4</td>
<td style="text-align: center;">1677.9</td>
<td style="text-align: center;">58.1</td>
<td style="text-align: center;">-53.6</td>
<td style="text-align: center;">-42.5</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(16.7)</td>
<td style="text-align: center;">(18.1)</td>
<td style="text-align: center;">(17.2)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(13.4)</td>
<td style="text-align: center;">(16.1)</td>
<td style="text-align: center;">(14.1)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">79</td>
<td style="text-align: center;">3560.7</td>
<td style="text-align: center;">188.0</td>
<td style="text-align: center;">-8.4</td>
<td style="text-align: center;">-11.2</td>
<td style="text-align: center;">2797.0</td>
<td style="text-align: center;">340.3</td>
<td style="text-align: center;">119.1</td>
<td style="text-align: center;">122.3</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(21.0)</td>
<td style="text-align: center;">(23.2)</td>
<td style="text-align: center;">(21.6)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(16.2)</td>
<td style="text-align: center;">(20.1)</td>
<td style="text-align: center;">(17.2)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">80</td>
<td style="text-align: center;">4709.0</td>
<td style="text-align: center;">572.9</td>
<td style="text-align: center;">178.0</td>
<td style="text-align: center;">175.9</td>
<td style="text-align: center;">3932.2</td>
<td style="text-align: center;">1154.3</td>
<td style="text-align: center;">741.6</td>
<td style="text-align: center;">738.5</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(23.4)</td>
<td style="text-align: center;">(27.2)</td>
<td style="text-align: center;">(24.6)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(18.0)</td>
<td style="text-align: center;">(23.4)</td>
<td style="text-align: center;">(19.5)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">81</td>
<td style="text-align: center;">6226.0</td>
<td style="text-align: center;">855.5</td>
<td style="text-align: center;">249.5</td>
<td style="text-align: center;">249.9</td>
<td style="text-align: center;">5218.8</td>
<td style="text-align: center;">1920.0</td>
<td style="text-align: center;">1299.9</td>
<td style="text-align: center;">1318.5</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(27.2)</td>
<td style="text-align: center;">(32.4)</td>
<td style="text-align: center;">(29.1)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(20.7)</td>
<td style="text-align: center;">(28.2)</td>
<td style="text-align: center;">(23.1)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">82</td>
<td style="text-align: center;">7200.6</td>
<td style="text-align: center;">1508.5</td>
<td style="text-align: center;">783.3</td>
<td style="text-align: center;">782.4</td>
<td style="text-align: center;">6150.2</td>
<td style="text-align: center;">2917.1</td>
<td style="text-align: center;">2186.0</td>
<td style="text-align: center;">2210.1</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(30.3)</td>
<td style="text-align: center;">(36.4)</td>
<td style="text-align: center;">(32.5)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(23.4)</td>
<td style="text-align: center;">(32.0)</td>
<td style="text-align: center;">(26.0)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">83</td>
<td style="text-align: center;">8398.1</td>
<td style="text-align: center;">1390.5</td>
<td style="text-align: center;">588.8</td>
<td style="text-align: center;">601.5</td>
<td style="text-align: center;">7221.1</td>
<td style="text-align: center;">2889.9</td>
<td style="text-align: center;">2103.8</td>
<td style="text-align: center;">2142.3</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(34.4)</td>
<td style="text-align: center;">(41.1)</td>
<td style="text-align: center;">(36.6)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(27.0)</td>
<td style="text-align: center;">(36.7)</td>
<td style="text-align: center;">(29.8)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">84</td>
<td style="text-align: center;">9874.2</td>
<td style="text-align: center;">652.8</td>
<td style="text-align: center;">-235.7</td>
<td style="text-align: center;">-198.5</td>
<td style="text-align: center;">8377.2</td>
<td style="text-align: center;">2202.9</td>
<td style="text-align: center;">1333.0</td>
<td style="text-align: center;">1428.9</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(39.5)</td>
<td style="text-align: center;">(46.9)</td>
<td style="text-align: center;">(41.7)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(30.5)</td>
<td style="text-align: center;">(41.4)</td>
<td style="text-align: center;">(33.4)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">85</td>
<td style="text-align: center;">10972.7</td>
<td style="text-align: center;">469.8</td>
<td style="text-align: center;">-521.3</td>
<td style="text-align: center;">-459.6</td>
<td style="text-align: center;">9306.8</td>
<td style="text-align: center;">1955.5</td>
<td style="text-align: center;">932.3</td>
<td style="text-align: center;">1059.2</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(44.6)</td>
<td style="text-align: center;">(52.6)</td>
<td style="text-align: center;">(46.8)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(34.4)</td>
<td style="text-align: center;">(46.2)</td>
<td style="text-align: center;">(37.3)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">86</td>
<td style="text-align: center;">12004.5</td>
<td style="text-align: center;">543.7</td>
<td style="text-align: center;">-557.3</td>
<td style="text-align: center;">-491.7</td>
<td style="text-align: center;">10106.2</td>
<td style="text-align: center;">1881.3</td>
<td style="text-align: center;">720.9</td>
<td style="text-align: center;">872.3</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(50.4)</td>
<td style="text-align: center;">(59.0)</td>
<td style="text-align: center;">(52.5)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(38.7)</td>
<td style="text-align: center;">(51.2)</td>
<td style="text-align: center;">(41.6)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">87</td>
<td style="text-align: center;">13045.7</td>
<td style="text-align: center;">663.9</td>
<td style="text-align: center;">-548.0</td>
<td style="text-align: center;">-464.3</td>
<td style="text-align: center;">10833.0</td>
<td style="text-align: center;">2050.1</td>
<td style="text-align: center;">751.0</td>
<td style="text-align: center;">925.0</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(54.6)</td>
<td style="text-align: center;">(63.9)</td>
<td style="text-align: center;">(56.8)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(41.8)</td>
<td style="text-align: center;">(55.2)</td>
<td style="text-align: center;">(44.8)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">88</td>
<td style="text-align: center;">14136.1</td>
<td style="text-align: center;">904.3</td>
<td style="text-align: center;">-415.5</td>
<td style="text-align: center;">-311.7</td>
<td style="text-align: center;">11480.1</td>
<td style="text-align: center;">2175.0</td>
<td style="text-align: center;">708.2</td>
<td style="text-align: center;">923.7</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(58.3)</td>
<td style="text-align: center;">(68.2)</td>
<td style="text-align: center;">(60.6)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(44.9)</td>
<td style="text-align: center;">(59.5)</td>
<td style="text-align: center;">(48.1)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">89</td>
<td style="text-align: center;">14716.1</td>
<td style="text-align: center;">1169.1</td>
<td style="text-align: center;">-248.6</td>
<td style="text-align: center;">-136.3</td>
<td style="text-align: center;">11751.4</td>
<td style="text-align: center;">2379.1</td>
<td style="text-align: center;">799.7</td>
<td style="text-align: center;">1031.9</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(61.0)</td>
<td style="text-align: center;">(71.2)</td>
<td style="text-align: center;">(63.2)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(47.6)</td>
<td style="text-align: center;">(62.7)</td>
<td style="text-align: center;">(50.9)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">90</td>
<td style="text-align: center;">14886.1</td>
<td style="text-align: center;">1300.8</td>
<td style="text-align: center;">-154.5</td>
<td style="text-align: center;">-53.2</td>
<td style="text-align: center;">11904.3</td>
<td style="text-align: center;">2483.6</td>
<td style="text-align: center;">824.9</td>
<td style="text-align: center;">1064.0</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(63.0)</td>
<td style="text-align: center;">(73.6)</td>
<td style="text-align: center;">(65.2)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(49.4)</td>
<td style="text-align: center;">(65.4)</td>
<td style="text-align: center;">(52.7)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">91</td>
<td style="text-align: center;">14407.9</td>
<td style="text-align: center;">1559.6</td>
<td style="text-align: center;">29.8</td>
<td style="text-align: center;">146.2</td>
<td style="text-align: center;">11518.7</td>
<td style="text-align: center;">2758.8</td>
<td style="text-align: center;">1026.1</td>
<td style="text-align: center;">1277.9</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(64.6)</td>
<td style="text-align: center;">(75.6)</td>
<td style="text-align: center;">(66.9)</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(50.8)</td>
<td style="text-align: center;">(67.2)</td>
<td style="text-align: center;">(54.3)</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Nota:</span> <sup></sup> Panel A de la Tabla II en Angrist (1998). Errores estándar entre paréntesis.</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>
</div>
</section>
<section id="ejemplo-veteranos-del-ejército-de-estados-unidos-2" class="slide level2">
<h2>Ejemplo: veteranos del ejército de Estados Unidos</h2>
<ul>
<li><p>Noten que la columna (2) muestra lo que se hubiera concluido si solo se comparan diferencias de medias</p></li>
<li><p>Antes de 1980, las diferencias eran muy pequeñas (cero en términos prácticos)</p></li>
<li><p>En esta aplicación esta comparación llevaría a conclusiones incorrectas</p></li>
<li><p>Además, las diferencias para no-blancos y blancos son distintas</p></li>
<li><p>Hay un pico en los efectos alrededor de 1982</p></li>
<li><p>En esta aplicación, los resultados por <em>matching</em> y regresión son muy parecidos hasta 1984</p></li>
<li><p>La conclusión es que existe evidencia de efectos negativos en los ingresos por haber servido en el ejército en los blancos y efectos positivos para los individuos de otras razas</p></li>
</ul>
</section>
<section id="ejemplo-veteranos-del-ejército-de-estados-unidos-3" class="slide level2 columnas-arriba">
<h2>Ejemplo: veteranos del ejército de Estados Unidos</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>Para personas identificadas como blancas:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="ExactMatching_effects_graph_a.jpg" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>Para personas identificadas como no blancas:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="ExactMatching_effects_graph_b.jpg" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section></section>
<section>
<section id="propensity-score-matching" class="title-slide slide level1 divider center" data-background-color="#9B2247" data-state="nochrome">
<h1>Propensity Score Matching</h1>

</section>
<section id="maldición-de-la-dimensionalidad" class="slide level2">
<h2>Maldición de la dimensionalidad</h2>
<ul>
<li><p>En la práctica es difícil manejar problemas en espacios de múltiples dimensiones: <strong>maldición de la dimensionalidad</strong></p></li>
<li><p>El problema de la maldición de la dimensionalidad se exacerba con el tamaño limitado de las bases de datos</p></li>
<li><p>Si <span class="math inline">\(X\)</span> tuviera <span class="math inline">\(K\)</span> indicadores binarios, el número de posibles combinaciones sería <span class="math inline">\(2^K\)</span></p></li>
<li><p>Por ejemplo, si solo tuviéramos <span class="math inline">\(X_1=\{\text{menor de 35 años}, \text{con 35 años o más}\}\)</span>, <span class="math inline">\(X_2=\{\text{más que preparatoria}, \text{menos que preparatoria}\}\)</span>, <span class="math inline">\(X_3=\{\text{indígena}, \text{no indígena}\}\)</span>, tendríamos que hacer ocho comparaciones:</p>
<ul>
<li>menor de 35 años, más que preparatoria, indígena</li>
<li>menor de 35 años, más que preparatoria, no indígena</li>
<li>…</li>
<li>con 35 años o más, menos que preparatoria, no indígena</li>
</ul></li>
<li><p>Pero si <span class="math inline">\(X\)</span> incluye muchas variables, algunas tomando muchos valores, esto se vuelve imposible de realizar</p></li>
</ul>
</section>
<section id="maldición-de-la-dimensionalidad-1" class="slide level2">
<h2>Maldición de la dimensionalidad</h2>
<ul>
<li><p>El requerimiento de soporte común significa que debemos tener tratados y no tratados para cada valor de <span class="math inline">\(X\)</span> para hacer comparaciones</p></li>
<li><p>Cuando <span class="math inline">\(X\)</span> tiene muchas dimensiones, resulta un problema de <em>escasez</em> o <em>sparseness</em></p></li>
<li><p>Algunas celdas estarán vacías, o solo tendrán tratados, o solo tendrán no tratados</p></li>
<li><p>Si tenemos unidades no tratadas en cada celda donde hay tratados, <strong>aún podemos estimar el TOT</strong></p>
<ul>
<li><p>Noten que cuando completamos la muestra emparejada en el ejemplo hipotético, siempre encontramos a alguien en el grupo de control para asignárselo a un tratado</p></li>
<li><p>Pero al revés, no siempre es posible: por ejemplo, no hay ningún tratado de 48 años en nuestro ejemplo hipotético</p></li>
</ul></li>
</ul>
</section>
<section id="teorema-del-propensity-score-rosenbaum-y-rubin-1983" class="slide level2">
<h2>Teorema del <em>propensity score</em> (Rosenbaum y Rubin, 1983)</h2>
<ul>
<li><strong>Teorema 1. Inconfundibilidad dado el propensity score</strong>: el <strong>Supuesto 1</strong> implica</li>
</ul>
<p><span class="math display">\[
\{Y(0), Y(1)\} \perp  D|p(X)
\]</span></p>
<p>donde <span class="math inline">\(p(X)=\Pr(D=1|X)\)</span> es la probabilidad de ser tratado dado un conjunto de covariables <span class="math inline">\(X\)</span>, el <em>propensity score</em> o PS</p>
<ul>
<li>El efecto del tratamiento, bajo el supuesto de inconfundibilidad dado el propensity score, es:</li>
</ul>
<p><span class="math display">\[\Delta_{TOT}=E\left(\mu_1(p(X))-\mu_0(p(X))|D=1\right)\]</span></p>
<p>donde <span class="math inline">\(\mu_d(p(X))=E(Y|D=d,p(X))\)</span></p>
</section>
<section id="estimación" class="slide level2">
<h2>Estimación</h2>
<ul>
<li><p>Debemos primero especificar y estimar el PS (probit o logit son los métodos más comunes)</p></li>
<li><p>Se realiza el <em>match</em> de unidades tratadas con unidades que no lo fueron usando el PS</p></li>
<li><p>Se comprueba la calidad del <em>matching</em></p></li>
<li><p>Se estima la diferencia en la variable de resultados entre estos grupos, así como su error estándar</p></li>
</ul>
</section>
<section id="estimación-del-modelo-del-ps" class="slide level2">
<h2>Estimación del modelo del PS</h2>
<ul>
<li><p>Se usa un modelo <em>probit</em> o <em>logit</em></p></li>
<li><p>Se deben seleccionar las características incluidas en el modelo</p></li>
<li><p><strong>Prueba y error</strong>: maximizar la tasa de clasificación de tratamientos y controles usando <span class="math inline">\(\bar{p}\)</span>, la proporción de tratamientos en la muestra</p></li>
<li><p><strong>Significancia estadística</strong>: usar solo las variables estadísticamente significativas, comenzando con un modelo muy básico</p></li>
<li><p><strong>Validación cruzada</strong>: comenzar con un modelo simple y agregar grupos de variables comparando las que reduzcan el error cuadrático promedio</p></li>
</ul>
</section>
<section id="estimación-del-modelo-del-ps-1" class="slide level2">
<h2>Estimación del modelo del PS</h2>
<ul>
<li><p>Las características usadas para calcular el PS no deben haber sido afectadas por el tratamiento</p></li>
<li><p>Idealmente usamos variables <span class="math inline">\(X\)</span> pre-intervención</p></li>
<li><p>Cuando no hay <span class="math inline">\(X\)</span> pre-intervención, a veces se puede obtener el PS con variables post-intervención siempre y cuando estas no hayan sido afectadas por el tratamiento (pocas veces recomendado)</p></li>
</ul>
</section>
<section id="algoritmos-de-matching" class="slide level2">
<h2>Algoritmos de <em>matching</em></h2>
<ul>
<li><p><strong>Vecino más cercano</strong>: a cada individuo del grupo tratado se le asigna el individuo del grupo no tratado con el PS más cercano</p></li>
<li><p><strong><span class="math inline">\(M\)</span> vecinos más cercanos</strong>: a cada individuo del grupo tratado se le asignan los <span class="math inline">\(M\)</span> individuos del grupo no tratado con el PS más cercano (<em>ratio</em> en R define el número de vecinos)</p></li>
<li><p>El método de vecinos más cercanos puede generar malos emparejamientos si los vecinos más cercanos están muy lejos en términos del PS</p></li>
<li><p><strong>Vecino más cercano con caliper</strong>: consiste en definir una vecindad aceptable de matching (el <em>caliper</em>) y elegir solo el vecino más cercano dentro del caliper</p></li>
<li><p><strong><span class="math inline">\(M\)</span> vecinos más cercanos con caliper</strong>: consiste en hacer <em>match</em> con <span class="math inline">\(M\)</span> individuos dentro del <em>caliper</em></p></li>
</ul>
</section>
<section id="algoritmos-de-matching-1" class="slide level2">
<h2>Algoritmos de <em>matching</em></h2>
<ul>
<li><p><strong>Radio</strong>: todos los no tratados dentro del caliper son usados para hacer <em>match</em></p></li>
<li><p><strong>Estratificación</strong>: parte la región de soporte común en bloques de acuerdo al PS, estima el efecto de tratamiento dentro de cada bloque y, posiblemente, agrega los efectos de acuerdo con la distribución del PS</p></li>
<li><p><strong>Kernel</strong>: todas las unidades no tratadas son usadas para hacer <em>match</em>, pesándolas apropiadamente con unos pesos que decaen conforme a la distancia en términos del PS (reduce la varianza, pero incrementa el sesgo)</p></li>
<li><p>Y muchos otros: <strong>genético</strong>, <strong>cardinal</strong>, <strong>óptimo</strong>, <strong>completo</strong>, etc.</p></li>
<li><p>No hay un método claramente superior a todos los demás</p></li>
<li><p>Puede hacerse con reemplazo o sin reemplazo</p></li>
<li><p>Se recomienda mostrar la robustez respecto a las decisiones tomadas</p></li>
</ul>
</section>
<section id="calidad-del-matching" class="slide level2">
<h2>Calidad del <em>matching</em></h2>
<ul>
<li><p>Para estimar el TOT se requiere que se cumpla el soporte común, por lo que se debe verificar el traslape del PS calculado para los tratados y no tratados</p></li>
<li><p>Otro de los teoremas de Rosenbaum y Rubin (1983) implica que</p></li>
</ul>
<p><span class="math display">\[
X \perp  D|p(X)
\]</span></p>
<ul>
<li><p>Esto es, que al controlar por el PS, las variables <span class="math inline">\(X\)</span> no deben proveer información sobre <span class="math inline">\(D\)</span></p></li>
<li><p>Se recomienda también hacer una prueba de estratificación</p>
<ol type="1">
<li><p>Dividir el rango del soporte común en bloques</p></li>
<li><p>Hacer una prueba de medias del PS entre grupos dentro de cada bloque</p></li>
<li><p>Hacer una prueba de medias de cada variable en <span class="math inline">\(X\)</span> entre grupos dentro de cada bloque</p></li>
</ol></li>
</ul>
</section>
<section id="estimación-del-tot-e-inferencia-estadística" class="slide level2">
<h2>Estimación del TOT e inferencia estadística</h2>
<ul>
<li><p>Con la muestra emparejada, procedemos a estimar el efecto del tratamiento y su error estándar</p></li>
<li><p>Existe una gran variedad de formas de proceder, así como de críticas a las formas en que otros lo hacen</p></li>
<li><p>La primera edición de MT usaba métodos de simulación basados en el paquete <em>Zelig</em> (ya descontinuado)</p></li>
<li><p>En CA se propone usar bootstrap para tomar en cuenta la etapa de estimación del PS usando el paquete <em>Matching</em></p></li>
<li><p>Para nuestra práctica, usaremos el paquete <a href="https://kosukeimai.github.io/MatchIt/index.html"><em>MatchIt</em></a>, con un enfoque de regresión o <em>g-computation</em> para estimar los efectos</p></li>
</ul>
</section>
<section id="conclusión-sobre-el-psm" class="slide level2">
<h2>Conclusión sobre el PSM</h2>
<ul>
<li><p>El uso del PSM requiere de supuestos teóricos fuertes</p></li>
<li><p>La implementación implica que las variables en <span class="math inline">\(X\)</span> son aquellas que permiten asumir la inconfundibilidad dado el PS</p></li>
<li><p>Hay una gran cantidad de decisiones en el proceso de estimación</p></li>
<li><p>La crítica más importante es que la mayoría de las veces nos preocupa más la autoselección basada en no observables que en observables</p></li>
<li><p>Pero muchas veces es todo lo que tenemos a la mano</p></li>
<li><p>Hacer análisis de sensibilidad a las distintas decisiones y presentar resultados transparentes</p></li>
</ul>
</section></section>
<section>
<section id="regresión" class="title-slide slide level1 divider center" data-background-color="#9B2247" data-state="nochrome">
<h1>Regresión</h1>

</section>
<section id="regresión-1" class="slide level2">
<h2>Regresión</h2>
<ul>
<li>Dados unos datos observacionales y asumiendo SIC, ¿por qué no usar directamente las herramientas de regresión que ya conocemos para estimar efectos causales?</li>
</ul>
<p><strong>Definiciones</strong></p>
<ul>
<li><strong>Efecto Promedio Condicional del Tratamiento (CATE)</strong>: es el efecto promedio de tratamiento bajo la condición de que los individuos tienen el mismo valor <span class="math inline">\(X=x\)</span></li>
</ul>
<p><span class="math display">\[
\begin{align*}
\Delta_x&amp;=E(Y(1)|X=x)-E(Y(0)|X=x) \\
&amp;=\mu_1(x)-\mu_0(x)
\end{align*}
\]</span></p>
<ul>
<li>Si <em>promediamos</em> el CATE sobre todos los valores de <span class="math inline">\(X=x\)</span>, obtenemos el ATE:</li>
</ul>
<p><span class="math display">\[\Delta_{ATE} = E(\mu_1(X)-\mu_0(X))\]</span></p>
<ul>
<li>Y si nos fijamos solo en el subconjunto de la población que fue tratado, obtenemos el TOT:</li>
</ul>
<p><span class="math display">\[\Delta_{TOT} = E(\mu_1(X)|D=1)-E(\mu_0(X)|D=1)\]</span></p>
</section>
<section id="regresión-lineal" class="slide level2">
<h2>Regresión lineal</h2>
<ul>
<li>Bajo el SIC, podríamos pensar que podemos estimar <span class="math inline">\(\mu_D(X)\)</span> usando una regresión de la forma: <span class="math display">\[\mu_D(X)=\alpha+\beta_DD+\beta_{X_1}X_1+\ldots+\beta_{X_K}X_K\]</span></li>
</ul>
<p><strong>Problemas</strong></p>
<ul>
<li><p><span class="math inline">\(D\)</span> y <span class="math inline">\(X\)</span> están correlacionados, lo cual afecta la varianza de <span class="math inline">\(\hat{\beta}_D\)</span> (tenemos menos información nueva que si <span class="math inline">\(D\)</span> y <span class="math inline">\(X\)</span> fueran independientes)</p></li>
<li><p>El modelo puede estar mal especificado</p>
<ul>
<li>Omitimos términos de grado mayor que uno</li>
<li>Omitimos posibles interacciones entre covariables (<span class="math inline">\(X_1 X_2\)</span>)</li>
<li>Omitimos posibles interacciones entre el tratamiento, las covariables y sus posibles términos de orden mayor que uno</li>
</ul></li>
</ul>
</section>
<section id="regresión-con-interacciones-y-términos-de-orden-alto" class="slide level2">
<h2>Regresión con interacciones y términos de orden alto</h2>
<ul>
<li><p>Pensaríamos que podemos arreglar el segundo problema con <span class="math display">\[
\begin{align*}
\mu_D(X) &amp;= \alpha + \beta_D D + \beta_{X_1}X_1 + \ldots + \beta_{X_K}X_K + \beta_{D,X_1}DX_1 + \ldots + \beta_{D,X_K}DX_K \\
&amp;\quad + \beta_{X_1^2}X_1^2+\ldots+\beta_{X_1,X_2}X_1X_2+\ldots
\end{align*}
\]</span></p></li>
<li><p>Y con los coeficientes estimados podríamos obtener <span class="math inline">\(\hat{\mu}_D(X)\)</span> y calcular</p></li>
</ul>
<p><span class="math display">\[\hat{\Delta}_{ATE}^R=\frac{1}{n}\sum_{i=1}^{n}(\hat{\mu}_1(X_i)-\hat{\mu}_0(X_i))\]</span> <span class="math display">\[\hat{\Delta}_{TOT}^R=\frac{1}{n_1}\sum_{i:D_i=1}(\hat{\mu}_1(X_i)-\hat{\mu}_0(X_i))\]</span></p>
<p><strong>Problemas</strong></p>
<ul>
<li><p>¿Cómo determinar óptimamente el orden de los polinomios y el número de interacciones?</p></li>
<li><p><em>Trade-off</em> sesgo vs varianza</p></li>
</ul>
</section>
<section id="trade-off-sesgo-vs-varianza" class="slide level2 columnas-arriba">
<h2><em>Trade-off</em> sesgo vs varianza</h2>
<ul>
<li>El error cuadrático medio de <span class="math inline">\(\hat{\mu}_d(x)\)</span> como estimador de <span class="math inline">\(\mu_d(x)\)</span> se descompone en dos partes:</li>
</ul>
<p><span class="math display">\[
E\left((\hat{\mu}_d(x)-\mu_d(x))^2\right)=\underbrace{\left(E(\hat{\mu}_d(x))-\mu_d(x)\right)^2}_{\text{Sesgo}^2}+\underbrace{Var(\hat{\mu}_d(x))}_{\text{Varianza}}
\]</span></p>
<div class="columns">
<div class="column" style="width:45%;">
<ul>
<li><p>Un modelo <strong>rígido</strong> (pocos términos) no sigue la forma de <span class="math inline">\(\mu_d(x)\)</span>: sesgo alto y varianza baja</p></li>
<li><p>Un modelo <strong>flexible</strong> (muchos términos) sigue de cerca los datos: sesgo bajo y varianza alta</p></li>
<li><p>Reducir un componente suele aumentar el otro</p></li>
</ul>
</div><div class="column" style="width:55%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="figures/sesgo_varianza-1.png" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="métodos-locales" class="slide level2">
<h2>Métodos locales</h2>
<ul>
<li>Estimamos la media condicional para cada valor de <span class="math inline">\(X=x\)</span> como la media local de observaciones con <span class="math inline">\(X\)</span> cercanos a <span class="math inline">\(x\)</span></li>
</ul>
<p><span class="math display">\[\hat{\mu}_{d,h}(x)=\frac{\sum_{i:D_i=d}\mathcal{K}\left(\frac{X_i-x}{h}\right) Y_i}{\sum_{i:D_i=d}\mathcal{K}\left(\frac{X_i-x}{h}\right)}\]</span></p>
<p>donde <span class="math inline">\(\mathcal{K}(\cdot)\)</span> es la función <em>kernel</em> que otorga pesos más grandes a las observaciones con <span class="math inline">\(\frac{X_i-x}{h}\)</span> cercano a cero y pesos más pequeños (incluso cero) para valores más lejanos de cero, y <span class="math inline">\(h\)</span> es el <em>ancho de banda</em></p>
</section>
<section id="pesos-kernel" class="slide level2">
<h2>Pesos kernel</h2>
<ul>
<li>Algunos ejemplos de pesos kernel son los siguientes, con <span class="math inline">\(u=\frac{X_i-x}{h}\)</span>:</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="lightable-paper lightable-hover caption-top" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Kernel</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">\(\mathcal{K}(u)\)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Uniforme</td>
<td style="text-align: center;">\(\frac{1}{2}\,\mathbb{I}\{\lvert u\rvert\leq 1\}\)</td>
</tr>
<tr class="even">
<td style="text-align: center;">Triangular</td>
<td style="text-align: center;">\((1-\lvert u\rvert)\,\mathbb{I}\{\lvert u\rvert\leq 1\}\)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Epanechnikov</td>
<td style="text-align: center;">\(\frac{3}{4}(1-u^2)\,\mathbb{I}\{\lvert u\rvert\leq 1\}\)</td>
</tr>
<tr class="even">
<td style="text-align: center;">Cuártico (<em>biweight</em>)</td>
<td style="text-align: center;">\(\frac{15}{16}(1-u^2)^2\,\mathbb{I}\{\lvert u\rvert\leq 1\}\)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Gaussiano</td>
<td style="text-align: center;">\(\frac{1}{\sqrt{2\pi}}\exp\left(-\frac{u^2}{2}\right)\)</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="elección-de-h" class="slide level2">
<h2>Elección de <span class="math inline">\(h\)</span></h2>
<ul>
<li>La elección de <span class="math inline">\(h\)</span> es clave en la estimación
<ul>
<li>Un <span class="math inline">\(h\)</span> grande conlleva más sesgo pues se otorga un peso más grande a observaciones con <span class="math inline">\(X_i\)</span> lejano de <span class="math inline">\(x\)</span></li>
<li>Un <span class="math inline">\(h\)</span> pequeño conlleva una mayor varianza pues solo otorga pesos a unas cuantas observaciones<sup>1</sup></li>
</ul></li>
</ul>
<ul>
<li>Se suele escoger un <span class="math inline">\(h_{opt}\)</span> usando un procedimiento de <em>validación cruzada</em> o <em>cross-validation</em></li>
</ul>
<p><span class="math display">\[h_{opt}=\text{arg} \min_{h \in \mathcal{H}} \sum_{i:D_i=d}(Y_i-\hat{\mu}_{d,-i,h}(X_i))^2\]</span></p>
<p>donde <span class="math inline">\(\hat{\mu}_{d,-i,h}(X_i)\)</span> es la media condicional estimada para la observación <span class="math inline">\(i\)</span>, dejando fuera a <span class="math inline">\(i\)</span> y usando el resto de la muestra para la estimación</p>
<aside><ol class="aside-footnotes"><li id="fn3"><p>A este problema se le conoce como <em>sobreajuste</em> u <em>overfitting</em>. La idea es que, con un <span class="math inline">\(h\)</span> muy pequeño, cada media local se calcula con muy pocas observaciones, por lo que <span class="math inline">\(\hat{\mu}\)</span> reproduce el ruido de la muestra con la que se estimó y no la media condicional. En otras palabras, la media condicional ajusta muy bien dentro de la muestra, pero predice mal observaciones nuevas. Por eso la validación cruzada evalúa el error en la observación <span class="math inline">\(i\)</span> que se dejó fuera.</p></li></ol></aside></section>
<section id="elección-de-h-1" class="slide level2">
<h2>Elección de <span class="math inline">\(h\)</span></h2>
<ul>
<li><p>El proceso de validación cruzada consiste en variar <span class="math inline">\(h\)</span> hasta encontrar el valor que minimice la suma de los errores de predicción</p></li>
<li><p>Una vez obtenido <span class="math inline">\(h_{opt}\)</span> calculamos <span class="math inline">\(\hat{\mu}_{d,h_{opt}}(X_i)\)</span></p></li>
<li><p>Esta es una forma comúnmente usada en el trabajo aplicado para estimar medias condicionales</p></li>
</ul>
</section></section>
<section>
<section id="inverse-probability-weighting" class="title-slide slide level1 divider center" data-background-color="#9B2247" data-state="nochrome">
<h1><em>Inverse probability weighting</em></h1>

</section>
<section id="inverse-probability-weighting-ipw" class="slide level2">
<h2><em>Inverse probability weighting (IPW)</em></h2>
<ul>
<li><p>Es otra manera de explotar el PS para estimar el efecto causal, dado que se cumpla el SIC</p></li>
<li><p>La idea es usar el inverso del PS como pesos</p>
<ul>
<li>Las observaciones subrepresentadas en su grupo (tratados con PS bajo, no tratados con PS alto) reciben más peso</li>
<li>Las observaciones sobrerrepresentadas en su grupo (tratados con PS alto, no tratados con PS bajo) reciben menos peso</li>
</ul></li>
<li><p>La intuición es que al repesar las observaciones, los grupos tratado y no tratado son comparables en términos de la distribución de sus <span class="math inline">\(X\)</span></p></li>
</ul>
</section>
<section id="motivación-del-ipw-con-un-experimentosantanna" class="slide level2">
<h2>Motivación del IPW con un experimento<sup>1</sup></h2>
<ul>
<li><p>Pensemos en un experimento simple, donde <span class="math inline">\(\{Y(0),Y(1)\} \perp D\)</span> y solo decidimos la proporción de unidades que serán tratadas</p></li>
<li><p>Estimamos el ATE con la diferencia de medias entre tratados y no tratados, que podemos reescribir como:</p></li>
</ul>
<p><span class="math display">\[
\begin{align*}
\hat{\Delta}_{ATE}^{E}&amp;=\frac{1}{n_1}\sum_{i:D_i=1}Y_i-\frac{1}{n_0}\sum_{i:D_i=0}Y_i \\
&amp;=\frac{\sum_{i=1}^n D_iY_i}{\sum_{j=1}^n D_j}-\frac{\sum_{i=1}^n (1-D_i)Y_i}{\sum_{j=1}^n (1-D_j)} \\
&amp;=\frac{1}{n}\sum_{i=1}^n \frac{D_i}{\hat{p}}Y_i-\frac{1}{n}\sum_{i=1}^n \frac{1-D_i}{1-\hat{p}}Y_i
\end{align*}
\]</span></p>
<p>donde <span class="math inline">\(\hat{p}=\frac{1}{n}\sum_{i=1}^n D_i=\frac{n_1}{n}\)</span> es la proporción de unidades tratadas</p>
<aside><ol class="aside-footnotes"><li id="fn4"><p>Adaptado de <a href="https://psantanna.com/Econ520/Slides/15-ipw/15slides.html#12">Sant’Anna, Econ 520</a></p></li></ol></aside></section>
<section id="motivación-del-ipw-con-un-experimento" class="slide level2">
<h2>Motivación del IPW con un experimento</h2>
<ul>
<li>Es decir, en un experimento simple, el estimador de diferencia de medias del ATE es un promedio ponderado de los resultados:</li>
</ul>
<p><span class="math display">\[
\hat{\Delta}_{ATE}^{E}=\frac{1}{n}\sum_{i=1}^n \left(\frac{D_i}{\hat{p}}-\frac{1-D_i}{1-\hat{p}}\right)Y_i
\]</span></p>
<ul>
<li><p>Los pesos son el inverso del PS, que en este diseño es una constante</p></li>
<li><p>Cada grupo es pesado por el inverso de la probabilidad de pertenecer a ese grupo</p></li>
<li><p>Podemos seguir usando la misma lógica reemplazando <span class="math inline">\(\hat{p}\)</span> por <span class="math inline">\(\hat{p}(X_i)\)</span>, siempre que haya soporte común, <span class="math inline">\(0&lt;p(X)&lt;1\)</span></p></li>
</ul>
</section>
<section id="estimadores-de-ipw" class="slide level2">
<h2>Estimadores de IPW</h2>
<ul>
<li>Bajo esta lógica, dos estimadores de IPW son:</li>
</ul>
<p><span class="math display">\[\hat{\Delta}_{ATE}^{IPW}=\left(\sum_{i=1}^n \frac{Y_i D_i}{\hat{p}(X_i)} / \sum_{i=1}^n \frac{D_i}{\hat{p}(X_i)}\right) - \left(\sum_{i=1}^n \frac{Y_i (1-D_i)}{1-\hat{p}(X_i)} / \sum_{i=1}^n \frac{1-D_i}{1-\hat{p}(X_i)}\right)\]</span></p>
<p><span class="math display">\[\hat{\Delta}_{TOT}^{IPW}=\left(\sum_{i=1}^n Y_i D_i / \sum_{i=1}^n D_i\right) - \left(\sum_{i=1}^n \frac{Y_i (1-D_i)\hat{p}(X_i)}{1-\hat{p}(X_i)} / \sum_{i=1}^n \frac{(1-D_i)\hat{p}(X_i)}{1-\hat{p}(X_i)}\right)\]</span></p>
<ul>
<li>En el TOT, los tratados reciben un peso de uno y los no tratados se pesan por <span class="math inline">\(\frac{\hat{p}(X_i)}{1-\hat{p}(X_i)}\)</span>, de forma que la distribución de sus <span class="math inline">\(X\)</span> se parezca a la de los tratados</li>
</ul>
</section></section>
<section>
<section id="métodos-doblemente-robustos" class="title-slide slide level1 divider center" data-background-color="#9B2247" data-state="nochrome">
<h1>Métodos doblemente robustos</h1>

</section>
<section id="métodos-doblemente-robustos-dr" class="slide level2">
<h2><em>Métodos doblemente robustos (DR)</em></h2>
<ul>
<li><p>Estos métodos consisten en usar lo mejor de los dos mundos vistos anteriormente: estimación de medias condicionales y pesos basados en el PS</p></li>
<li><p>Los parámetros de interés son:</p></li>
</ul>
<p><span class="math display">\[\Delta_{ATE}=E\left(\mu_1(X)-\mu_0(X)+ \frac{(Y-\mu_1(X))D}{p(X)}-\frac{(Y-\mu_0(X))(1-D)}{1-p(X)}\right)\]</span> <span class="math display">\[\Delta_{TOT}=E\left(\frac{(Y-\mu_0(X))D}{\Pr(D=1)}-\frac{(Y-\mu_0(X))(1-D)p(X)}{(1-p(X))\Pr(D=1)}\right)\]</span></p>
<ul>
<li><p>Puede verificarse que, bajo el SIC y el soporte común, estas expresiones son equivalentes a las que definen <span class="math inline">\(\Delta_{ATE}\)</span> y <span class="math inline">\(\Delta_{TOT}\)</span> con medias condicionales (regresión) y con pesos basados en el PS (IPW)</p></li>
<li><p>La ventaja es que basta con que especifiquemos bien el modelo para la media condicional o el modelo del PS para estimar de forma consistente los efectos de tratamiento</p>
<ul>
<li>Regresión requiere que el modelo de la media condicional sea correcto</li>
<li>IPW requiere que el modelo del PS sea correcto</li>
</ul></li>
</ul>
</section>
<section id="estimadores-dr" class="slide level2">
<h2>Estimadores DR</h2>
<ul>
<li><p>Usamos estimadores <em>plug-in</em>, es decir, calculamos cada parte por separado y los <em>conectamos</em><sup>1</sup></p></li>
<li><p>Estimamos <span class="math inline">\(\hat{\mu}_1(X)\)</span> y <span class="math inline">\(\hat{\mu}_0(X)\)</span> con una regresión y <span class="math inline">\(\hat{p}(X)\)</span> con un modelo para el PS</p></li>
<li><p>El estimador DR del ATE es:</p></li>
</ul>
<p><span class="math display">\[
\begin{align*}
\hat{\Delta}_{ATE}^{DR}&amp;=\frac{1}{n}\sum_{i=1}^n\left(\hat{\mu}_1(X_i)+\frac{D_i(Y_i-\hat{\mu}_1(X_i))}{\hat{p}(X_i)}\right) -\frac{1}{n}\sum_{i=1}^n\left(\hat{\mu}_0(X_i)+\frac{(1-D_i)(Y_i-\hat{\mu}_0(X_i))}{1-\hat{p}(X_i)}\right)
\end{align*}
\]</span></p>
<ul>
<li>Y el estimador DR del TOT, usando <span class="math inline">\(\widehat{\Pr}(D=1)=\frac{n_1}{n}\)</span>, es:</li>
</ul>
<p><span class="math display">\[
\hat{\Delta}_{TOT}^{DR}=\frac{1}{n_1}\sum_{i=1}^n\left(D_i-\frac{(1-D_i)\hat{p}(X_i)}{1-\hat{p}(X_i)}\right)(Y_i-\hat{\mu}_0(X_i))
\]</span></p>
<ul>
<li>En el TOT solo necesitamos <span class="math inline">\(\hat{\mu}_0(X)\)</span>, pues el contrafactual que falta es el de los tratados sin tratamiento</li>
</ul>
<aside><ol class="aside-footnotes"><li id="fn5"><p>Adaptado de <a href="https://matheusfacure.github.io/python-causality-handbook/12-Doubly-Robust-Estimation.html">Facure, <em>Causal Inference for the Brave and True</em>, capítulo 12</a></p></li></ol></aside></section>
<section id="inferencia-para-regresión-ipw-y-dr" class="slide level2">
<h2>Inferencia para regresión, IPW y DR</h2>
<ul>
<li><p>Usamos errores robustos en el caso de la estimación paramétrica</p></li>
<li><p>Usamos bootstrap para la estimación local con kernel</p></li>
<li><p>Usamos errores estándar analíticos que toman en cuenta la estimación del PS en el caso de IPW y DR</p></li>
</ul>
</section></section>
<section>
<section id="anexo-1-ejemplos-de-algoritmos-de-matching-basados-en-el-ps" class="title-slide slide level1 divider center" data-background-color="#9B2247" data-state="nochrome">
<h1>Anexo 1: ejemplos de algoritmos de <em>matching</em> basados en el PS</h1>

</section>
<section id="vecino-más-cercano" class="slide level2">
<h2>Vecino más cercano</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="lightable-paper lightable-hover caption-top" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Tratados</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">\(\hat{p}\)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">a</td>
<td style="text-align: center;">0.031</td>
</tr>
<tr class="even">
<td style="text-align: center;">b</td>
<td style="text-align: center;">0.042</td>
</tr>
<tr class="odd">
<td style="text-align: center;">c</td>
<td style="text-align: center;">0.07</td>
</tr>
<tr class="even">
<td style="text-align: center;">\(\vdots\)</td>
<td style="text-align: center;">\(\vdots\)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="lightable-paper lightable-hover caption-top" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">No tratados</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">\(\hat{p}\)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">0.034</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">0.068</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">0.21</td>
</tr>
<tr class="even">
<td style="text-align: center;">\(\vdots\)</td>
<td style="text-align: center;">\(\vdots\)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div></div>
<ul>
<li><p>Con vecino más cercano, el individuo <span class="math inline">\(a\)</span> tratado estaría emparejado con el <span class="math inline">\(A\)</span> no tratado</p></li>
<li><p>Si el emparejamiento es con reemplazo, <span class="math inline">\(A\)</span> podría ser usado otra vez y <span class="math inline">\(b\)</span> también sería emparejado con <span class="math inline">\(A\)</span></p></li>
<li><p>Pero si el emparejamiento es sin reemplazo, <span class="math inline">\(A\)</span> ya no puede ser usado y a <span class="math inline">\(b\)</span> se le emparejaría con <span class="math inline">\(B\)</span></p></li>
<li><p>Cuando hacemos el emparejamiento sin reemplazo, debemos tener una muestra lo suficientemente grande</p></li>
<li><p>El emparejamiento sin reemplazo depende del orden en que se realice el procedimiento</p></li>
</ul>
</section>
<section id="vecino-más-cercano-con-caliper" class="slide level2">
<h2>Vecino más cercano con caliper</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="lightable-paper lightable-hover caption-top" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Tratados</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">\(\hat{p}\)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">a</td>
<td style="text-align: center;">0.031</td>
</tr>
<tr class="even">
<td style="text-align: center;">b</td>
<td style="text-align: center;">0.042</td>
</tr>
<tr class="odd">
<td style="text-align: center;">c</td>
<td style="text-align: center;">0.07</td>
</tr>
<tr class="even">
<td style="text-align: center;">d</td>
<td style="text-align: center;">0.11</td>
</tr>
<tr class="odd">
<td style="text-align: center;">\(\vdots\)</td>
<td style="text-align: center;">\(\vdots\)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="lightable-paper lightable-hover caption-top" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">No tratados</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">\(\hat{p}\)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">0.034</td>
</tr>
<tr class="even">
<td style="text-align: center;">B</td>
<td style="text-align: center;">0.068</td>
</tr>
<tr class="odd">
<td style="text-align: center;">C</td>
<td style="text-align: center;">0.21</td>
</tr>
<tr class="even">
<td style="text-align: center;">D</td>
<td style="text-align: center;">0.40</td>
</tr>
<tr class="odd">
<td style="text-align: center;">\(\vdots\)</td>
<td style="text-align: center;">\(\vdots\)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div></div>
<ul>
<li><p>El primer paso es fijar el caliper, por ejemplo, de 0.1</p></li>
<li><p>El caliper implica buscar al vecino más cercano dentro de una vecindad de 0.1</p></li>
<li><p>En este ejemplo <span class="math inline">\(d\)</span> se emparejaría con <span class="math inline">\(B\)</span> si <span class="math inline">\(B\)</span> aún está disponible (porque no ha sido emparejado con nadie o porque, aunque haya sido emparejado, el procedimiento se hace con reemplazo)</p></li>
<li><p><span class="math inline">\(D\)</span> queda fuera del caliper y nunca se usa</p></li>
</ul>
</section>
<section id="m-vecinos-más-cercanos-con-caliper" class="slide level2">
<h2><span class="math inline">\(M\)</span> vecinos más cercanos con caliper</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="lightable-paper lightable-hover caption-top" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Tratados</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">\(\hat{p}\)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">d</td>
<td style="text-align: center;">0.31</td>
</tr>
<tr class="even">
<td style="text-align: center;">e</td>
<td style="text-align: center;">0.39</td>
</tr>
<tr class="odd">
<td style="text-align: center;">f</td>
<td style="text-align: center;">0.44</td>
</tr>
<tr class="even">
<td style="text-align: center;">g</td>
<td style="text-align: center;">0.52</td>
</tr>
<tr class="odd">
<td style="text-align: center;">h</td>
<td style="text-align: center;">0.55</td>
</tr>
<tr class="even">
<td style="text-align: center;">i</td>
<td style="text-align: center;">0.62</td>
</tr>
<tr class="odd">
<td style="text-align: center;">\(\vdots\)</td>
<td style="text-align: center;">\(\vdots\)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="lightable-paper lightable-hover caption-top" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">No tratados</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">\(\hat{p}\)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">R</td>
<td style="text-align: center;">0.27</td>
</tr>
<tr class="even">
<td style="text-align: center;">S</td>
<td style="text-align: center;">0.29</td>
</tr>
<tr class="odd">
<td style="text-align: center;">T</td>
<td style="text-align: center;">0.33</td>
</tr>
<tr class="even">
<td style="text-align: center;">U</td>
<td style="text-align: center;">0.49</td>
</tr>
<tr class="odd">
<td style="text-align: center;">V</td>
<td style="text-align: center;">0.57</td>
</tr>
<tr class="even">
<td style="text-align: center;">W</td>
<td style="text-align: center;">0.61</td>
</tr>
<tr class="odd">
<td style="text-align: center;">\(\vdots\)</td>
<td style="text-align: center;">\(\vdots\)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div></div>
<ul>
<li><p>Si se utiliza un caliper de 0.1 y dos vecinos, a <span class="math inline">\(g\)</span> se le asignarían <span class="math inline">\(U\)</span> y <span class="math inline">\(V\)</span> (si estuvieran disponibles)</p></li>
<li><p>Es decir, dentro del caliper, los dos individuos con el PS más cercano</p></li>
</ul>
</section>
<section id="radio" class="slide level2">
<h2>Radio</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="lightable-paper lightable-hover caption-top" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Tratados</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">\(\hat{p}\)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">d</td>
<td style="text-align: center;">0.31</td>
</tr>
<tr class="even">
<td style="text-align: center;">e</td>
<td style="text-align: center;">0.39</td>
</tr>
<tr class="odd">
<td style="text-align: center;">f</td>
<td style="text-align: center;">0.44</td>
</tr>
<tr class="even">
<td style="text-align: center;">g</td>
<td style="text-align: center;">0.52</td>
</tr>
<tr class="odd">
<td style="text-align: center;">h</td>
<td style="text-align: center;">0.55</td>
</tr>
<tr class="even">
<td style="text-align: center;">i</td>
<td style="text-align: center;">0.62</td>
</tr>
<tr class="odd">
<td style="text-align: center;">\(\vdots\)</td>
<td style="text-align: center;">\(\vdots\)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="lightable-paper lightable-hover caption-top" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">No tratados</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">\(\hat{p}\)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">R</td>
<td style="text-align: center;">0.27</td>
</tr>
<tr class="even">
<td style="text-align: center;">S</td>
<td style="text-align: center;">0.29</td>
</tr>
<tr class="odd">
<td style="text-align: center;">T</td>
<td style="text-align: center;">0.33</td>
</tr>
<tr class="even">
<td style="text-align: center;">U</td>
<td style="text-align: center;">0.49</td>
</tr>
<tr class="odd">
<td style="text-align: center;">V</td>
<td style="text-align: center;">0.57</td>
</tr>
<tr class="even">
<td style="text-align: center;">W</td>
<td style="text-align: center;">0.61</td>
</tr>
<tr class="odd">
<td style="text-align: center;">\(\vdots\)</td>
<td style="text-align: center;">\(\vdots\)</td>
</tr>
</tbody>
</table>
</div>
</div>
</div></div>
<ul>
<li><p>Pero si ahora implementamos radio con un caliper de 0.1, a <span class="math inline">\(g\)</span> se le asignarían <span class="math inline">\(U\)</span>, <span class="math inline">\(V\)</span> y <span class="math inline">\(W\)</span> (si estuvieran disponibles)</p></li>
<li><p>Es decir, todos los individuos dentro del caliper</p></li>
</ul>
</section>
<section id="kernel" class="slide level2">
<h2>Kernel</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="lightable-paper lightable-hover caption-top" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Tratados</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">\(\hat{p}\)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">d</td>
<td style="text-align: center;">0.31</td>
</tr>
<tr class="even">
<td style="text-align: center;">e</td>
<td style="text-align: center;">0.39</td>
</tr>
<tr class="odd">
<td style="text-align: center;">f</td>
<td style="text-align: center;">0.44</td>
</tr>
<tr class="even">
<td style="text-align: center;">g</td>
<td style="text-align: center;">0.52</td>
</tr>
<tr class="odd">
<td style="text-align: center;">h</td>
<td style="text-align: center;">0.55</td>
</tr>
<tr class="even">
<td style="text-align: center;">i</td>
<td style="text-align: center;">0.62</td>
</tr>
</tbody>
</table>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="lightable-paper lightable-hover caption-top" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">No tratados</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">\(\hat{p}\)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">R</td>
<td style="text-align: center;">0.27</td>
</tr>
<tr class="even">
<td style="text-align: center;">S</td>
<td style="text-align: center;">0.29</td>
</tr>
<tr class="odd">
<td style="text-align: center;">T</td>
<td style="text-align: center;">0.33</td>
</tr>
<tr class="even">
<td style="text-align: center;">U</td>
<td style="text-align: center;">0.49</td>
</tr>
<tr class="odd">
<td style="text-align: center;">V</td>
<td style="text-align: center;">0.57</td>
</tr>
<tr class="even">
<td style="text-align: center;">W</td>
<td style="text-align: center;">0.61</td>
</tr>
</tbody>
</table>
</div>
</div>
</div></div>
<ul>
<li><p>Supongamos que estos son todos nuestros datos</p></li>
<li><p>Con un emparejamiento por kernel, a <span class="math inline">\(d\)</span> lo <em>emparejamos</em> con todos los individuos, desde <span class="math inline">\(R\)</span> hasta <span class="math inline">\(W\)</span></p></li>
<li><p>La función kernel le dará más peso a <span class="math inline">\(T\)</span> y <span class="math inline">\(S\)</span>, un poco menos a <span class="math inline">\(R\)</span> y así hasta darle muy poco o casi nada de peso a <span class="math inline">\(W\)</span></p></li>
</ul>
</section></section>
<section>
<section id="anexo-2-psm-en-r" class="title-slide slide level1 divider center" data-background-color="#9B2247" data-state="nochrome">
<h1>Anexo 2: PSM en R</h1>

</section>
<section id="efecto-de-fumar-en-el-embarazo" class="slide level2">
<h2>Efecto de fumar en el embarazo</h2>
<ul>
<li><p>Datos en <a href="cattaneo_smoking.csv">cattaneo_smoking.csv</a> (Cattaneo, 2010) de una muestra de mujeres que incluye un indicador de si la madre fumó durante el embarazo</p></li>
<li><p>Buscamos estimar el efecto de fumar sobre el peso de los bebés al nacer</p></li>
<li><p>Se incluyen una serie de covariables que usaremos para modelar el PS</p></li>
<li><p>Usaremos los paquetes <em>MatchIt</em> y <em>cobalt</em></p></li>
</ul>
</section>
<section id="matchit-para-realizar-los-emparejamientos" class="slide level2 codigo-grande">
<h2><em>matchit</em> para realizar los emparejamientos</h2>
<ul>
<li><p>Usaremos <em>matchit</em> de la librería <em>MatchIt</em> para hacer el emparejamiento</p></li>
<li><p>Construimos la dummy de tratamiento (<strong>smoke</strong>), una dummy para mujeres casadas (<strong>married</strong>) y una dummy para si el caso en cuestión es el primer bebé (<strong>firstbaby</strong>)</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a aria-label="1"></a>data.smoking<span class="ot">&lt;-</span><span class="fu">read_csv</span>(</span>
<span id="cb21-2"><a aria-label="2"></a>  <span class="st">"./cattaneo_smoking.csv"</span>,</span>
<span id="cb21-3"><a aria-label="3"></a>  <span class="at">locale =</span> <span class="fu">locale</span>(<span class="at">encoding =</span> <span class="st">"latin1"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb21-4"><a aria-label="4"></a>  <span class="fu">clean_names</span>() <span class="sc">|&gt;</span></span>
<span id="cb21-5"><a aria-label="5"></a>  <span class="fu">mutate</span>(<span class="at">smoke=</span><span class="fu">ifelse</span>(mbsmoke<span class="sc">==</span><span class="st">"smoker"</span>,<span class="dv">1</span>,<span class="dv">0</span>)) <span class="sc">|&gt;</span></span>
<span id="cb21-6"><a aria-label="6"></a>  <span class="fu">mutate</span>(<span class="at">married=</span><span class="fu">ifelse</span>(mmarried<span class="sc">==</span><span class="st">"married"</span>,<span class="dv">1</span>,<span class="dv">0</span>)) <span class="sc">|&gt;</span></span>
<span id="cb21-7"><a aria-label="7"></a>  <span class="fu">mutate</span>(<span class="at">firstbaby=</span><span class="fu">ifelse</span>(fbaby<span class="sc">==</span><span class="st">"Yes"</span>,<span class="dv">1</span>,<span class="dv">0</span>))</span>
<span id="cb21-8"><a aria-label="8"></a></span>
<span id="cb21-9"><a aria-label="9"></a><span class="co">#Asegurarse que no hay NA, matchit no acepta NA</span></span>
<span id="cb21-10"><a aria-label="10"></a>data.smoking <span class="ot">&lt;-</span> data.smoking[<span class="fu">complete.cases</span>(data.smoking), ]</span>
<span id="cb21-11"><a aria-label="11"></a></span>
<span id="cb21-12"><a aria-label="12"></a><span class="co">#Una semilla para todo el trabajo</span></span>
<span id="cb21-13"><a aria-label="13"></a><span class="fu">set.seed</span>(<span class="dv">1021</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="comparación-observacional-2" class="slide level2 codigo-grande tabla-compacta">
<h2>Comparación observacional</h2>
<ul>
<li>Si solo comparamos a las mujeres que fuman con las que no fuman, estamos comparando personas muy diferentes</li>
</ul>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a aria-label="1"></a><span class="fu">datasummary_balance</span>(<span class="sc">~</span>smoke,</span>
<span id="cb22-2"><a aria-label="2"></a>                    <span class="at">fmt =</span> <span class="st">"%.2f"</span>,</span>
<span id="cb22-3"><a aria-label="3"></a>                    <span class="at">data =</span> <span class="fu">select</span>(data.smoking, smoke, </span>
<span id="cb22-4"><a aria-label="4"></a>                                  married, firstbaby, </span>
<span id="cb22-5"><a aria-label="5"></a>                                  medu, nprenatal, </span>
<span id="cb22-6"><a aria-label="6"></a>                                  foreign, mhisp, fage),</span>
<span id="cb22-7"><a aria-label="7"></a>                    <span class="at">dinm_statistic =</span> <span class="st">"p.value"</span>,</span>
<span id="cb22-8"><a aria-label="8"></a>                    <span class="at">title =</span> <span class="st">"Pruebas de balance"</span>,</span>
<span id="cb22-9"><a aria-label="9"></a>                    <span class="at">notes =</span> <span class="st">"Fuente: Cattaneo (2010)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_k4cvfx0wguld8hfb9y23 = TinyTable.createTableFunctions("tinytable_k4cvfx0wguld8hfb9y23");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '-1', j: 3 }, { i: '-1', j: 5 } ], css_id: 'tinytable_css_4tbnwr5y4kyrk2iwttum',}, 
          { positions: [ { i: '7', j: 2 }, { i: '7', j: 3 }, { i: '7', j: 4 }, { i: '7', j: 5 }, { i: '7', j: 6 }, { i: '7', j: 7 } ], css_id: 'tinytable_css_2m3zho09ey6pv57wfapv',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '4', j: 4 }, { i: '5', j: 4 }, { i: '6', j: 4 }, { i: '1', j: 5 }, { i: '2', j: 5 }, { i: '3', j: 5 }, { i: '4', j: 5 }, { i: '5', j: 5 }, { i: '6', j: 5 }, { i: '1', j: 6 }, { i: '2', j: 6 }, { i: '3', j: 6 }, { i: '4', j: 6 }, { i: '5', j: 6 }, { i: '6', j: 6 }, { i: '1', j: 7 }, { i: '2', j: 7 }, { i: '3', j: 7 }, { i: '4', j: 7 }, { i: '5', j: 7 }, { i: '6', j: 7 } ], css_id: 'tinytable_css_emlwgm1hdw0vjmuei6po',}, 
          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 }, { i: '0', j: 6 }, { i: '0', j: 7 } ], css_id: 'tinytable_css_i112rfu89fnf0bktih9h',}, 
          { positions: [ { i: '-1', j: 2 }, { i: '-1', j: 4 } ], css_id: 'tinytable_css_9u9ryo3s78a83dxqz378',}, 
          { positions: [ { i: '7', j: 1 } ], css_id: 'tinytable_css_fpzy64i0uix32lp7bnfu',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 } ], css_id: 'tinytable_css_n9ovfft0tpbdiwmj7yyz',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_3n1b0zyrf8t0z0rcdgya',}, 
          { positions: [ { i: '-1', j: 1 }, { i: '-1', j: 6 }, { i: '-1', j: 7 } ], css_id: 'tinytable_css_i11sk95z4prjh1d3o3fi',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_k4cvfx0wguld8hfb9y23.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_4tbnwr5y4kyrk2iwttum, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_4tbnwr5y4kyrk2iwttum {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: black; --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.03em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 3%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_2m3zho09ey6pv57wfapv, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_2m3zho09ey6pv57wfapv {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: right }
    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_emlwgm1hdw0vjmuei6po, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_emlwgm1hdw0vjmuei6po { text-align: right }
    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_i112rfu89fnf0bktih9h, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_i112rfu89fnf0bktih9h {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: right }
    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_9u9ryo3s78a83dxqz378, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_9u9ryo3s78a83dxqz378 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: black; --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.03em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 3%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_fpzy64i0uix32lp7bnfu, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_fpzy64i0uix32lp7bnfu {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_n9ovfft0tpbdiwmj7yyz, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_n9ovfft0tpbdiwmj7yyz { text-align: left }
    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_3n1b0zyrf8t0z0rcdgya, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_3n1b0zyrf8t0z0rcdgya {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_k4cvfx0wguld8hfb9y23 td.tinytable_css_i11sk95z4prjh1d3o3fi, #tinytable_k4cvfx0wguld8hfb9y23 th.tinytable_css_i11sk95z4prjh1d3o3fi {  position: relative; --border-bottom: 0; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_k4cvfx0wguld8hfb9y23" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        <caption>Pruebas de balance</caption>
        <thead>
<tr>
<th scope="col" align="center" colspan="1" data-row="-1" data-col="1"> </th>
<th scope="col" align="center" colspan="2" data-row="-1" data-col="2">0</th>
<th scope="col" align="center" colspan="2" data-row="-1" data-col="4">1</th>
<th scope="col" align="center" colspan="1" data-row="-1" data-col="6"> </th>
<th scope="col" align="center" colspan="1" data-row="-1" data-col="7"> </th>
</tr>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">Mean</th>
                <th scope="col" data-row="0" data-col="3">Std. Dev.</th>
                <th scope="col" data-row="0" data-col="4">Mean</th>
                <th scope="col" data-row="0" data-col="5">Std. Dev.</th>
                <th scope="col" data-row="0" data-col="6">Diff. in Means</th>
                <th scope="col" data-row="0" data-col="7">p</th>
              </tr>
        </thead>
        <tfoot><tr><td colspan="7">Fuente: Cattaneo (2010)</td></tr></tfoot>
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">married</td>
                  <td data-row="1" data-col="2">0.75</td>
                  <td data-row="1" data-col="3">0.43</td>
                  <td data-row="1" data-col="4">0.47</td>
                  <td data-row="1" data-col="5">0.50</td>
                  <td data-row="1" data-col="6">-0.28</td>
                  <td data-row="1" data-col="7">0.00</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1">firstbaby</td>
                  <td data-row="2" data-col="2">0.45</td>
                  <td data-row="2" data-col="3">0.50</td>
                  <td data-row="2" data-col="4">0.37</td>
                  <td data-row="2" data-col="5">0.48</td>
                  <td data-row="2" data-col="6">-0.08</td>
                  <td data-row="2" data-col="7">0.00</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">medu</td>
                  <td data-row="3" data-col="2">12.93</td>
                  <td data-row="3" data-col="3">2.53</td>
                  <td data-row="3" data-col="4">11.64</td>
                  <td data-row="3" data-col="5">2.17</td>
                  <td data-row="3" data-col="6">-1.29</td>
                  <td data-row="3" data-col="7">0.00</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1">nprenatal</td>
                  <td data-row="4" data-col="2">10.96</td>
                  <td data-row="4" data-col="3">3.52</td>
                  <td data-row="4" data-col="4">9.86</td>
                  <td data-row="4" data-col="5">4.21</td>
                  <td data-row="4" data-col="6">-1.10</td>
                  <td data-row="4" data-col="7">0.00</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">foreign</td>
                  <td data-row="5" data-col="2">0.06</td>
                  <td data-row="5" data-col="3">0.24</td>
                  <td data-row="5" data-col="4">0.03</td>
                  <td data-row="5" data-col="5">0.16</td>
                  <td data-row="5" data-col="6">-0.03</td>
                  <td data-row="5" data-col="7">0.00</td>
                </tr>
                <tr>
                  <td data-row="6" data-col="1">mhisp</td>
                  <td data-row="6" data-col="2">0.04</td>
                  <td data-row="6" data-col="3">0.19</td>
                  <td data-row="6" data-col="4">0.02</td>
                  <td data-row="6" data-col="5">0.15</td>
                  <td data-row="6" data-col="6">-0.01</td>
                  <td data-row="6" data-col="7">0.05</td>
                </tr>
                <tr>
                  <td data-row="7" data-col="1">fage</td>
                  <td data-row="7" data-col="2">27.84</td>
                  <td data-row="7" data-col="3">8.79</td>
                  <td data-row="7" data-col="4">24.74</td>
                  <td data-row="7" data-col="5">11.15</td>
                  <td data-row="7" data-col="6">-3.10</td>
                  <td data-row="7" data-col="7">0.00</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div></div>
</section>
<section id="estimación-del-ps" class="slide level2 codigo-grande">
<h2>Estimación del PS</h2>
<ul>
<li>Una manera de hacer más eficiente el uso de las <em>fórmulas</em> es usando <em>as.formula</em></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a aria-label="1"></a>binaria <span class="ot">&lt;-</span> <span class="st">"smoke"</span></span>
<span id="cb23-2"><a aria-label="2"></a>variables <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"married"</span>, <span class="st">"firstbaby"</span>, <span class="st">"medu"</span>, <span class="st">"nprenatal"</span>, <span class="st">"foreign"</span>, <span class="st">"mhisp"</span>, <span class="st">"fage"</span>)</span>
<span id="cb23-3"><a aria-label="3"></a></span>
<span id="cb23-4"><a aria-label="4"></a>ps <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(<span class="fu">paste</span>(binaria, <span class="fu">paste</span>(variables, <span class="at">collapse =</span> <span class="st">"+"</span>), <span class="at">sep =</span> <span class="st">" ~ "</span>))</span>
<span id="cb23-5"><a aria-label="5"></a><span class="fu">print</span>(ps)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>smoke ~ married + firstbaby + medu + nprenatal + foreign + mhisp + 
    fage</code></pre>
</div>
</div>
<ul>
<li>Usamos <em>matchit</em> para estimar el PS y realizar los emparejamientos con el algoritmo que indiquemos:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a aria-label="1"></a>m.out <span class="ot">&lt;-</span> <span class="fu">matchit</span>(<span class="at">formula=</span>ps,</span>
<span id="cb25-2"><a aria-label="2"></a>                 <span class="at">method =</span> <span class="st">"nearest"</span>,</span>
<span id="cb25-3"><a aria-label="3"></a>                 <span class="at">ratio =</span> <span class="dv">1</span>,</span>
<span id="cb25-4"><a aria-label="4"></a>                 <span class="at">distance=</span> <span class="st">"glm"</span>,</span>
<span id="cb25-5"><a aria-label="5"></a>                 <span class="at">link =</span> <span class="st">"logit"</span>,</span>
<span id="cb25-6"><a aria-label="6"></a>                 <span class="at">replace =</span> <span class="cn">FALSE</span>,</span>
<span id="cb25-7"><a aria-label="7"></a>                 <span class="at">estimand =</span> <span class="st">"ATT"</span>,</span>
<span id="cb25-8"><a aria-label="8"></a>                 <span class="at">data =</span> data.smoking)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="estimación-del-ps-1" class="slide level2 codigo-grande salida-scroll">
<h2>Estimación del PS</h2>
<ul>
<li>El resumen del procedimiento da bastante información sobre el <em>matching</em></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a aria-label="1"></a><span class="fu">summary</span>(m.out)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
matchit(formula = ps, data = data.smoking, method = "nearest", 
    distance = "glm", link = "logit", estimand = "ATT", replace = FALSE, 
    ratio = 1)

Summary of Balance for All Data:
          Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean
distance         0.2568        0.1700          0.6673     1.4475    0.2002
married          0.4734        0.7515         -0.5569          .    0.2781
firstbaby        0.3715        0.4531         -0.1689          .    0.0816
medu            11.6389       12.9299         -0.5955     0.7316    0.0717
nprenatal        9.8623       10.9629         -0.2616     1.4301    0.0376
foreign          0.0255        0.0598         -0.2181          .    0.0344
mhisp            0.0243        0.0363         -0.0776          .    0.0120
fage            24.7431       27.8444         -0.2782     1.6070    0.0468
          eCDF Max
distance    0.3329
married     0.2781
firstbaby   0.0816
medu        0.2549
nprenatal   0.1259
foreign     0.0344
mhisp       0.0120
fage        0.1377

Summary of Balance for Matched Data:
          Means Treated Means Control Std. Mean Diff. Var. Ratio eCDF Mean
distance         0.2568        0.2564          0.0033     1.0110    0.0005
married          0.4734        0.4769         -0.0070          .    0.0035
firstbaby        0.3715        0.3981         -0.0551          .    0.0266
medu            11.6389       11.6019          0.0171     0.7064    0.0161
nprenatal        9.8623        9.8588          0.0008     1.1543    0.0059
foreign          0.0255        0.0174          0.0514          .    0.0081
mhisp            0.0243        0.0231          0.0075          .    0.0012
fage            24.7431       24.5799          0.0146     1.0787    0.0124
          eCDF Max Std. Pair Dist.
distance    0.0093          0.0046
married     0.0035          0.2202
firstbaby   0.0266          0.4575
medu        0.0417          0.5168
nprenatal   0.0185          0.7039
foreign     0.0081          0.2425
mhisp       0.0012          0.2781
fage        0.0556          0.6457

Sample Sizes:
          Control Treated
All          3778     864
Matched       864     864
Unmatched    2914       0
Discarded       0       0</code></pre>
</div>
</div>
</section>
<section id="verificación-del-balance" class="slide level2 codigo-grande columnas-arriba">
<h2>Verificación del balance</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>Gráfico de nube:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a aria-label="1"></a><span class="fu">plot</span>(m.out, <span class="at">type =</span> <span class="st">"jitter"</span>, <span class="at">interactive =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="figures/unnamed-chunk-30-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<p>Histograma:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a aria-label="1"></a><span class="fu">plot</span>(m.out, <span class="at">type =</span> <span class="st">"hist"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="figures/unnamed-chunk-31-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="muestra-emparejada-3" class="slide level2 codigo-grande">
<h2>Muestra emparejada</h2>
<ul>
<li>Podemos guardar un objeto con la muestra emparejada usando <em>match.data</em> y observar quién hace match con quién</li>
</ul>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a aria-label="1"></a>m.data <span class="ot">&lt;-</span> <span class="fu">match.data</span>(m.out)</span>
<span id="cb30-2"><a aria-label="2"></a></span>
<span id="cb30-3"><a aria-label="3"></a><span class="fu">head</span>(m.out<span class="sc">$</span>match.matrix)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output cell-output-stdout">
<pre><code>   [,1]  
11 "4130"
20 "2234"
25 "1740"
43 "2857"
47 "305" 
49 "1442"</code></pre>
</div>
</div></div>
</section>
<section id="calidad-del-matching-1" class="slide level2">
<h2>Calidad del <em>matching</em></h2>
<ul>
<li><p>Se sugiere evaluar las diferencias promedio estandarizadas (SMD) entre los grupos tratados y no tratados, antes y después del emparejamiento</p></li>
<li><p>Para el TOT, <em>matchit</em> divide entre la desviación estándar del grupo tratado, <span class="math inline">\(S_T\)</span></p></li>
</ul>
<p><span class="math display">\[SMD_X=\frac{\bar{X}_T-\bar{X}_{NT}}{S_T}\]</span></p>
<ul>
<li>También se sugiere calcular la razón de varianzas (VR). Se espera que este ratio no sea muy distinto de 1 después de hacer el emparejamiento</li>
</ul>
<p><span class="math display">\[VR=\frac{S^2_T}{S^2_{NT}}\]</span></p>
<ul>
<li><strong>Regla de dedo</strong>: una diferencia de 0.1 o menos en el SMD se considera un buen balance. Por ejemplo, la escolaridad de la madre tenía un SMD de -0.5955 en la muestra en bruto, pero con el emparejamiento el SMD se vuelve de solo 0.0171</li>
</ul>
</section>
<section id="loveplot" class="slide level2 codigo-grande">
<h2><em>Loveplot</em></h2>
<ul>
<li>Usando la librería <em>cobalt</em> podemos construir un <em>love plot</em> que representa gráficamente las diferencias antes y después del emparejamiento</li>
</ul>
<div class="cell columns column-output-location">
<div class="column">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a aria-label="1"></a><span class="fu">love.plot</span>(<span class="fu">bal.tab</span>(m.out),</span>
<span id="cb32-2"><a aria-label="2"></a>          <span class="at">threshold =</span> .<span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div><div class="column">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="figures/unnamed-chunk-33-1.png" width="960"></p>
</figure>
</div>
</div>
</div></div>
</section>
<section id="efecto-de-tratamiento" class="slide level2 codigo-grande">
<h2>Efecto de tratamiento</h2>
<ul>
<li><p>Han existido muchas maneras de explotar la muestra emparejada. Aquí usamos <em>g-computation</em></p></li>
<li><p>Una buena guía sobre la estimación de los efectos está en la documentación de <a href="https://kosukeimai.github.io/MatchIt/articles/estimating-effects.html">MatchIt</a></p></li>
<li><p>Estimamos un modelo para la variable dependiente dado el tratamiento y, opcionalmente, las covariables, usando la muestra emparejada</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a aria-label="1"></a>tt1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(bweight <span class="sc">~</span> smoke,</span>
<span id="cb33-2"><a aria-label="2"></a>          <span class="at">data =</span> m.data,</span>
<span id="cb33-3"><a aria-label="3"></a>          <span class="at">weights =</span> weights)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="efecto-de-tratamiento-1" class="slide level2 codigo-grande">
<h2>Efecto de tratamiento</h2>
<ul>
<li><p>Usamos <code>marginaleffects::avg_comparisons()</code> para estimar el TOT</p></li>
<li><p><em>vcov</em> indica que se estimen errores agrupados a nivel pareja, que es lo apropiado cuando el emparejamiento es sin reemplazo (<a href="https://doi.org/10.1080/01621459.2020.1840383">Abadie &amp; Spiess, 2022</a>)</p></li>
<li><p><em>newdata</em> indica que se genere un nuevo objeto de datos con solo las unidades tratadas para estimar el TOT</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a aria-label="1"></a>tot.psm <span class="ot">&lt;-</span> marginaleffects<span class="sc">::</span><span class="fu">avg_comparisons</span>(tt1,</span>
<span id="cb34-2"><a aria-label="2"></a>                <span class="at">variables =</span> <span class="st">"smoke"</span>,</span>
<span id="cb34-3"><a aria-label="3"></a>                <span class="at">vcov =</span> <span class="sc">~</span>subclass,</span>
<span id="cb34-4"><a aria-label="4"></a>                <span class="at">newdata =</span> <span class="fu">subset</span>(smoke <span class="sc">==</span> <span class="dv">1</span>))</span>
<span id="cb34-5"><a aria-label="5"></a>tot.psm</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Estimate Std. Error     z Pr(&gt;|z|)    S 2.5 % 97.5 %
     -194       28.1 -6.91   &lt;0.001 37.6  -249   -139

Term: smoke
Type: response
Comparison: 1 - 0</code></pre>
</div>
</div>
</section>
<section id="efecto-de-tratamiento-2" class="slide level2 codigo-grande">
<h2>Efecto de tratamiento</h2>
<p>Algunos autores incluyen las covariables en su estimación:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a aria-label="1"></a>tt2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(bweight <span class="sc">~</span> smoke<span class="sc">*</span>(married <span class="sc">+</span> firstbaby <span class="sc">+</span> medu <span class="sc">+</span> nprenatal <span class="sc">+</span> foreign <span class="sc">+</span> mhisp <span class="sc">+</span> fage),</span>
<span id="cb36-2"><a aria-label="2"></a>          <span class="at">data =</span> m.data,</span>
<span id="cb36-3"><a aria-label="3"></a>          <span class="at">weights =</span> weights)</span>
<span id="cb36-4"><a aria-label="4"></a></span>
<span id="cb36-5"><a aria-label="5"></a><span class="co">#Errores agrupados a nivel subclass</span></span>
<span id="cb36-6"><a aria-label="6"></a>marginaleffects<span class="sc">::</span><span class="fu">avg_comparisons</span>(tt2,</span>
<span id="cb36-7"><a aria-label="7"></a>                <span class="at">variables =</span> <span class="st">"smoke"</span>,</span>
<span id="cb36-8"><a aria-label="8"></a>                <span class="at">vcov =</span> <span class="sc">~</span>subclass,</span>
<span id="cb36-9"><a aria-label="9"></a>                <span class="at">newdata =</span> <span class="fu">subset</span>(smoke <span class="sc">==</span> <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Estimate Std. Error    z Pr(&gt;|z|)    S 2.5 % 97.5 %
     -197       27.7 -7.1   &lt;0.001 39.5  -251   -143

Term: smoke
Type: response
Comparison: 1 - 0</code></pre>
</div>
</div>
</section></section>
<section>
<section id="anexo-3-regresión-ipw-y-dr-en-r" class="title-slide slide level1 divider center" data-background-color="#9B2247" data-state="nochrome">
<h1>Anexo 3: regresión, IPW y DR en R</h1>

</section>
<section id="regresión-ipw-y-dr-fumar-durante-el-embarazo" class="slide level2">
<h2>Regresión, IPW y DR: fumar durante el embarazo</h2>
<ul>
<li><p>Comparamos los distintos métodos para estimar el TOT con los datos de Cattaneo (2010)</p></li>
<li><p><span class="math inline">\(D\)</span> es <strong>smoke</strong>, <span class="math inline">\(Y\)</span> es <strong>bweight</strong> y <span class="math inline">\(X\)</span> son las mismas siete covariables que usamos para estimar el PS</p></li>
<li><p>Veremos cuatro estimadores:</p>
<ul>
<li>Regresión paramétrica, con <em>lm</em> y <em>avg_comparisons</em> del paquete <em>marginaleffects</em></li>
<li>Regresión kernel, con <em>npreg</em> del paquete <em>np</em> y solo tres de las covariables</li>
<li>IPW, con <em>PSweight</em> del paquete <em>PSweight</em></li>
<li>DR, también con <em>PSweight</em></li>
</ul></li>
<li><p>En IPW y DR el PS se estima con el mismo logit que en el PSM, guardado en la fórmula <strong>ps</strong></p></li>
</ul>
</section>
<section id="regresión-paramétrica" class="slide level2 codigo-grande">
<h2>Regresión paramétrica</h2>
<ul>
<li><p>Estimamos una regresión con interacciones entre <span class="math inline">\(D\)</span> y todas las covariables</p></li>
<li><p><em>avg_comparisons</em>, del paquete <em>marginaleffects</em>, promedia <span class="math inline">\(\hat{\mu}_1(X_i)-\hat{\mu}_0(X_i)\)</span> sobre los tratados, que es <span class="math inline">\(\hat{\Delta}_{TOT}^R\)</span>:</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a aria-label="1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb38-2"><a aria-label="2"></a></span>
<span id="cb38-3"><a aria-label="3"></a><span class="co"># Regresión con interacciones entre D y X</span></span>
<span id="cb38-4"><a aria-label="4"></a>ols <span class="ot">&lt;-</span> <span class="fu">lm</span>(bweight <span class="sc">~</span> smoke <span class="sc">*</span> (married <span class="sc">+</span> firstbaby <span class="sc">+</span> medu <span class="sc">+</span> nprenatal <span class="sc">+</span></span>
<span id="cb38-5"><a aria-label="5"></a>                               foreign <span class="sc">+</span> mhisp <span class="sc">+</span> fage),</span>
<span id="cb38-6"><a aria-label="6"></a>                               <span class="at">data =</span> data.smoking)</span>
<span id="cb38-7"><a aria-label="7"></a></span>
<span id="cb38-8"><a aria-label="8"></a><span class="co"># Promedio de las diferencias predichas en la muestra de tratados</span></span>
<span id="cb38-9"><a aria-label="9"></a>tot.reg <span class="ot">&lt;-</span> <span class="fu">avg_comparisons</span>(ols, <span class="at">variables =</span> <span class="st">"smoke"</span>, <span class="at">vcov =</span> <span class="st">"HC1"</span>,</span>
<span id="cb38-10"><a aria-label="10"></a>                           <span class="at">newdata =</span> <span class="fu">filter</span>(data.smoking, smoke <span class="sc">==</span> <span class="dv">1</span>))</span>
<span id="cb38-11"><a aria-label="11"></a><span class="fu">c</span>(<span class="at">efecto =</span> tot.reg<span class="sc">$</span>estimate, <span class="at">ee =</span> tot.reg<span class="sc">$</span>std.error)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    efecto         ee 
-212.35668   22.56909 </code></pre>
</div>
</div>
</section>
<section id="regresión-kernel" class="slide level2 codigo-grande">
<h2>Regresión kernel</h2>
<ul>
<li>Con siete covariables, la media local sufre de la maldición de la dimensionalidad, por lo que usamos solo tres: <strong>married</strong>, <strong>fage</strong> y <strong>nprenatal</strong></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a aria-label="1"></a><span class="fu">library</span>(np)</span>
<span id="cb40-2"><a aria-label="2"></a></span>
<span id="cb40-3"><a aria-label="3"></a>tratados <span class="ot">&lt;-</span> <span class="fu">filter</span>(data.smoking, smoke <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb40-4"><a aria-label="4"></a>notratados <span class="ot">&lt;-</span> <span class="fu">filter</span>(data.smoking, smoke <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb40-5"><a aria-label="5"></a></span>
<span id="cb40-6"><a aria-label="6"></a><span class="co"># h óptimo de cada covariable por validación cruzada, solo con los no tratados</span></span>
<span id="cb40-7"><a aria-label="7"></a>bw <span class="ot">&lt;-</span> <span class="fu">npregbw</span>(bweight <span class="sc">~</span> married <span class="sc">+</span> fage <span class="sc">+</span> nprenatal, <span class="at">data =</span> notratados,</span>
<span id="cb40-8"><a aria-label="8"></a>              <span class="at">regtype =</span> <span class="st">"lc"</span>, <span class="at">bwmethod =</span> <span class="st">"cv.ls"</span>, <span class="at">ckertype =</span> <span class="st">"epanechnikov"</span>)</span>
<span id="cb40-9"><a aria-label="9"></a></span>
<span id="cb40-10"><a aria-label="10"></a><span class="co"># Media local de los no tratados, evaluada en las X de cada tratado</span></span>
<span id="cb40-11"><a aria-label="11"></a>mu0 <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="fu">npreg</span>(bw), <span class="at">newdata =</span> tratados)</span>
<span id="cb40-12"><a aria-label="12"></a><span class="fu">mean</span>(tratados<span class="sc">$</span>bweight <span class="sc">-</span> mu0)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -207.2631</code></pre>
</div>
</div>
</section>
<section id="regresión-kernel-1" class="slide level2 columnas-arriba">
<h2>Regresión kernel</h2>
<div class="columns">
<div class="column" style="width:45%;">
<ul>
<li><p><em>regtype = “lc”</em>: es la media local constante; con varias covariables, el peso es el producto de los kernels de cada una</p></li>
<li><p><em>bwmethod = “cv.ls”</em>: es la validación cruzada que deja fuera a cada observación</p></li>
<li><p>Hay un <span class="math inline">\(h_{opt}\)</span> por covariable: 0.47 para <strong>married</strong>, 27.3 para <strong>fage</strong> y 1.46 para <strong>nprenatal</strong></p></li>
<li><p><span class="math inline">\(\hat{\mu}_0\)</span> se estima solo con los no tratados y da el contrafactual de cada tratado</p></li>
<li><p>El TOT estimado es de -207.3 gramos</p></li>
<li><p>Obtenemos el error estándar usando bootstrap</p></li>
</ul>
</div><div class="column" style="width:55%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="figures/kernel_mu0-1.png" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="regresión-kernel-inferencia" class="slide level2 codigo-grande">
<h2>Regresión kernel: inferencia</h2>
<ul>
<li><em>boot</em>, del paquete <em>boot</em>, repite el estimador en cada muestra bootstrap, manteniendo fijos los <span class="math inline">\(h_{opt}\)</span></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a aria-label="1"></a><span class="fu">library</span>(boot)</span>
<span id="cb42-2"><a aria-label="2"></a></span>
<span id="cb42-3"><a aria-label="3"></a>covs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"married"</span>, <span class="st">"fage"</span>, <span class="st">"nprenatal"</span>)</span>
<span id="cb42-4"><a aria-label="4"></a></span>
<span id="cb42-5"><a aria-label="5"></a>bs <span class="ot">&lt;-</span> <span class="cf">function</span>(data, indices) {</span>
<span id="cb42-6"><a aria-label="6"></a>  dat <span class="ot">&lt;-</span> data[indices, ]                 <span class="co"># muestra bootstrap</span></span>
<span id="cb42-7"><a aria-label="7"></a>  tr <span class="ot">&lt;-</span> <span class="fu">filter</span>(dat, smoke <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb42-8"><a aria-label="8"></a>  nt <span class="ot">&lt;-</span> <span class="fu">filter</span>(dat, smoke <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb42-9"><a aria-label="9"></a>  mu0 <span class="ot">&lt;-</span> <span class="fu">npreg</span>(<span class="at">bws =</span> bw<span class="sc">$</span>bw, <span class="at">txdat =</span> nt[, covs], <span class="at">tydat =</span> nt<span class="sc">$</span>bweight,</span>
<span id="cb42-10"><a aria-label="10"></a>               <span class="at">exdat =</span> tr[, covs], <span class="at">regtype =</span> <span class="st">"lc"</span>, <span class="at">ckertype =</span> <span class="st">"epanechnikov"</span>)<span class="sc">$</span>mean</span>
<span id="cb42-11"><a aria-label="11"></a>  <span class="fu">mean</span>(tr<span class="sc">$</span>bweight <span class="sc">-</span> mu0)                 <span class="co"># TOT en la muestra bootstrap</span></span>
<span id="cb42-12"><a aria-label="12"></a>}</span>
<span id="cb42-13"><a aria-label="13"></a></span>
<span id="cb42-14"><a aria-label="14"></a><span class="fu">set.seed</span>(<span class="dv">1021</span>)</span>
<span id="cb42-15"><a aria-label="15"></a>boot.kernel <span class="ot">&lt;-</span> <span class="fu">boot</span>(<span class="at">data =</span> data.smoking, <span class="at">statistic =</span> bs, <span class="at">R =</span> <span class="dv">499</span>)</span>
<span id="cb42-16"><a aria-label="16"></a><span class="fu">c</span>(<span class="at">efecto =</span> boot.kernel<span class="sc">$</span>t0, <span class="at">ee =</span> <span class="fu">sd</span>(boot.kernel<span class="sc">$</span>t))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    efecto         ee 
-207.26309   21.38315 </code></pre>
</div>
</div>
</section>
<section id="ipw" class="slide level2 codigo-grande">
<h2>IPW</h2>
<ul>
<li><em>weight = “treated”</em> pide los pesos del TOT (1 para los tratados y <span class="math inline">\(\frac{\hat{p}(X_i)}{1-\hat{p}(X_i)}\)</span> para los no tratados)</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a aria-label="1"></a><span class="fu">library</span>(PSweight)</span>
<span id="cb44-2"><a aria-label="2"></a></span>
<span id="cb44-3"><a aria-label="3"></a>ipw <span class="ot">&lt;-</span> <span class="fu">PSweight</span>(<span class="at">ps.formula =</span> ps,</span>
<span id="cb44-4"><a aria-label="4"></a>                <span class="at">yname =</span> <span class="st">"bweight"</span>,</span>
<span id="cb44-5"><a aria-label="5"></a>                <span class="at">data =</span> <span class="fu">as.data.frame</span>(data.smoking),</span>
<span id="cb44-6"><a aria-label="6"></a>                <span class="at">weight =</span> <span class="st">"treated"</span>)</span>
<span id="cb44-7"><a aria-label="7"></a></span>
<span id="cb44-8"><a aria-label="8"></a><span class="fu">summary</span>(ipw)<span class="sc">$</span>estimates</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std.Error   z value       lwr       upr Pr(&gt;|z|)
Contrast 1 -212.8243  23.34637 -9.115947 -258.5824 -167.0663        0</code></pre>
</div>
</div>
</section>
<section id="dr" class="slide level2 codigo-grande">
<h2>DR</h2>
<ul>
<li>Agregamos un modelo para <span class="math inline">\(Y\)</span> (<em>out.formula</em>) y pedimos el estimador aumentado (<em>augmentation = TRUE</em>)</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a aria-label="1"></a>resultado <span class="ot">&lt;-</span> <span class="fu">as.formula</span>(<span class="fu">paste</span>(<span class="st">"bweight"</span>,</span>
<span id="cb46-2"><a aria-label="2"></a>                              <span class="fu">paste</span>(variables, <span class="at">collapse =</span> <span class="st">"+"</span>),</span>
<span id="cb46-3"><a aria-label="3"></a>                              <span class="at">sep =</span> <span class="st">" ~ "</span>))</span>
<span id="cb46-4"><a aria-label="4"></a></span>
<span id="cb46-5"><a aria-label="5"></a>dr <span class="ot">&lt;-</span> <span class="fu">PSweight</span>(<span class="at">ps.formula =</span> ps,</span>
<span id="cb46-6"><a aria-label="6"></a>               <span class="at">yname =</span> <span class="st">"bweight"</span>,</span>
<span id="cb46-7"><a aria-label="7"></a>               <span class="at">data =</span> <span class="fu">as.data.frame</span>(data.smoking),</span>
<span id="cb46-8"><a aria-label="8"></a>               <span class="at">weight =</span> <span class="st">"treated"</span>,</span>
<span id="cb46-9"><a aria-label="9"></a>               <span class="at">augmentation =</span> <span class="cn">TRUE</span>,</span>
<span id="cb46-10"><a aria-label="10"></a>               <span class="at">out.formula =</span> resultado)</span>
<span id="cb46-11"><a aria-label="11"></a></span>
<span id="cb46-12"><a aria-label="12"></a><span class="fu">summary</span>(dr)<span class="sc">$</span>estimates</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate Std.Error   z value       lwr       upr Pr(&gt;|z|)
Contrast 1 -218.2062  23.19071 -9.409207 -263.6592 -172.7532        0</code></pre>
</div>
</div>
</section>
<section id="comparación-entre-métodos" class="slide level2">
<h2>Comparación entre métodos</h2>
<div class="cell">
<div class="cell-output-display">
<table class="lightable-paper lightable-hover caption-top" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Método</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Efecto en el peso al nacer (gramos)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Error estándar</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Diferencia simple de medias</td>
<td style="text-align: center;">-275.3</td>
<td style="text-align: center;">21.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">PSM (vecino más cercano, sin reemplazo)</td>
<td style="text-align: center;">-194.3</td>
<td style="text-align: center;">28.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Regresión paramétrica</td>
<td style="text-align: center;">-212.4</td>
<td style="text-align: center;">22.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Regresión kernel (tres covariables)</td>
<td style="text-align: center;">-207.3</td>
<td style="text-align: center;">21.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IPW</td>
<td style="text-align: center;">-212.8</td>
<td style="text-align: center;">23.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">DR</td>
<td style="text-align: center;">-218.2</td>
<td style="text-align: center;">23.2</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li><p>Todos los métodos estiman el TOT con las mismas covariables, salvo la regresión kernel, que usa tres: fumar durante el embarazo reduce el peso al nacer en alrededor de 200 gramos</p></li>
<li><p>La diferencia simple de medias exagera el efecto, pues las madres que fuman difieren de las que no fuman en características que también afectan el peso al nacer</p></li>
<li><p>Todos descansan en el SIC: si hay selección en no observables, ninguno la corrige</p></li>
</ul>
</section></section>
<section id="selección-por-observables-2" class="title-slide slide level1 final center" data-background-color="#9B2247" data-state="nochrome">
<h1>Selección por Observables</h1>
<div class="f-eyebrow">
<p>Inferencia Causal</p>
</div>
<div class="f-inst">
<p><a href="https://rojasirvin.github.io/">Irvin Rojas</a></p>
</div>
<div class="f-inst">
<p>CIDE · Maestría en Economía</p>
</div>
<p><span class="f-icons"><a href="https://github.com/rojasirvin" target="_blank" aria-label="GitHub"><i class="bi bi-github"></i></a> <a href="https://scholar.google.com/citations?hl=es&amp;user=FUwdSTMAAAAJ&amp;view_op=list_works&amp;sortby=pubdate" target="_blank" aria-label="Google Scholar"><i class="bi bi-mortarboard-fill"></i></a> <a href="mailto:irvin.rojas@cide.edu" aria-label="Correo"><i class="bi bi-envelope-fill"></i></a></span></p>
<div class="f-rule">

</div>
<div class="f-copy">
<p>© 2026 Irvin Rojas. Distribuido bajo licencia Creative Commons <strong>CC BY-NC-SA 4.0</strong>. Los materiales de terceros citados conservan sus propios derechos.</p>
</div>


</section>


    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="logo-CIDE.jpg" class="slide-logo"></p>
<div class="footer footer-default">
<p>Inferencia Causal · Selección por Observables</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/rojasirvin\.github\.io\/inferencia-causal\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>