{
  "hash": "011696afe241b70a718e0c6cef972947",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat:\n  revealjs:\n    theme: [\"./theme-ic.scss\"]\n    width: 1600\n    height: 900\n    slide-number: c/t\n    center: false\n    scrollable: false\n    title-slide: false\n    logo: logo-CIDE.jpg\n    footer: \"Inferencia Causal · Selección por Observables\"\n    include-in-header:\n      - _ic-header.html\n      - fontawesome.html\n---\n\n\n\n\n\n\n# Selección por Observables {.portada background-color=\"#163D34\" data-state=\"nochrome\"}\n\n::: {.pa-eyebrow}\nInferencia Causal\n:::\n\n[Irvin Rojas]{.pa-name} <span class=\"pa-icons\"><a href=\"https://github.com/rojasirvin\" target=\"_blank\" aria-label=\"GitHub\"><i class=\"bi bi-github\"></i></a> <a href=\"https://scholar.google.com/citations?hl=es&user=FUwdSTMAAAAJ&view_op=list_works&sortby=pubdate\" target=\"_blank\" aria-label=\"Google Scholar\"><i class=\"bi bi-mortarboard-fill\"></i></a> <a href=\"mailto:irvin.rojas@cide.edu\" aria-label=\"Correo\"><i class=\"bi bi-envelope-fill\"></i></a></span>\n\n::: {.pa-inst}\nCentro de Investigación y Docencia Económicas<br>Maestría en Economía\n:::\n\n::: {.cell}\n<style type=\"text/css\">\n.huge .remark-code { /*Change made here*/\n  font-size: 200% !important;\n}\n.tiny .remark-code { /*Change made here*/\n  font-size: 60% !important;\n}\n/* Láminas con código y salida de R más grandes que el .7em del tema; mismo\n   tamaño en todas, con interlineado y márgenes más compactos para que quepan */\n.reveal .codigo-grande div.sourceCode pre code.sourceCode { font-size: 1.3em !important; line-height: 1.4; }\n.reveal .codigo-grande .cell-output pre code { font-size: 1.3em; line-height: 1.25; padding: .45em 1.1em; }\n.reveal .codigo-grande pre, .reveal .codigo-grande div.sourceCode { margin: .25em 0 .45em; }\n/* El tema centra verticalmente las columnas; aquí arrancan al mismo nivel */\n.reveal .columnas-arriba .columns { align-items: flex-start; }\n/* El tema limita los scroll_box a 560px; esta lámina solo tiene la tabla */\n.reveal .tabla-alta div[style*=\"overflow-y\"] { max-height: 770px !important; }\n</style>\n:::\n\n\n# Selección por Observables {.divider background-color=\"#9B2247\" data-state=\"nochrome\"}\n\n\n## Motivación\n\n- Hemos estudiado la conveniencia de los experimentos para revelar relaciones causales\n\n- También hemos destacado las limitaciones de los diseños experimentales\n\n- Algunos métodos nos permiten usar datos observacionales y supuestos estadísticos para estimar relaciones causales en ausencia de variación experimental\n\n- Los métodos basados en selección en observables dieron origen a una literatura extensa en economía en la década de los 2000, sin embargo, su aplicación actual como método de inferencia principal es muy limitada\n\n- En cambio, los fundamentos de los métodos basados en observables son piezas clave en métodos modernos de inferencia causal que usan *machine learning* o los conocidos como *estimadores doblemente robustos*\n\n\n## Organización de lo que cubriremos en el curso\n\n1. Supuesto de independencia condicional\n1. Métodos de *matching*\n   - *Matching* basado en covariables\n   - *Propensity score matching*\n1. Otros métodos basados en el SIC\n   - Regresión\n   - *Inverse probability weighting*\n   - Métodos doblemente robustos\n\n\n\n## Recordatorio del sesgo de selección\n \n- Las razones que determinan la asignación del tratamiento determinan también el valor de $Y$\n\n- Una comparación observacional nos da el efecto del tratamiento más el sesgo de selección:\n\n$$\n\\begin{aligned}\nE(Y|D=1)-E(Y|D=0)=&\\overbrace{ E(Y(1)|D=1)-E(Y(0)|D=1)}^{\\Delta_{TOT}\\text{: efecto promedio en los tratados}}+\\\\& \\underbrace{E(Y(0)|D=1)-E(Y(0)|D=0)}_{\\text{Sesgo de selección}}\n\\end{aligned}\n$$\n\n- Una forma de eliminar el sesgo de selección es mediante la asignación aleatoria del tratamiento\n\n- Esto no siempre es posible, por lo que recurrimos a supuestos estadísticos\n \n\n\n## Supuesto de independencia condicional\n\n- **Supuesto 1. Independencia condicional (SIC)**: condicional en una serie de características $X$, los resultados potenciales son independientes del tratamiento\n\n$$\\{Y(0),Y(1)\\}\\perp D | X$$\n\n- El SIC también se conoce como inconfundibilidad, ignorabilidad del tratamiento o *unconfoundedness*\n\n\n## Supuesto de independencia condicional\n\n- El SIC dice que al *controlar* por una serie de características $X$, el tratamiento es *como* si fuera aleatorio:\n\n$$\nE(Y(1)|D=1,X)=E(Y(1)|D=0,X)\n$$\n\n$$\nE(Y(0)|D=1,X)=E(Y(0)|D=0,X)\n$$\n\n- Los valores esperados de $Y(1)$ y $Y(0)$ son iguales cuando nos fijamos en cada valor de $X$\n\n\n## Ejemplo: ir a la universidad\n\n- Supongamos que $D$ es ir o no a la universidad y la variable de interés es el ingreso\n\n- Sabemos que la comparación estará contaminada por el sesgo de selección\n\n- Es posible que aquellos que fueron a la universidad de todos modos hubieran tenido un mayor salario, incluso sin haber ido a la universidad, por lo que el sesgo de selección es positivo\n\n- El SIC implica que si hacemos la comparación condicional en $X$, el sesgo de selección desaparece\n\n$$\nE(Y|D=1,X)-E(Y|D=0,X)=E(Y(1)-Y(0)|X)\n$$\n\n- Es decir, que si comparamos a personas con y sin tratamiento, con los $X$ *fijos*, el sesgo de selección desaparece\n\n- *Mantener fijas* las $X$ es el análogo a obtener el promedio del salario en cada nivel de escolaridad en la gráfica de la FEC\n\n\n## Ejemplo: ir a la universidad\n\n- Para generalizar el concepto cuando la variable tiene más de dos valores (como con la educación $S$), escribamos $Y(s)$ para el ingreso potencial con $s$ años de educación\n\n- Esta función nos dice cuál sería el ingreso de un individuo bajo todos los posibles niveles de $s$\n\n- En este caso, asumimos el SIC, que se traduce en: \n$$Y(s)\\perp S | X\\quad \\forall\\quad s$$\n\n- En diseños experimentales, descansamos en el supuesto de independencia de los resultados potenciales con respecto al estatus de tratamiento\n\n- Pero con datos *observacionales*, el SIC significa que $S$ es *casi como si fuera asignado de manera aleatoria* cuando condicionamos en $X$\n\n## Ejemplo: ir a la universidad\n\n- En los datos solo observamos $Y=Y(S)$\n\n- Dado el SIC, podemos hacer comparaciones de ingreso promedio para distintos niveles de educación:\n\n$$E(Y|S=s,X)-E(Y|S=s-1,X)=E(Y(s)-Y(s-1)|X)$$\n\n- Notemos que lo impráctico de esto es que tendríamos que hacer comparaciones en pares y luego tratar de hacer un promedio ponderado por el número de individuos en cada nivel de educación\n\n\n## Regresión para hacer las comparaciones\n\n- Supongamos una función causal para el ingreso\n\n$$Y(s)=\\alpha+\\rho s+\\nu$$\n\nque indica lo que un individuo ganaría para todo valor de $s$ (y no solo el valor realizado $S$)\n\n- La única parte aleatoria es el error con media cero $\\nu$, que captura los factores no observados que afectan los ingresos\n\n- Sustituyendo el valor observado:\n\n$$Y=\\alpha+\\rho S+\\nu$$\n\n- $S$ puede estar correlacionado con los resultados potenciales $Y(s)$, es decir, correlacionado con el error $\\nu$\n\n\n## Regresión para hacer las comparaciones\n\n- Supongamos que el SIC se cumple dado un vector $X$\n\n- Descompongamos el error en una función lineal de las características $X$ y un error $u$:\n\n$$\\nu=X'\\gamma+u$$\n\ndonde se asume que $E(\\nu|X)=X'\\gamma$ y donde $u$ y $X$ no están correlacionados\n\n- Si se cumple el SIC, entonces:\n\n$$\n\\begin{aligned}\nE(Y(s)|X,S)=E(Y(s)|X)&=\\alpha+\\rho s+E(\\nu|X) \\\\\n&=\\alpha+\\rho s + X'\\gamma\n\\end{aligned}\n$$\n\n- Es decir, en el modelo de regresión causal $Y=\\alpha+\\rho S+ X'\\gamma+u$, $u$ no está correlacionado con los regresores $X$ y $S$\n\n- $\\rho$ es el efecto causal de interés\n\n- El supuesto clave es que la única razón por la cual $\\nu$ y $S$ están correlacionados es $X$\n\n## Supuesto de soporte común\n\n- **Supuesto 2. Soporte común**: para cualquier combinación de covariables en la población, existen individuos tratados y no tratados\n\n$$0<p(X)<1$$\n\ndonde $p(X)=\\Pr(D=1|X)$ es la probabilidad condicional de recibir el tratamiento o *propensity score (PS)*\n\n- El soporte común descarta que haya covariables que predigan determinísticamente la asignación de tratamiento\n\n\n## Supuestos de identificación del TOT\n \n- Cuando se cumple **Supuesto 1** $+$ **Supuesto 2**  se conoce como **ignorabilidad fuerte**\n  \n- Heckman, Ichimura y Todd (1998) muestran que estas condiciones son demasiado estrictas si nos interesa estimar solo el TOT\n  \n- Para identificar el TOT es suficiente:\n    \n- **Supuesto 1a. Inconfundibilidad en el control**\n\n$$\nY(0) \\perp  D | X\n$$\n\n- **Supuesto 2a. Traslape débil**\n\n$$\np(X) < 1\n$$\n\n\n\n# Matching exacto {.divider background-color=\"#9B2247\" data-state=\"nochrome\"}\n\n## Matching exacto\n \n- Un estimador de matching exacto consiste en *emparejar* individuos tratados y no tratados para cada valor específico de las $X$ y estimar un promedio ponderado de las diferencias\n  \n- Tenemos datos observacionales de individuos que recibieron y no recibieron un tratamiento y tenemos una serie de características $X$\n\n- Bajo el SIC, podemos eliminar el sesgo de selección al estimar las diferencias de $Y$ dentro de grupos con las mismas $X$\n\n- Requerimos que existan observaciones tratadas y no tratadas para todas las características $X$\n\n\n## Ejemplo: programa hipotético de empleo\n\n- Usemos [el ejemplo](https://mixtape.scunning.com/matching-and-subclassification.html?panelset=r-code) en The Mixtape (MT):\n\n\n::: {.cell}\n\n:::\n\n\n## Ejemplo: programa hipotético de empleo {.codigo-grande .columnas-arriba}\n\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n- Los individuos tratados:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 3\n   unit_treat age_treat earnings_treat\n        <dbl>     <dbl>          <dbl>\n 1          1        18           9500\n 2          2        29          12250\n 3          3        24          11000\n 4          4        27          11750\n 5          5        33          13250\n 6          6        22          10500\n 7          7        19           9750\n 8          8        20          10000\n 9          9        21          10250\n10         10        30          12500\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n- Mientras que los no tratados:\n  \n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 3\n   unit_control age_control earnings_control\n          <dbl>       <dbl>            <dbl>\n 1            1          20             8500\n 2            2          27            10075\n 3            3          21             8725\n 4            4          39            12775\n 5            5          38            12550\n 6            6          29            10525\n 7            7          39            12775\n 8            8          33            11425\n 9            9          24             9400\n10           10          30            10750\n11           11          33            11425\n12           12          36            12100\n13           13          22             8950\n14           14          18             8050\n15           15          43            13675\n16           16          39            12775\n17           17          19             8275\n18           18          30             9000\n19           19          51            15475\n20           20          48            14800\n```\n\n\n:::\n:::\n\n:::\n\n::::\n\n\n\n\n\n\n\n## Comparación observacional {.codigo-grande}\n\n- Si hiciéramos diferencias simples obtendríamos:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(data.treat$earnings_treat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11075\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(data.control$earnings_control)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11101.25\n```\n\n\n:::\n\n```{.r .cell-code}\n#Diferencia\nmean(data.treat$earnings_treat) - mean(data.control$earnings_control)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -26.25\n```\n\n\n:::\n:::\n\n\n- Parece que en el grupo de control ganan más (efecto de tratamiento negativo)\n\n## Comparación observacional {.codigo-grande}\n\n- El principal problema con esta diferencia es que sabemos que los ingresos crecen con la edad\n\n- La muestra de no tratados tiene mayor edad promedio:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(data.treat$age_treat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24.3\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(data.control$age_control)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 31.95\n```\n\n\n:::\n\n```{.r .cell-code}\n#Diferencia\nmean(data.treat$age_treat) - mean(data.control$age_control)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -7.65\n```\n\n\n:::\n:::\n\n\n- Estamos *confundiendo* el efecto de la edad\n\n\n## Muestra emparejada\n\n- Construyamos la muestra emparejada buscando, para cada individuo en el grupo tratado, uno en el de control que tenga la misma edad. Cuando le encontramos un individuo no tratado al tratado con la misma edad decimos que esa pareja hizo *match*\n\n- Por ejemplo, la primera unidad tratada, con 18 años y un ingreso de 9,500 estaría emparejada con la unidad 14 del grupo de control, que tiene también 18 años y un ingreso de 8,050\n\n- Para dicho individuo de 18 años, su ingreso contrafactual sería 8,050\n\n- Cuando hay varias unidades en el grupo de control que pueden ser empatadas con la de tratamiento, podemos construir el ingreso contrafactual calculando el promedio\n\n- Del grupo de control, los individuos 10 y 18 tienen 30 años, con ingresos 10,750 y 9,000, por lo que usamos el promedio (9,875) para crear el contrafactual del individuo tratado de 30 años de la fila 10\n\n## Muestra emparejada {.codigo-grande}\n\n- La muestra emparejada o contrafactual será:\n\n\n::: {.cell output-location='column'}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 3\n   unit_matched age_matched earnings_matched\n          <dbl>       <dbl>            <dbl>\n 1            1          18             8050\n 2            2          29            10525\n 3            3          24             9400\n 4            4          27            10075\n 5            5          33            11425\n 6            6          22             8950\n 7            7          19             8275\n 8            8          20             8500\n 9            9          21             8725\n10           10          30             9875\n```\n\n\n:::\n:::\n\n\n## Muestra emparejada {.codigo-grande}\n\n- Noten que la edad es la misma entre los tratados y la muestra emparejada:\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n- Muestra de tratados:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(data.treat$age_treat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24.3\n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n- Muestra emparejada:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(data.matched$age_matched)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24.3\n```\n\n\n:::\n:::\n\n:::\n\n::::\n\n\n- En este caso, decimos que la edad *está balanceada*\n\n- Y entonces podemos calcular el efecto de tratamiento como la diferencia de ingresos entre los tratados y los no tratados en la muestra emparejada:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1695\n```\n\n\n:::\n:::\n\n\n- En este caso, encontramos un efecto positivo del programa de 1,695 unidades monetarias.\n\n## Estimador de matching exacto\n\n- Podemos definir un **estimador de matching exacto** del TOT basado en una sola característica como:\n\n$$\\hat{\\Delta}_{TOT}=\\frac{1}{n_1}\\sum_{i:D_i=1}\\left(Y_i-\\frac{1}{M_i}\\sum_{m=1}^{M_i}Y_{j_m(i)}\\right)$$\n\ndonde $n_1$ es el número de tratados, $M_i$ es el número de no tratados con $X_j=X_i$ y $j_m(i)$ es el $m$-ésimo de ellos\n\n## Importancia del soporte común\n\n- Observemos lo que ocurre con la distribución de edades en ambos grupos:\n\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\nPara los tratados:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](figures/grafica_tratados-1.png){width=960}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n- Mientras que para los no tratados:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](figures/grafica_notratados-1.png){width=960}\n:::\n:::\n\n:::\n\n::::\n\n- El supuesto de traslape débil para identificar el TOT significa que para cada unidad tratada, hay al menos un no tratado\n\n\n\n## Estimador de matching exacto del ATE\n\n- Hasta aquí, solo hemos imputado el contrafactual para cada unidad en el grupo tratado\n\n- Si podemos imputar también, para cada unidad no tratada, su correspondiente contrafactual tratado, podemos estimar el ATE\n\n- Y un **estimador de matching exacto** del ATE sería:\n\n\n$$\\hat{\\Delta}=\\frac{1}{n}\\sum_{i=1}^{n}(2D_i-1)\\left(Y_i-\\frac{1}{M_i}\\sum_{m=1}^{M_i}Y_{j_m(i)}\\right)$$\n\ndonde ahora $j_m(i)$ recorre las $M_i$ unidades del grupo *opuesto* al de $i$ con $X_j=X_i$\n\n- Casi todas las aplicaciones de *matching* se enfocan en el TOT\n\n## *Matching* con más de una característica\n\n- En general, tenemos varias características en $X$\n\n- Pensamos en $X$ más como una *celda* de individuos que comparten las mismas características\n\n- Tenemos que tener una regla para definir la distancia mínima entre dos vectores de covariables $X_i$ y $X_j$\n\n- Un **estimador de vecino más cercano** es:\n\n$$\\hat{\\Delta}_{TOT}=\\frac{1}{n_1}\\sum_{i:D_i=1}\\left(Y_i-\\sum_{j:D_j=0}\\mathbb{I}\\left\\{||X_j-X_i||=\\min_{l:D_l=0}||X_l-X_i||\\right\\} Y_j\\right)$$\n\n## Decisiones en el *matching*\n\n- ¿Realizar el *matching* con o sin reemplazo?[^1]\n\n[^1]: La discusión en *Causal Analysis (CA)* asume *matching con reemplazo*. \n\n- Sin reemplazo:\n  - Reduce la varianza en la estimación al usar un grupo no tratado más grande en lugar de reusar observaciones\n  - Incrementa el sesgo pues algunos *matches* no podrán hacerse dado que algunas observaciones no tratadas ya han sido descartadas\n\n- ¿Cómo medir la distancia entre las covariables?\n  - Euclidiana: $||X_j-X_i||_{Euclidiana}=\\sqrt{\\sum_{k=1}^{K}(X_{jk}-X_{ik})^2}$\n  - Varianza: $||X_j-X_i||_{Varianza}=\\sqrt{\\sum_{k=1}^{K}\\frac{(X_{jk}-X_{ik})^2}{\\hat{Var}(X_k)}}$\n  - Mahalanobis: $||X_j-X_i||_{Mahalanobis}=\\sqrt{(X_j-X_i)'\\hat{\\Sigma}_X^{-1}(X_j-X_i)}$, con $\\hat{\\Sigma}_X$ la matriz de varianzas y covarianzas de $X$\n\n## Decisiones en el *matching*\n\n- ¿Cómo estimar la varianza?\n  - Bootstrap no funciona (Abadie & Imbens, 2008)\n  - Usar fórmulas analíticas (ver CA)\n\n\n\n\n\n\n\n\n\n\n\n## Ejemplo: veteranos del ejército de Estados Unidos\n\n- Angrist (1998)[^angrist] estudia el efecto del servicio militar sobre los ingresos (inscribirse en el ejército tiene un claro componente de autoselección)\n\n[^angrist]: [Estimating the Labor Market Impact of Voluntary Military Service Using Social Security Data on Military Applicants](https://www.jstor.org/stable/2998558).\n\n- El autor tiene datos $X$: raza, año de solicitud de ingreso al ejército, escolaridad, calificación en examen de aptitud, año de nacimiento\n  \n- Estas características definen *celdas* y dentro de cada celda tenemos tratados y no tratados\n\n- Se estiman los efectos usando distintas metodologías\n\n- Los impactos estimados usando el matching exacto se encuentran bajo la columna *Contraste controlado*\n\n## Ejemplo: veteranos del ejército de Estados Unidos {.tabla-alta}\n\n\n::: {.cell warnings='false'}\n`````{=html}\n<div style=\"border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:700px; \"><table class=\" lightable-paper lightable-hover\" style='font-family: \"Arial Narrow\", arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;border-bottom: 0;'>\n <thead>\n<tr><th style=\"padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important;position: sticky; top:0; background-color: #FFFFFF;\" colspan=\"9\"><div style=\"TRUE\">Estimaciones alternativas del efecto del servicio militar en los ingresos</div></th></tr>\n<tr>\n<th style=\"empty-cells: hide;position: sticky; top:0; background-color: #FFFFFF;\" colspan=\"1\"></th>\n<th style=\"padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important;position: sticky; top:0; background-color: #FFFFFF;\" colspan=\"4\"><div style=\"TRUE\">Blancos</div></th>\n<th style=\"padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; font-weight: bold; padding-right: 4px; padding-left: 4px; background-color: white !important;position: sticky; top:0; background-color: #FFFFFF;\" colspan=\"4\"><div style=\"TRUE\">No blancos</div></th>\n</tr>\n  <tr>\n   <th style=\"text-align:left;color: white !important;background-color: rgba(155, 34, 71, 255) !important;position: sticky; top:0; background-color: #FFFFFF;\"> Año </th>\n   <th style=\"text-align:center;color: white !important;background-color: rgba(155, 34, 71, 255) !important;position: sticky; top:0; background-color: #FFFFFF;\"> Media<br>(1) </th>\n   <th style=\"text-align:center;color: white !important;background-color: rgba(155, 34, 71, 255) !important;position: sticky; top:0; background-color: #FFFFFF;\"> Diferencia de medias<br>(2) </th>\n   <th style=\"text-align:center;color: white !important;background-color: rgba(155, 34, 71, 255) !important;position: sticky; top:0; background-color: #FFFFFF;\"> Contraste controlado<br>(3) </th>\n   <th style=\"text-align:center;color: white !important;background-color: rgba(155, 34, 71, 255) !important;position: sticky; top:0; background-color: #FFFFFF;\"> Regresión<br>(4) </th>\n   <th style=\"text-align:center;color: white !important;background-color: rgba(155, 34, 71, 255) !important;position: sticky; top:0; background-color: #FFFFFF;\"> Media<br>(5) </th>\n   <th style=\"text-align:center;color: white !important;background-color: rgba(155, 34, 71, 255) !important;position: sticky; top:0; background-color: #FFFFFF;\"> Diferencia de medias<br>(6) </th>\n   <th style=\"text-align:center;color: white !important;background-color: rgba(155, 34, 71, 255) !important;position: sticky; top:0; background-color: #FFFFFF;\"> Contraste controlado<br>(7) </th>\n   <th style=\"text-align:center;color: white !important;background-color: rgba(155, 34, 71, 255) !important;position: sticky; top:0; background-color: #FFFFFF;\"> Regresión<br>(8) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 74 </td>\n   <td style=\"text-align:center;\"> 182.7 </td>\n   <td style=\"text-align:center;\"> -26.1 </td>\n   <td style=\"text-align:center;\"> -14.0 </td>\n   <td style=\"text-align:center;\"> -13.0 </td>\n   <td style=\"text-align:center;\"> 157.2 </td>\n   <td style=\"text-align:center;\"> -4.9 </td>\n   <td style=\"text-align:center;\"> -2.0 </td>\n   <td style=\"text-align:center;\"> -3.9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (7.0) </td>\n   <td style=\"text-align:center;\"> (9.2) </td>\n   <td style=\"text-align:center;\"> (9.4) </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (4.4) </td>\n   <td style=\"text-align:center;\"> (6.0) </td>\n   <td style=\"text-align:center;\"> (5.8) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 75 </td>\n   <td style=\"text-align:center;\"> 237.9 </td>\n   <td style=\"text-align:center;\"> -41.4 </td>\n   <td style=\"text-align:center;\"> -14.2 </td>\n   <td style=\"text-align:center;\"> -12.0 </td>\n   <td style=\"text-align:center;\"> 216.9 </td>\n   <td style=\"text-align:center;\"> -0.6 </td>\n   <td style=\"text-align:center;\"> -17.1 </td>\n   <td style=\"text-align:center;\"> -15.2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (6.3) </td>\n   <td style=\"text-align:center;\"> (7.6) </td>\n   <td style=\"text-align:center;\"> (7.8) </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (4.5) </td>\n   <td style=\"text-align:center;\"> (6.0) </td>\n   <td style=\"text-align:center;\"> (5.5) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 76 </td>\n   <td style=\"text-align:center;\"> 473.4 </td>\n   <td style=\"text-align:center;\"> -47.9 </td>\n   <td style=\"text-align:center;\"> -14.8 </td>\n   <td style=\"text-align:center;\"> -12.7 </td>\n   <td style=\"text-align:center;\"> 413.6 </td>\n   <td style=\"text-align:center;\"> -14.5 </td>\n   <td style=\"text-align:center;\"> -33.3 </td>\n   <td style=\"text-align:center;\"> -30.2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (8.1) </td>\n   <td style=\"text-align:center;\"> (9.0) </td>\n   <td style=\"text-align:center;\"> (9.3) </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (6.4) </td>\n   <td style=\"text-align:center;\"> (8.0) </td>\n   <td style=\"text-align:center;\"> (7.4) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 77 </td>\n   <td style=\"text-align:center;\"> 1012.9 </td>\n   <td style=\"text-align:center;\"> -7.1 </td>\n   <td style=\"text-align:center;\"> -8.6 </td>\n   <td style=\"text-align:center;\"> -9.4 </td>\n   <td style=\"text-align:center;\"> 820.9 </td>\n   <td style=\"text-align:center;\"> -13.0 </td>\n   <td style=\"text-align:center;\"> -56.0 </td>\n   <td style=\"text-align:center;\"> -51.3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (11.3) </td>\n   <td style=\"text-align:center;\"> (12.3) </td>\n   <td style=\"text-align:center;\"> (12.2) </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (9.1) </td>\n   <td style=\"text-align:center;\"> (11.1) </td>\n   <td style=\"text-align:center;\"> (10.0) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 78 </td>\n   <td style=\"text-align:center;\"> 2147.1 </td>\n   <td style=\"text-align:center;\"> 40.3 </td>\n   <td style=\"text-align:center;\"> -23.5 </td>\n   <td style=\"text-align:center;\"> -22.4 </td>\n   <td style=\"text-align:center;\"> 1677.9 </td>\n   <td style=\"text-align:center;\"> 58.1 </td>\n   <td style=\"text-align:center;\"> -53.6 </td>\n   <td style=\"text-align:center;\"> -42.5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (16.7) </td>\n   <td style=\"text-align:center;\"> (18.1) </td>\n   <td style=\"text-align:center;\"> (17.2) </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (13.4) </td>\n   <td style=\"text-align:center;\"> (16.1) </td>\n   <td style=\"text-align:center;\"> (14.1) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 79 </td>\n   <td style=\"text-align:center;\"> 3560.7 </td>\n   <td style=\"text-align:center;\"> 188.0 </td>\n   <td style=\"text-align:center;\"> -8.4 </td>\n   <td style=\"text-align:center;\"> -11.2 </td>\n   <td style=\"text-align:center;\"> 2797.0 </td>\n   <td style=\"text-align:center;\"> 340.3 </td>\n   <td style=\"text-align:center;\"> 119.1 </td>\n   <td style=\"text-align:center;\"> 122.3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (21.0) </td>\n   <td style=\"text-align:center;\"> (23.2) </td>\n   <td style=\"text-align:center;\"> (21.6) </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (16.2) </td>\n   <td style=\"text-align:center;\"> (20.1) </td>\n   <td style=\"text-align:center;\"> (17.2) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 80 </td>\n   <td style=\"text-align:center;\"> 4709.0 </td>\n   <td style=\"text-align:center;\"> 572.9 </td>\n   <td style=\"text-align:center;\"> 178.0 </td>\n   <td style=\"text-align:center;\"> 175.9 </td>\n   <td style=\"text-align:center;\"> 3932.2 </td>\n   <td style=\"text-align:center;\"> 1154.3 </td>\n   <td style=\"text-align:center;\"> 741.6 </td>\n   <td style=\"text-align:center;\"> 738.5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (23.4) </td>\n   <td style=\"text-align:center;\"> (27.2) </td>\n   <td style=\"text-align:center;\"> (24.6) </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (18.0) </td>\n   <td style=\"text-align:center;\"> (23.4) </td>\n   <td style=\"text-align:center;\"> (19.5) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 81 </td>\n   <td style=\"text-align:center;\"> 6226.0 </td>\n   <td style=\"text-align:center;\"> 855.5 </td>\n   <td style=\"text-align:center;\"> 249.5 </td>\n   <td style=\"text-align:center;\"> 249.9 </td>\n   <td style=\"text-align:center;\"> 5218.8 </td>\n   <td style=\"text-align:center;\"> 1920.0 </td>\n   <td style=\"text-align:center;\"> 1299.9 </td>\n   <td style=\"text-align:center;\"> 1318.5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (27.2) </td>\n   <td style=\"text-align:center;\"> (32.4) </td>\n   <td style=\"text-align:center;\"> (29.1) </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (20.7) </td>\n   <td style=\"text-align:center;\"> (28.2) </td>\n   <td style=\"text-align:center;\"> (23.1) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 82 </td>\n   <td style=\"text-align:center;\"> 7200.6 </td>\n   <td style=\"text-align:center;\"> 1508.5 </td>\n   <td style=\"text-align:center;\"> 783.3 </td>\n   <td style=\"text-align:center;\"> 782.4 </td>\n   <td style=\"text-align:center;\"> 6150.2 </td>\n   <td style=\"text-align:center;\"> 2917.1 </td>\n   <td style=\"text-align:center;\"> 2186.0 </td>\n   <td style=\"text-align:center;\"> 2210.1 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (30.3) </td>\n   <td style=\"text-align:center;\"> (36.4) </td>\n   <td style=\"text-align:center;\"> (32.5) </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (23.4) </td>\n   <td style=\"text-align:center;\"> (32.0) </td>\n   <td style=\"text-align:center;\"> (26.0) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 83 </td>\n   <td style=\"text-align:center;\"> 8398.1 </td>\n   <td style=\"text-align:center;\"> 1390.5 </td>\n   <td style=\"text-align:center;\"> 588.8 </td>\n   <td style=\"text-align:center;\"> 601.5 </td>\n   <td style=\"text-align:center;\"> 7221.1 </td>\n   <td style=\"text-align:center;\"> 2889.9 </td>\n   <td style=\"text-align:center;\"> 2103.8 </td>\n   <td style=\"text-align:center;\"> 2142.3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (34.4) </td>\n   <td style=\"text-align:center;\"> (41.1) </td>\n   <td style=\"text-align:center;\"> (36.6) </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (27.0) </td>\n   <td style=\"text-align:center;\"> (36.7) </td>\n   <td style=\"text-align:center;\"> (29.8) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 84 </td>\n   <td style=\"text-align:center;\"> 9874.2 </td>\n   <td style=\"text-align:center;\"> 652.8 </td>\n   <td style=\"text-align:center;\"> -235.7 </td>\n   <td style=\"text-align:center;\"> -198.5 </td>\n   <td style=\"text-align:center;\"> 8377.2 </td>\n   <td style=\"text-align:center;\"> 2202.9 </td>\n   <td style=\"text-align:center;\"> 1333.0 </td>\n   <td style=\"text-align:center;\"> 1428.9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (39.5) </td>\n   <td style=\"text-align:center;\"> (46.9) </td>\n   <td style=\"text-align:center;\"> (41.7) </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (30.5) </td>\n   <td style=\"text-align:center;\"> (41.4) </td>\n   <td style=\"text-align:center;\"> (33.4) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 85 </td>\n   <td style=\"text-align:center;\"> 10972.7 </td>\n   <td style=\"text-align:center;\"> 469.8 </td>\n   <td style=\"text-align:center;\"> -521.3 </td>\n   <td style=\"text-align:center;\"> -459.6 </td>\n   <td style=\"text-align:center;\"> 9306.8 </td>\n   <td style=\"text-align:center;\"> 1955.5 </td>\n   <td style=\"text-align:center;\"> 932.3 </td>\n   <td style=\"text-align:center;\"> 1059.2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (44.6) </td>\n   <td style=\"text-align:center;\"> (52.6) </td>\n   <td style=\"text-align:center;\"> (46.8) </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (34.4) </td>\n   <td style=\"text-align:center;\"> (46.2) </td>\n   <td style=\"text-align:center;\"> (37.3) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 86 </td>\n   <td style=\"text-align:center;\"> 12004.5 </td>\n   <td style=\"text-align:center;\"> 543.7 </td>\n   <td style=\"text-align:center;\"> -557.3 </td>\n   <td style=\"text-align:center;\"> -491.7 </td>\n   <td style=\"text-align:center;\"> 10106.2 </td>\n   <td style=\"text-align:center;\"> 1881.3 </td>\n   <td style=\"text-align:center;\"> 720.9 </td>\n   <td style=\"text-align:center;\"> 872.3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (50.4) </td>\n   <td style=\"text-align:center;\"> (59.0) </td>\n   <td style=\"text-align:center;\"> (52.5) </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (38.7) </td>\n   <td style=\"text-align:center;\"> (51.2) </td>\n   <td style=\"text-align:center;\"> (41.6) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 87 </td>\n   <td style=\"text-align:center;\"> 13045.7 </td>\n   <td style=\"text-align:center;\"> 663.9 </td>\n   <td style=\"text-align:center;\"> -548.0 </td>\n   <td style=\"text-align:center;\"> -464.3 </td>\n   <td style=\"text-align:center;\"> 10833.0 </td>\n   <td style=\"text-align:center;\"> 2050.1 </td>\n   <td style=\"text-align:center;\"> 751.0 </td>\n   <td style=\"text-align:center;\"> 925.0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (54.6) </td>\n   <td style=\"text-align:center;\"> (63.9) </td>\n   <td style=\"text-align:center;\"> (56.8) </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (41.8) </td>\n   <td style=\"text-align:center;\"> (55.2) </td>\n   <td style=\"text-align:center;\"> (44.8) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 88 </td>\n   <td style=\"text-align:center;\"> 14136.1 </td>\n   <td style=\"text-align:center;\"> 904.3 </td>\n   <td style=\"text-align:center;\"> -415.5 </td>\n   <td style=\"text-align:center;\"> -311.7 </td>\n   <td style=\"text-align:center;\"> 11480.1 </td>\n   <td style=\"text-align:center;\"> 2175.0 </td>\n   <td style=\"text-align:center;\"> 708.2 </td>\n   <td style=\"text-align:center;\"> 923.7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (58.3) </td>\n   <td style=\"text-align:center;\"> (68.2) </td>\n   <td style=\"text-align:center;\"> (60.6) </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (44.9) </td>\n   <td style=\"text-align:center;\"> (59.5) </td>\n   <td style=\"text-align:center;\"> (48.1) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 89 </td>\n   <td style=\"text-align:center;\"> 14716.1 </td>\n   <td style=\"text-align:center;\"> 1169.1 </td>\n   <td style=\"text-align:center;\"> -248.6 </td>\n   <td style=\"text-align:center;\"> -136.3 </td>\n   <td style=\"text-align:center;\"> 11751.4 </td>\n   <td style=\"text-align:center;\"> 2379.1 </td>\n   <td style=\"text-align:center;\"> 799.7 </td>\n   <td style=\"text-align:center;\"> 1031.9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (61.0) </td>\n   <td style=\"text-align:center;\"> (71.2) </td>\n   <td style=\"text-align:center;\"> (63.2) </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (47.6) </td>\n   <td style=\"text-align:center;\"> (62.7) </td>\n   <td style=\"text-align:center;\"> (50.9) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 90 </td>\n   <td style=\"text-align:center;\"> 14886.1 </td>\n   <td style=\"text-align:center;\"> 1300.8 </td>\n   <td style=\"text-align:center;\"> -154.5 </td>\n   <td style=\"text-align:center;\"> -53.2 </td>\n   <td style=\"text-align:center;\"> 11904.3 </td>\n   <td style=\"text-align:center;\"> 2483.6 </td>\n   <td style=\"text-align:center;\"> 824.9 </td>\n   <td style=\"text-align:center;\"> 1064.0 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (63.0) </td>\n   <td style=\"text-align:center;\"> (73.6) </td>\n   <td style=\"text-align:center;\"> (65.2) </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (49.4) </td>\n   <td style=\"text-align:center;\"> (65.4) </td>\n   <td style=\"text-align:center;\"> (52.7) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 91 </td>\n   <td style=\"text-align:center;\"> 14407.9 </td>\n   <td style=\"text-align:center;\"> 1559.6 </td>\n   <td style=\"text-align:center;\"> 29.8 </td>\n   <td style=\"text-align:center;\"> 146.2 </td>\n   <td style=\"text-align:center;\"> 11518.7 </td>\n   <td style=\"text-align:center;\"> 2758.8 </td>\n   <td style=\"text-align:center;\"> 1026.1 </td>\n   <td style=\"text-align:center;\"> 1277.9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\">  </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (64.6) </td>\n   <td style=\"text-align:center;\"> (75.6) </td>\n   <td style=\"text-align:center;\"> (66.9) </td>\n   <td style=\"text-align:center;\">  </td>\n   <td style=\"text-align:center;\"> (50.8) </td>\n   <td style=\"text-align:center;\"> (67.2) </td>\n   <td style=\"text-align:center;\"> (54.3) </td>\n  </tr>\n</tbody>\n<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n<span style=\"font-style: italic;\">Nota:</span> <sup></sup> Panel A de la Tabla II en Angrist (1998). Errores estándar entre paréntesis.</td></tr></tfoot>\n</table></div>\n\n`````\n:::\n\n\n\n## Ejemplo: veteranos del ejército de Estados Unidos\n\n- Noten que la columna (2) muestra lo que se hubiera concluido si solo se comparan diferencias de medias\n    \n- Antes de 1980, las diferencias eran muy pequeñas (cero en términos prácticos)\n  \n- En esta aplicación esta comparación llevaría a conclusiones incorrectas\n  \n- Además, las diferencias para no-blancos y blancos son distintas\n  \n- Hay un pico en los efectos alrededor de 1982\n  \n- En esta aplicación, los resultados por *matching* y regresión son muy parecidos hasta 1984\n  \n- La conclusión es que existe evidencia de efectos negativos en los ingresos por haber servido en el ejército en los blancos y efectos positivos para los individuos de otras razas\n\n\n## Ejemplo: veteranos del ejército de Estados Unidos {.columnas-arriba}\n\n\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n- Para personas identificadas como blancas:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ExactMatching_effects_graph_a.jpg){width=100%}\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n- Para personas identificadas como no blancas:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ExactMatching_effects_graph_b.jpg){width=100%}\n:::\n:::\n\n:::\n\n::::\n\n\n\n\n\n# Propensity Score Matching {.divider background-color=\"#9B2247\" data-state=\"nochrome\"}\n\n## Maldición de la dimensionalidad\n \n- En la práctica es difícil manejar problemas en espacios de múltiples dimensiones: **maldición de la dimensionalidad**\n \n- El problema de la maldición de la dimensionalidad se exacerba con el tamaño limitado de las bases de datos\n \n- Si $X$ tuviera $K$ indicadores binarios, el número de posibles combinaciones sería $2^K$\n   \n- Por ejemplo, si solo tuviéramos $X_1=\\{\\text{menor de 35 años}, \\text{con 35 años o más}\\}$, $X_2=\\{\\text{más que preparatoria}, \\text{menos que preparatoria}\\}$, $X_3=\\{\\text{indígena}, \\text{no indígena}\\}$, tendríamos que hacer ocho comparaciones:\n   \n  - menor de 35 años, más que preparatoria, indígena\n  - menor de 35 años, más que preparatoria, no indígena\n  - ...\n  - con 35 años o más, menos que preparatoria, no indígena\n\n- Pero si $X$ incluye muchas variables, algunas tomando muchos valores, esto se vuelve imposible de realizar\n  \n\n## Maldición de la dimensionalidad\n\n- El requerimiento de soporte común significa que debemos tener tratados y no tratados para cada valor de $X$ para hacer comparaciones\n\n- Cuando $X$ tiene muchas dimensiones, resulta un problema de *escasez* o *sparseness*\n\n- Algunas celdas estarán vacías, o solo tendrán tratados, o solo tendrán no tratados\n\n- Si tenemos unidades no tratadas en cada celda donde hay tratados, **aún podemos estimar el TOT**\n\n  - Noten que cuando completamos la muestra emparejada en el ejemplo hipotético, siempre encontramos a alguien en el grupo de control para asignárselo a un tratado\n  \n  - Pero al revés, no siempre es posible: por ejemplo, no hay ningún tratado de 48 años en nuestro ejemplo hipotético\n\n\n\n## Teorema del *propensity score* (Rosenbaum y Rubin, 1983)\n \n- **Teorema 1. Inconfundibilidad dado el propensity score**: el **Supuesto 1** implica\n \n$$\n\\{Y(0), Y(1)\\} \\perp  D|p(X)\n$$\n \ndonde $p(X)=\\Pr(D=1|X)$ es la probabilidad de ser tratado dado un conjunto de covariables $X$, el *propensity score* o PS\n \n- El efecto del tratamiento, bajo el supuesto de inconfundibilidad dado el propensity score, es:\n   \n$$\\Delta_{TOT}=E\\left(\\mu_1(p(X))-\\mu_0(p(X))|D=1\\right)$$\n\ndonde $\\mu_d(p(X))=E(Y|D=d,p(X))$\n\n## Estimación\n \n- Debemos primero especificar y estimar el PS (probit o logit son los métodos más comunes)\n \n- Se realiza el *match* de unidades tratadas con unidades que no lo fueron usando el PS\n\n- Se comprueba la calidad del *matching*\n\n- Se estima la diferencia en la variable de resultados entre estos grupos, así como su error estándar\n   \n\n## Estimación del modelo del PS\n \n- Se usa un modelo *probit* o *logit*\n\n- Se deben seleccionar las características incluidas en el modelo \n \n- **Prueba y error**: maximizar la tasa de clasificación de tratamientos y controles usando $\\bar{p}$, la proporción de tratamientos en la muestra\n\n- **Significancia estadística**: usar solo las variables estadísticamente significativas, comenzando con un modelo muy básico\n\n- **Validación cruzada**: comenzar con un modelo simple y agregar grupos de variables comparando las que reduzcan el error cuadrático promedio\n\n## Estimación del modelo del PS\n\n- Las características usadas para calcular el PS no deben haber sido afectadas por el tratamiento\n \n- Idealmente usamos variables $X$ pre-intervención\n \n- Cuando no hay $X$ pre-intervención, a veces se puede obtener el PS con variables post-intervención siempre y cuando estas no hayan sido afectadas por el tratamiento (pocas veces recomendado)\n\n## Algoritmos de *matching*\n\n- **Vecino más cercano**: a cada individuo del grupo tratado se le asigna el individuo del grupo no tratado con el PS más cercano\n \n- **$M$ vecinos más cercanos**: a cada individuo del grupo tratado se le asignan los $M$ individuos del grupo no tratado con el PS más cercano (*ratio* en R define el número de vecinos)\n\n- El método de vecinos más cercanos puede generar malos emparejamientos si los vecinos más cercanos están muy lejos en términos del PS\n  \n- **Vecino más cercano con caliper**: consiste en definir una vecindad aceptable de matching (el *caliper*) y elegir solo el vecino más cercano dentro del caliper\n\n- **$M$ vecinos más cercanos con caliper**: consiste en hacer *match* con $M$ individuos dentro del *caliper*\n\n## Algoritmos de *matching*\n\n- **Radio**: todos los no tratados dentro del caliper son usados para hacer *match*\n\n- **Estratificación**: parte la región de soporte común en bloques de acuerdo al PS, estima el efecto de tratamiento dentro de cada bloque y, posiblemente, agrega los efectos de acuerdo con la distribución del PS\n\n- **Kernel**: todas las unidades no tratadas son usadas para hacer *match*, pesándolas apropiadamente con unos pesos que decaen conforme a la distancia en términos del PS (reduce la varianza, pero incrementa el sesgo)\n\n- Y muchos otros: **genético**, **cardinal**, **óptimo**, **completo**, etc.\n\n- No hay un método claramente superior a todos los demás\n \n- Puede hacerse con reemplazo o sin reemplazo\n \n- Se recomienda mostrar la robustez respecto a las decisiones tomadas\n\n\n\n\n\n \n\n\n\n## Calidad del *matching*\n\n- Para estimar el TOT se requiere que se cumpla el soporte común, por lo que se debe verificar el traslape del PS calculado para los tratados y no tratados\n \n- Otro de los teoremas de Rosenbaum y Rubin (1983) implica que\n\n$$\nX \\perp  D|p(X)\n$$\n \n- Esto es, que al controlar por el PS, las variables $X$ no deben proveer información sobre $D$\n   \n- Se recomienda también hacer una prueba de estratificación\n\n  1. Dividir el rango del soporte común en bloques \n \n  1. Hacer una prueba de medias del PS entre grupos dentro de cada bloque\n \n  1. Hacer una prueba de medias de cada variable en $X$ entre grupos dentro de cada bloque\n\n\n## Estimación del TOT e inferencia estadística\n\n- Con la muestra emparejada, procedemos a estimar el efecto del tratamiento y su error estándar\n\n- Existe una gran variedad de formas de proceder, así como de críticas a las formas en que otros lo hacen\n\n- La primera edición de MT usaba métodos de simulación basados en el paquete *Zelig* (ya descontinuado)\n\n- En CA se propone usar bootstrap para tomar en cuenta la etapa de estimación del PS usando el paquete *Matching*\n\n- Para nuestra práctica, usaremos el paquete [*MatchIt*](https://kosukeimai.github.io/MatchIt/index.html), con un enfoque de regresión o *g-computation* para estimar los efectos\n\n\n\n \n## Conclusión sobre el PSM\n\n- El uso del PSM requiere de supuestos teóricos fuertes\n\n- La implementación implica que las variables en $X$ son aquellas que permiten asumir la inconfundibilidad dado el PS\n\n- Hay una gran cantidad de decisiones en el proceso de estimación\n\n- La crítica más importante es que la mayoría de las veces nos preocupa más la autoselección basada en no observables que en observables\n\n- Pero muchas veces es todo lo que tenemos a la mano\n\n- Hacer análisis de sensibilidad a las distintas decisiones y presentar resultados transparentes \n \n\n# Regresión {.divider background-color=\"#9B2247\" data-state=\"nochrome\"}\n\n## Regresión\n\nPróximamente\n\n# *Inverse probability weighting* {.divider background-color=\"#9B2247\" data-state=\"nochrome\"}\n\n## *Inverse probability weighting*\n\nPróximamente\n\n# Métodos doblemente robustos {.divider background-color=\"#9B2247\" data-state=\"nochrome\"}\n\n## *Métodos doblemente robustos*\n\nPróximamente\n\n\n\n# Anexo 1: ejemplos de algoritmos de *matching* basados en el PS {.divider background-color=\"#9B2247\" data-state=\"nochrome\"}\n\n\n::: {.cell}\n\n:::\n\n\n## Vecino más cercano\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-paper lightable-hover\" style='font-family: \"Arial Narrow\", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Tratados </th>\n   <th style=\"text-align:center;\"> \\(\\hat{p}\\) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> a </td>\n   <td style=\"text-align:center;\"> 0.031 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> b </td>\n   <td style=\"text-align:center;\"> 0.042 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> c </td>\n   <td style=\"text-align:center;\"> 0.07 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> \\(\\vdots\\) </td>\n   <td style=\"text-align:center;\"> \\(\\vdots\\) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-paper lightable-hover\" style='font-family: \"Arial Narrow\", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> No tratados </th>\n   <th style=\"text-align:center;\"> \\(\\hat{p}\\) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> A </td>\n   <td style=\"text-align:center;\"> 0.034 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> B </td>\n   <td style=\"text-align:center;\"> 0.068 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> C </td>\n   <td style=\"text-align:center;\"> 0.21 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> \\(\\vdots\\) </td>\n   <td style=\"text-align:center;\"> \\(\\vdots\\) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n:::\n\n::::\n\n- Con vecino más cercano, el individuo $a$ tratado estaría emparejado con el $A$ no tratado\n\n- Si el emparejamiento es con reemplazo, $A$ podría ser usado otra vez y $b$ también sería emparejado con $A$\n\n- Pero si el emparejamiento es sin reemplazo, $A$ ya no puede ser usado y a $b$ se le emparejaría con $B$\n\n- Cuando hacemos el emparejamiento sin reemplazo, debemos tener una muestra lo suficientemente grande\n\n- El emparejamiento sin reemplazo depende del orden en que se realice el procedimiento\n\n\n## Vecino más cercano con caliper\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-paper lightable-hover\" style='font-family: \"Arial Narrow\", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Tratados </th>\n   <th style=\"text-align:center;\"> \\(\\hat{p}\\) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> a </td>\n   <td style=\"text-align:center;\"> 0.031 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> b </td>\n   <td style=\"text-align:center;\"> 0.042 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> c </td>\n   <td style=\"text-align:center;\"> 0.07 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> d </td>\n   <td style=\"text-align:center;\"> 0.11 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> \\(\\vdots\\) </td>\n   <td style=\"text-align:center;\"> \\(\\vdots\\) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-paper lightable-hover\" style='font-family: \"Arial Narrow\", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> No tratados </th>\n   <th style=\"text-align:center;\"> \\(\\hat{p}\\) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> A </td>\n   <td style=\"text-align:center;\"> 0.034 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> B </td>\n   <td style=\"text-align:center;\"> 0.068 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> C </td>\n   <td style=\"text-align:center;\"> 0.21 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> D </td>\n   <td style=\"text-align:center;\"> 0.40 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> \\(\\vdots\\) </td>\n   <td style=\"text-align:center;\"> \\(\\vdots\\) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n:::\n\n::::\n\n- El primer paso es fijar el caliper, por ejemplo, de 0.1\n\n- El caliper implica buscar al vecino más cercano dentro de una vecindad de 0.1\n\n- En este ejemplo $d$ se emparejaría con $B$ si $B$ aún está disponible (porque no ha sido emparejado con nadie o porque, aunque haya sido emparejado, el procedimiento se hace con reemplazo)\n\n- $D$ queda fuera del caliper y nunca se usa \n\n\n## $M$ vecinos más cercanos con caliper\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-paper lightable-hover\" style='font-family: \"Arial Narrow\", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Tratados </th>\n   <th style=\"text-align:center;\"> \\(\\hat{p}\\) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> d </td>\n   <td style=\"text-align:center;\"> 0.31 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> e </td>\n   <td style=\"text-align:center;\"> 0.39 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> f </td>\n   <td style=\"text-align:center;\"> 0.44 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> g </td>\n   <td style=\"text-align:center;\"> 0.52 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> h </td>\n   <td style=\"text-align:center;\"> 0.55 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> i </td>\n   <td style=\"text-align:center;\"> 0.62 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> \\(\\vdots\\) </td>\n   <td style=\"text-align:center;\"> \\(\\vdots\\) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-paper lightable-hover\" style='font-family: \"Arial Narrow\", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> No tratados </th>\n   <th style=\"text-align:center;\"> \\(\\hat{p}\\) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> R </td>\n   <td style=\"text-align:center;\"> 0.27 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> S </td>\n   <td style=\"text-align:center;\"> 0.29 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> T </td>\n   <td style=\"text-align:center;\"> 0.33 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> U </td>\n   <td style=\"text-align:center;\"> 0.49 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> V </td>\n   <td style=\"text-align:center;\"> 0.57 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> W </td>\n   <td style=\"text-align:center;\"> 0.61 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> \\(\\vdots\\) </td>\n   <td style=\"text-align:center;\"> \\(\\vdots\\) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n:::\n\n::::\n\n- Si se utiliza un caliper de 0.1 y dos vecinos, a $g$ se le asignarían $U$ y $V$ (si estuvieran disponibles)\n\n- Es decir, dentro del caliper, los dos individuos con el PS más cercano\n\n\n## Radio\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-paper lightable-hover\" style='font-family: \"Arial Narrow\", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Tratados </th>\n   <th style=\"text-align:center;\"> \\(\\hat{p}\\) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> d </td>\n   <td style=\"text-align:center;\"> 0.31 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> e </td>\n   <td style=\"text-align:center;\"> 0.39 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> f </td>\n   <td style=\"text-align:center;\"> 0.44 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> g </td>\n   <td style=\"text-align:center;\"> 0.52 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> h </td>\n   <td style=\"text-align:center;\"> 0.55 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> i </td>\n   <td style=\"text-align:center;\"> 0.62 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> \\(\\vdots\\) </td>\n   <td style=\"text-align:center;\"> \\(\\vdots\\) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-paper lightable-hover\" style='font-family: \"Arial Narrow\", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> No tratados </th>\n   <th style=\"text-align:center;\"> \\(\\hat{p}\\) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> R </td>\n   <td style=\"text-align:center;\"> 0.27 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> S </td>\n   <td style=\"text-align:center;\"> 0.29 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> T </td>\n   <td style=\"text-align:center;\"> 0.33 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> U </td>\n   <td style=\"text-align:center;\"> 0.49 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> V </td>\n   <td style=\"text-align:center;\"> 0.57 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> W </td>\n   <td style=\"text-align:center;\"> 0.61 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> \\(\\vdots\\) </td>\n   <td style=\"text-align:center;\"> \\(\\vdots\\) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n:::\n\n::::\n\n- Pero si ahora implementamos radio con un caliper de 0.1, a $g$ se le asignarían $U$, $V$ y $W$ (si estuvieran disponibles)\n\n- Es decir, todos los individuos dentro del caliper\n\n\n## Kernel\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-paper lightable-hover\" style='font-family: \"Arial Narrow\", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> Tratados </th>\n   <th style=\"text-align:center;\"> \\(\\hat{p}\\) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> d </td>\n   <td style=\"text-align:center;\"> 0.31 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> e </td>\n   <td style=\"text-align:center;\"> 0.39 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> f </td>\n   <td style=\"text-align:center;\"> 0.44 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> g </td>\n   <td style=\"text-align:center;\"> 0.52 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> h </td>\n   <td style=\"text-align:center;\"> 0.55 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> i </td>\n   <td style=\"text-align:center;\"> 0.62 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-paper lightable-hover\" style='font-family: \"Arial Narrow\", arial, helvetica, sans-serif; width: auto !important; margin-left: auto; margin-right: auto;'>\n <thead>\n  <tr>\n   <th style=\"text-align:center;\"> No tratados </th>\n   <th style=\"text-align:center;\"> \\(\\hat{p}\\) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:center;\"> R </td>\n   <td style=\"text-align:center;\"> 0.27 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> S </td>\n   <td style=\"text-align:center;\"> 0.29 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> T </td>\n   <td style=\"text-align:center;\"> 0.33 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> U </td>\n   <td style=\"text-align:center;\"> 0.49 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> V </td>\n   <td style=\"text-align:center;\"> 0.57 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:center;\"> W </td>\n   <td style=\"text-align:center;\"> 0.61 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n:::\n\n::::\n\n- Supongamos que estos son todos nuestros datos\n\n- Con un emparejamiento por kernel, a $d$ lo *emparejamos* con todos los individuos, desde $R$ hasta $W$\n\n- La función kernel le dará más peso a $T$ y $S$, un poco menos a $R$ y así hasta darle muy poco o casi nada de peso a $W$\n\n\n# Selección por Observables {.final background-color=\"#9B2247\" data-state=\"nochrome\"}\n\n::: {.f-eyebrow}\nInferencia Causal\n:::\n\n::: {.f-inst}\n[Irvin Rojas](https://rojasirvin.github.io/)\n:::\n\n::: {.f-inst}\nCIDE · Maestría en Economía\n:::\n\n<span class=\"f-icons\"><a href=\"https://github.com/rojasirvin\" target=\"_blank\" aria-label=\"GitHub\"><i class=\"bi bi-github\"></i></a> <a href=\"https://scholar.google.com/citations?hl=es&user=FUwdSTMAAAAJ&view_op=list_works&sortby=pubdate\" target=\"_blank\" aria-label=\"Google Scholar\"><i class=\"bi bi-mortarboard-fill\"></i></a> <a href=\"mailto:irvin.rojas@cide.edu\" aria-label=\"Correo\"><i class=\"bi bi-envelope-fill\"></i></a></span>\n\n::: {.f-rule}\n:::\n\n::: {.f-copy}\n© 2026 Irvin Rojas. Distribuido bajo licencia Creative Commons **CC BY-NC-SA 4.0**. Los materiales de terceros citados conservan sus propios derechos.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}